-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table order_items of database oracle (Oracle).

CREATE TABLE order_items (
    order_id number(19) NOT NULL,
    line_no number(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku char(20 char) NOT NULL,
    quantity number(19) NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0)
);
CREATE INDEX ix_order_lines_product ON order_items (sku);
