using Maquettiste.Engine.Model;
using Maquettiste.Engine.Rendering;
using Maquettiste.Testing;

namespace Maquettiste.Engine.Tests.Rendering;

/// <summary>The per-run template cache and the pure parts of the helpers.</summary>
public sealed class TemplateCacheAndHelperTests
{
    [Fact]
    public void Templates_are_parsed_once_per_content_and_delimiters_and_read_once_per_run()
    {
        using var pack = new TempPack("cache", new Dictionary<string, string> { ["a.scriban"] = "A {{ 1 }}", ["./b.scriban"] = "B" });
        var loaded = pack.Load(RenderKit.Manifest("cache", new PackUnit { Id = "a", Template = "a.scriban", For = "model" }));
        var cache = new TemplateCache();

        var first = cache.Get(loaded, "a.scriban", null);
        Assert.Same(first, cache.Get(loaded, "./a.scriban", null));
        Assert.Same(first, cache.Get(loaded, "a.scriban", new Delimiters { Open = "{{", Close = "}}" }));
        var custom = cache.Get(loaded, "a.scriban", new Delimiters { Open = "<%", Close = "%>" });
        Assert.NotSame(first, custom);
        Assert.Equal(".maquettiste/templates/cache/a.scriban", cache.Describe(first)!.RepoPath);
        Assert.NotNull(cache.Describe(custom)!.Map);

        // Within a run the file is read once; a new run (a new cache) sees the change.
        pack.Write("a.scriban", "changed");
        Assert.Same(first, cache.Get(loaded, "a.scriban", null));
        Assert.Equal("changed", new TemplateCache().Get(loaded, "a.scriban", null).Render());
    }

    [Fact]
    public void Parse_failures_are_cached_and_reported_as_MQ6003()
    {
        using var pack = new TempPack("cache", new Dictionary<string, string> { ["bad.scriban"] = "\r\nline two {{ end }}" });
        var loaded = pack.Load(RenderKit.Manifest("cache", new PackUnit { Id = "a", Template = "bad.scriban", For = "model" }));
        var cache = new TemplateCache();
        var first = Assert.Throws<TemplateException>(() => cache.Get(loaded, "bad.scriban", null));
        var second = Assert.Throws<TemplateException>(() => cache.Get(loaded, "bad.scriban", null));
        Assert.Same(first, second);
        var d = first.Diagnostics[0];
        Assert.Equal("MQ6003", d.Rule);
        Assert.Equal(2, d.Line);
        Assert.True(d.Column >= 10, "column " + d.Column);
        Assert.Equal(".maquettiste/templates/cache/bad.scriban", d.FilePath);
    }

    [Fact]
    public void Template_files_must_be_utf8_and_lose_their_bom_and_crlf()
    {
        using var pack = new TempPack("cache", new Dictionary<string, string>());
        File.WriteAllBytes(Path.Combine(pack.Root, "bom.scriban"), [0xEF, 0xBB, 0xBF, (byte)'a', (byte)'\r', (byte)'\n', (byte)'b']);
        File.WriteAllBytes(Path.Combine(pack.Root, "latin1.scriban"), [(byte)'a', 0xE9]);
        var loaded = pack.Load(RenderKit.Manifest("cache", new PackUnit { Id = "a", Template = "bom.scriban", For = "model" }));
        var cache = new TemplateCache();
        Assert.Equal("a\nb", cache.ReadText(loaded, "bom.scriban"));
        var error = Assert.Throws<TemplateException>(() => cache.Get(loaded, "latin1.scriban", null));
        Assert.Contains("UTF-8", error.Diagnostics[0].Message, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("a.scriban", "a.scriban")]
    [InlineData("./dir/a.scriban", "dir/a.scriban")]
    [InlineData("dir\\a.scriban", "dir/a.scriban")]
    [InlineData("../a.scriban", null)]
    [InlineData("dir/../a.scriban", null)]
    [InlineData("/abs.scriban", null)]
    [InlineData("C:/x.scriban", null)]
    [InlineData("dir//a.scriban", null)]
    [InlineData("", null)]
    public void Pack_paths_are_normalized_or_refused(string path, string? expected)
    {
        Assert.Equal(expected is not null, PackPaths.TryNormalize(path, out var normalized, out _));
        Assert.Equal(expected, normalized);
    }

    [Fact]
    public void Indent_and_dedent()
    {
        Assert.Equal("  a\n  b\n\n  c", BuiltinHelpers.Indent("a\nb\n\nc", "  "));
        Assert.Equal("", BuiltinHelpers.Indent("", "  "));
        Assert.Equal("a\n  b\n\nc", BuiltinHelpers.Dedent("    a\n      b\n  \n    c"));
        Assert.Equal("a\n\tb", BuiltinHelpers.Dedent("\ta\n\t\tb"));
        Assert.Equal("a\n b", BuiltinHelpers.Dedent("a\n b"));
    }

    [Fact]
    public void Escaping()
    {
        Assert.Equal("\\# a \\*b\\* \\_c\\_ \\`d\\` \\[e\\]\\(f\\) \\<g\\> \\| \\~ \\! \\\\ x-y 2.5\n1\\. one\n  \\- two\n\\+ three", BuiltinHelpers.EscapeMarkdown("# a *b* _c_ `d` [e](f) <g> | ~ ! \\ x-y 2.5\n1. one\n  - two\n+ three"));
        Assert.Equal("&lt;a b=&quot;c&quot; d=&apos;e&apos;&gt;&amp;&lt;/a&gt;", BuiltinHelpers.EscapeXml("<a b=\"c\" d='e'>&</a>"));
        Assert.Equal("a\\\"b\\\\c\\nd\\te\\u0001 é <>&", BuiltinHelpers.EscapeJson("a\"b\\c\nd\te\u0001 é <>&"));
        Assert.Equal("-- Generated by Maquettiste (p/u). Do not edit; changes are overwritten.", BuiltinHelpers.Banner("--", "p", "u"));
        Assert.Equal("Generated by Maquettiste (p/u). Do not edit; changes are overwritten.", BuiltinHelpers.Banner("", "p", "u"));
    }

    [Fact]
    public void Sql_quoting_by_dialect_and_mode()
    {
        Assert.Equal("customer", SqlDialects.Quote("customer", Dialect.PostgreSql, Quoting.Reserved));
        Assert.Equal("\"select\"", SqlDialects.Quote("SELECT".ToLowerInvariant(), Dialect.PostgreSql, Quoting.Reserved));
        Assert.Equal("\"User\"", SqlDialects.Quote("User", Dialect.Oracle, Quoting.Reserved));
        Assert.Equal("[order]", SqlDialects.Quote("order", Dialect.SqlServer, Quoting.Reserved));
        Assert.Equal("`key`", SqlDialects.Quote("key", Dialect.MySql, Quoting.Reserved));
        Assert.Equal("\"index\"", SqlDialects.Quote("index", Dialect.Sqlite, Quoting.Reserved));
        Assert.Equal("\"1st\"", SqlDialects.Quote("1st", Dialect.PostgreSql, Quoting.Reserved));
        Assert.Equal("[a]]b]", SqlDialects.Quote("a]b", Dialect.SqlServer, Quoting.Always));
        Assert.Equal("order", SqlDialects.Quote("order", Dialect.PostgreSql, Quoting.Never));
        Assert.True(SqlDialects.TryParse("Postgres", out var pg) && pg == Dialect.PostgreSql);
        Assert.True(SqlDialects.TryParse("mssql", out var ss) && ss == Dialect.SqlServer);
        Assert.False(SqlDialects.TryParse("db2", out _));
    }

    [Fact]
    public void Sql_literals_by_dialect()
    {
        Assert.Equal("'it''s'", SqlDialects.Literal("it's", Dialect.PostgreSql));
        Assert.Equal("N'it''s'", SqlDialects.Literal("it's", Dialect.SqlServer));
        Assert.Equal("'a\\\\b'", SqlDialects.Literal("a\\b", Dialect.MySql));
        Assert.Equal("true", SqlDialects.Literal(true, Dialect.PostgreSql));
        Assert.Equal("0", SqlDialects.Literal(false, Dialect.Oracle));
        Assert.Equal("NULL", SqlDialects.Literal(null, Dialect.Sqlite));
        Assert.Equal("-12", SqlDialects.Literal(-12L, Dialect.MySql));
        Assert.Equal("0.1", SqlDialects.Literal(0.1d, Dialect.PostgreSql));
        Assert.Equal("12.50", SqlDialects.Literal(12.50m, Dialect.PostgreSql));
        Assert.Equal("'2026-01-02'", SqlDialects.Literal(new DateOnly(2026, 1, 2), Dialect.SqlServer));
        Assert.Equal("'2026-01-02T03:04:05'", SqlDialects.Literal(new DateTime(2026, 1, 2, 3, 4, 5), Dialect.PostgreSql));
        Assert.Equal("'2026-01-02T03:04:05.5+02:00'", SqlDialects.Literal(new DateTimeOffset(2026, 1, 2, 3, 4, 5, 500, TimeSpan.FromHours(2)), Dialect.PostgreSql));
        Assert.Equal("'13:45:00'", SqlDialects.Literal(new TimeOnly(13, 45), Dialect.PostgreSql));
        Assert.Throws<ArgumentException>(() => SqlDialects.Literal(double.NaN, Dialect.PostgreSql));
        Assert.Throws<ArgumentException>(() => SqlDialects.Literal(new[] { 1 }, Dialect.PostgreSql));
    }

    [Fact]
    public async Task Json_is_canonical_and_rejects_model_objects()
    {
        var model = await BillingModel.GetAsync();
        var invoice = model.Entities.Single(e => e.Name == "Invoice");
        var unit = await Adhoc.RenderAsync("{{ json {z: [1, 2.5, 'x'], a: null, m: {b: true, a: 'é\"'}} }}|{{ json 'plain' }}|{{ json entity.tags }}", invoice);
        Assert.Equal("{\"a\":null,\"m\":{\"a\":\"é\\\"\",\"b\":true},\"z\":[1,2.5,\"x\"]}|\"plain\"|[\"billing\"]", unit.Text());

        var error = (await Adhoc.RenderAsync("{{ json entity }}", invoice)).Error();
        Assert.Equal("MQ6006", error.Rule);
        Assert.Contains("cannot serialize a entity", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public async Task Helpers_reject_wrong_arguments_with_MQ6006()
    {
        foreach (var template in new[] { "{{ pascal }}", "{{ pascal 'a' 'b' }}", "{{ indent 'a' -1 }}", "{{ type_of 'uuid' 'cobol' }}", "{{ sql_quote 'x' }}",
                     "{{ sql_literal [1] 'postgresql' }}", "{{ type_of 'nope' 'postgresql' }}", "{{ sql_quote 'x' 'postgresql' 'sometimes' }}",
                     "{{ pascal model.entities }}", "{{ snake pack }}", "{{ kebab model }}", "{{ json date }}" })
        {
            var unit = await Adhoc.RenderAsync(template);
            Assert.True(unit.Failed, template);
            Assert.Equal("MQ6006", Assert.Single(unit.Diagnostics).Rule);
        }
    }

    [Fact]
    public async Task Type_of_uses_pack_maps_then_dialects()
    {
        var model = await BillingModel.GetAsync();
        var customer = model.Entities.Single(e => e.Name == "Customer");
        var files = new Dictionary<string, string>
        {
            ["types/ts.json"] = "{ \"uuid\": \"string\", \"string\": \"string\", \"date\": \"Date\", \"datetimeoffset\": \"Date\", \"nullable\": \"{type} | null\", \"Email\": \"EmailAddress\" }",
        };
        var unit = await Adhoc.RenderAsync(
            "{{ for a in entity.attributes }}{{ a.name }}:{{ type_of a 'ts' }}/{{ type_of a.type 'ts' }}/{{ type_of a 'sqlserver' }};{{ end }}", customer, files: files);
        var text = unit.Text();
        Assert.Contains("customerSince:Date | null/Date/date;", text, StringComparison.Ordinal);
        Assert.Contains("name:string/string/nvarchar(120);", text, StringComparison.Ordinal);
        Assert.Contains("id:string/string/uniqueidentifier;", text, StringComparison.Ordinal);

        var main = model.Databases.Single(d => d.Name == "main");
        var column = main.Tables.SelectMany(t => t.Columns).First(c => c.Type == "decimal");
        var table = main.Tables.Single(t => t.Columns.Contains(column));
        var columnUnit = await Adhoc.RenderAsync(
            $"{{{{ c = (lookup '{table.Id}').columns | array.first }}}}{{{{ for c in (lookup '{table.Id}').columns }}}}{{{{ if c.name == '{column.Name}' }}}}{{{{ type_of c 'postgresql' }}}}|{{{{ type_of c 'oracle' }}}}{{{{ end }}}}{{{{ end }}}}");
        Assert.Equal(column.NativeType + "|number(" + (column.Precision ?? 18) + "," + (column.Scale ?? 2) + ")", columnUnit.Text());
    }

    [Fact]
    public async Task Type_of_a_dialect_takes_a_custom_types_native_type()
    {
        var b = new ModelBuilder(seed: 57);
        var lsn = b.ScalarType("Lsn", "binary").Length(8).NativeType("postgresql", "pg_lsn").NativeType("sqlserver", "binary({length})");
        b.Entity("Thing").Key("id", "int64").Attr("at", lsn);
        b.Database("db", Dialect.PostgreSql);
        var model = Resolution.ResolutionKit.Resolve(b);
        var unit = await Adhoc.RenderAsync(
            "{{ for a in entity.attributes }}{{ a.name }}:{{ type_of a 'postgresql' }}/{{ type_of a.type 'sqlserver' }}/{{ type_of a 'oracle' }};{{ end }}"
            + "{{ type_of (model.scalar_types | array.first) 'sqlserver' }}|{{ (model.scalar_types | array.first).native_types.postgresql }}",
            model.Entities.Single(e => e.Name == "Thing"), model: model);
        Assert.Equal("id:bigint/bigint/number(19);at:pg_lsn/binary(8)/blob;binary(8)|pg_lsn", unit.Text());
    }
}
