-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.advance_ship_notices of database main (PostgreSQL 16).
-- Maps entity AdvanceShipNotice.

CREATE TABLE northwind.advance_ship_notices (
    id uuid NOT NULL,
    asn_number varchar(40) NOT NULL,
    shipped_on date NULL,
    expected_arrival_on date NULL,
    carrier_name varchar(100) NULL,
    tracking_number varchar(60) NULL,
    raw_document jsonb NULL,
    purchase_order_id uuid NULL,
    supplier_id uuid NOT NULL,
    CONSTRAINT pk_advance_ship_notices PRIMARY KEY (id),
    CONSTRAINT fk_advance_ship_notices_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES northwind.purchase_orders (id) ON DELETE SET NULL,
    CONSTRAINT fk_advance_ship_notices_supplier_id FOREIGN KEY (supplier_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT
);
