-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.agreement_lines of database main (PostgreSQL 16).
-- Maps entity AgreementLine.

CREATE TABLE northwind.agreement_lines (
    id uuid NOT NULL,
    agreed_price_amount numeric(19,4) NULL,
    agreed_price_currency varchar(3) NULL,
    discount numeric(5,2) NULL,
    minimum_quantity numeric(12,3) NULL,
    product_category_id uuid NULL,
    product_id uuid NULL,
    customer_price_agreement_id uuid NOT NULL,
    CONSTRAINT pk_agreement_lines PRIMARY KEY (id),
    CONSTRAINT fk_agreement_lines_product_category_id FOREIGN KEY (product_category_id) REFERENCES northwind.product_categories (id) ON DELETE SET NULL,
    CONSTRAINT fk_agreement_lines_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE SET NULL,
    CONSTRAINT fk_agreement_lines_customer_price_agreement_id FOREIGN KEY (customer_price_agreement_id) REFERENCES northwind.customer_price_agreements (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.agreement_lines IS 'A price or discount for a product or a whole category within a customer agreement.';
COMMENT ON COLUMN northwind.agreement_lines.id IS 'Surrogate key of the agreement line.';
COMMENT ON COLUMN northwind.agreement_lines.agreed_price_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.agreement_lines.agreed_price_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.agreement_lines.discount IS 'Discount off list price, when no fixed price is agreed.';
COMMENT ON COLUMN northwind.agreement_lines.minimum_quantity IS 'Minimum order quantity for the price.';
