-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.api_keys of database main (PostgreSQL 16).

CREATE TABLE northwind.api_keys (
    id char(26) NOT NULL,
    prefix varchar(12) NOT NULL,
    key_hash varchar(128) NOT NULL,
    expires_on date NULL,
    last_used_at timestamptz(6) NULL,
    revoked_at timestamptz(6) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    api_client_id uuid NOT NULL,
    CONSTRAINT pk_api_keys PRIMARY KEY (id),
    CONSTRAINT uq_api_keys_prefix UNIQUE (prefix),
    CONSTRAINT fk_api_keys_api_client_id FOREIGN KEY (api_client_id) REFERENCES northwind.api_clients (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.api_keys IS 'A secret credential of an API client; only a hash is stored.';
COMMENT ON COLUMN northwind.api_keys.id IS 'Surrogate key of the api key.';
COMMENT ON COLUMN northwind.api_keys.prefix IS 'Public prefix shown in the console to identify the key.';
COMMENT ON COLUMN northwind.api_keys.key_hash IS 'SHA-256 hash of the secret.';
COMMENT ON COLUMN northwind.api_keys.expires_on IS 'Expiry date; null for no expiry.';
COMMENT ON COLUMN northwind.api_keys.last_used_at IS 'Most recent use.';
COMMENT ON COLUMN northwind.api_keys.revoked_at IS 'When the key was revoked.';
COMMENT ON COLUMN northwind.api_keys.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.api_keys.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.api_keys.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.api_keys.updated_by IS 'User name of the last editor.';
