-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.api_clients of database main (PostgreSQL 16).
-- Maps entity ApiClient.

CREATE TABLE northwind.api_clients (
    id uuid NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(500) NULL,
    owner_email varchar(254) NOT NULL,
    allowed_scopes varchar(1000) NOT NULL,
    rate_limit_per_minute integer NOT NULL DEFAULT 600,
    is_enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    deleted_at timestamptz(6) NULL,
    CONSTRAINT pk_api_clients PRIMARY KEY (id),
    CONSTRAINT uq_api_clients_name UNIQUE (name)
);
