-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.api_keys of database main (PostgreSQL 16).
-- Maps entity ApiKey.

CREATE TABLE northwind.api_keys (
    id char(26) NOT NULL,
    prefix varchar(12) NOT NULL,
    key_hash varchar(128) NOT NULL,
    expires_on date NULL,
    last_used_at timestamptz(6) NULL,
    revoked_at timestamptz(6) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    api_client_id uuid NOT NULL,
    CONSTRAINT pk_api_keys PRIMARY KEY (id),
    CONSTRAINT uq_api_keys_prefix UNIQUE (prefix),
    CONSTRAINT fk_api_keys_api_client_id FOREIGN KEY (api_client_id) REFERENCES northwind.api_clients (id) ON DELETE CASCADE
);
