-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.applied_promotions of database main (PostgreSQL 16).
-- Maps entity AppliedPromotion.

CREATE TABLE northwind.applied_promotions (
    id uuid NOT NULL,
    discount_amount_amount numeric(19,4) NOT NULL,
    discount_amount_currency varchar(3) NOT NULL,
    applied_at timestamptz(6) NOT NULL,
    promotion_id uuid NOT NULL,
    sales_order_line_id char(26) NULL,
    sales_order_id uuid NOT NULL,
    CONSTRAINT pk_applied_promotions PRIMARY KEY (id),
    CONSTRAINT fk_applied_promotions_promotion_id FOREIGN KEY (promotion_id) REFERENCES northwind.promotions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_applied_promotions_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES northwind.sales_order_lines (id) ON DELETE CASCADE,
    CONSTRAINT fk_applied_promotions_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES northwind.sales_orders (id) ON DELETE CASCADE
);
