-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.audit_events of database main (PostgreSQL 16).
-- Maps entity AuditEvent.

CREATE TABLE northwind.audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    occurred_at timestamptz(6) NOT NULL,
    action varchar(80) NOT NULL,
    entity_type varchar(80) NOT NULL,
    entity_key varchar(64) NOT NULL,
    details jsonb NULL,
    ip_address varchar(45) NULL,
    actor_id uuid NULL,
    CONSTRAINT pk_audit_events PRIMARY KEY (id),
    CONSTRAINT fk_audit_events_actor_id FOREIGN KEY (actor_id) REFERENCES northwind.user_accounts (id) ON DELETE SET NULL
);
CREATE INDEX ix_audit_events_entity ON northwind.audit_events (entity_type, entity_key);
CREATE INDEX ix_audit_events_occurred_at ON northwind.audit_events (occurred_at);
COMMENT ON TABLE northwind.audit_events IS 'Details are stored as jsonb so auditors can query inside them.';
COMMENT ON COLUMN northwind.audit_events.id IS 'Surrogate key of the audit event.';
COMMENT ON COLUMN northwind.audit_events.occurred_at IS 'When the action happened.';
COMMENT ON COLUMN northwind.audit_events.action IS 'What happened, such as role.granted.';
COMMENT ON COLUMN northwind.audit_events.entity_type IS 'Kind of record affected.';
COMMENT ON COLUMN northwind.audit_events.entity_key IS 'Key of the record affected.';
COMMENT ON COLUMN northwind.audit_events.details IS 'Before and after values, queried with jsonb operators.';
COMMENT ON COLUMN northwind.audit_events.ip_address IS 'Client IP address.';
