-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.backorders of database main (PostgreSQL 16).
-- Maps entity Backorder.

CREATE TABLE northwind.backorders (
    id uuid NOT NULL,
    quantity numeric(12,3) NOT NULL,
    expected_on date NULL,
    customer_notified_at timestamptz(6) NULL,
    is_fulfilled boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    purchase_order_line_id uuid NULL,
    sales_order_line_id char(26) NOT NULL,
    CONSTRAINT pk_backorders PRIMARY KEY (id),
    CONSTRAINT fk_backorders_purchase_order_line_id FOREIGN KEY (purchase_order_line_id) REFERENCES northwind.purchase_order_lines (id) ON DELETE SET NULL,
    CONSTRAINT fk_backorders_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES northwind.sales_order_lines (id) ON DELETE CASCADE
);
