-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.billing_accounts of database main (PostgreSQL 16).

CREATE TABLE northwind.billing_accounts (
    id uuid NOT NULL,
    account_number varchar(20) NOT NULL,
    name varchar(120) NOT NULL,
    billing_address_line1 varchar(120) NOT NULL,
    billing_address_line2 varchar(120) NULL,
    billing_address_city varchar(80) NOT NULL,
    billing_address_region varchar(80) NULL,
    billing_address_postal_code varchar(20) NULL,
    billing_address_country_code varchar(2) NOT NULL,
    invoice_delivery_method varchar(20) NOT NULL DEFAULT 'email',
    invoice_email varchar(254) NULL,
    consolidate_invoices boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    currency_code varchar(3) NULL,
    CONSTRAINT pk_billing_accounts PRIMARY KEY (id),
    CONSTRAINT uq_billing_accounts_account_number UNIQUE (account_number),
    CONSTRAINT fk_billing_accounts_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE CASCADE,
    CONSTRAINT fk_billing_accounts_currency_code FOREIGN KEY (currency_code) REFERENCES northwind.currencies (code) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.billing_accounts IS 'How and where a customer wants to be invoiced; large customers have one per division.';
COMMENT ON COLUMN northwind.billing_accounts.id IS 'Surrogate key of the billing account.';
COMMENT ON COLUMN northwind.billing_accounts.account_number IS 'Billing account number.';
COMMENT ON COLUMN northwind.billing_accounts.name IS 'Account name, such as Facilities division.';
COMMENT ON COLUMN northwind.billing_accounts.billing_address_line1 IS 'Street and number, or PO box.';
COMMENT ON COLUMN northwind.billing_accounts.billing_address_line2 IS 'Suite, floor or building.';
COMMENT ON COLUMN northwind.billing_accounts.billing_address_city IS 'City or locality.';
COMMENT ON COLUMN northwind.billing_accounts.billing_address_region IS 'State, province or county.';
COMMENT ON COLUMN northwind.billing_accounts.billing_address_postal_code IS 'Postal or ZIP code.';
COMMENT ON COLUMN northwind.billing_accounts.billing_address_country_code IS 'ISO country code.';
COMMENT ON COLUMN northwind.billing_accounts.invoice_delivery_method IS 'email, portal, edi or mail.';
COMMENT ON COLUMN northwind.billing_accounts.invoice_email IS 'Mailbox for invoices.';
COMMENT ON COLUMN northwind.billing_accounts.consolidate_invoices IS 'Whether to send one monthly invoice.';
COMMENT ON COLUMN northwind.billing_accounts.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.billing_accounts.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.billing_accounts.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.billing_accounts.updated_by IS 'User name of the last editor.';
