-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.blanket_order_lines of database main (PostgreSQL 16).

CREATE TABLE northwind.blanket_order_lines (
    id uuid NOT NULL,
    committed_quantity numeric(12,3) NOT NULL,
    released_quantity numeric(12,3) NOT NULL DEFAULT 0,
    unit_price_amount numeric(19,4) NOT NULL,
    unit_price_currency varchar(3) NOT NULL,
    blanket_order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    CONSTRAINT pk_blanket_order_lines PRIMARY KEY (id),
    CONSTRAINT fk_blanket_order_lines_blanket_order_id FOREIGN KEY (blanket_order_id) REFERENCES northwind.blanket_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_blanket_order_lines_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT
);
COMMENT ON TABLE northwind.blanket_order_lines IS 'A product and quantity committed on a blanket order.';
COMMENT ON COLUMN northwind.blanket_order_lines.id IS 'Surrogate key of the blanket order line.';
COMMENT ON COLUMN northwind.blanket_order_lines.committed_quantity IS 'Quantity committed.';
COMMENT ON COLUMN northwind.blanket_order_lines.released_quantity IS 'Quantity released so far.';
COMMENT ON COLUMN northwind.blanket_order_lines.unit_price_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.blanket_order_lines.unit_price_currency IS 'The ISO 4217 currency of the amount.';
