-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.blanket_orders of database main (PostgreSQL 16).
-- Maps entity BlanketOrder.

CREATE TABLE northwind.blanket_orders (
    id uuid NOT NULL,
    blanket_number varchar(20) NOT NULL,
    validity_starts_on date NOT NULL,
    validity_ends_on date NULL,
    committed_amount_amount numeric(19,4) NOT NULL,
    committed_amount_currency varchar(3) NOT NULL,
    released_amount_amount numeric(19,4) NOT NULL,
    released_amount_currency varchar(3) NOT NULL,
    is_closed boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    currency_code varchar(3) NOT NULL,
    customer_id uuid NOT NULL,
    CONSTRAINT pk_blanket_orders PRIMARY KEY (id),
    CONSTRAINT uq_blanket_orders_blanket_number UNIQUE (blanket_number),
    CONSTRAINT fk_blanket_orders_currency_code FOREIGN KEY (currency_code) REFERENCES northwind.currencies (code) ON DELETE RESTRICT,
    CONSTRAINT fk_blanket_orders_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT
);
