-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.brands of database main (PostgreSQL 16).

CREATE TABLE northwind.brands (
    id uuid NOT NULL,
    name varchar(120) NOT NULL,
    description text NULL,
    logo_url varchar(400) NULL,
    website varchar(200) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    manufacturer_id uuid NULL,
    CONSTRAINT pk_brands PRIMARY KEY (id),
    CONSTRAINT uq_brands_name UNIQUE (name),
    CONSTRAINT fk_brands_manufacturer_id FOREIGN KEY (manufacturer_id) REFERENCES northwind.manufacturers (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.brands IS 'A brand products are marketed under, which may differ from the manufacturer.';
COMMENT ON COLUMN northwind.brands.id IS 'Surrogate key of the brand.';
COMMENT ON COLUMN northwind.brands.name IS 'Brand name.';
COMMENT ON COLUMN northwind.brands.description IS 'Brand story.';
COMMENT ON COLUMN northwind.brands.logo_url IS 'Logo image URL.';
COMMENT ON COLUMN northwind.brands.website IS 'Brand website.';
COMMENT ON COLUMN northwind.brands.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.brands.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.brands.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.brands.updated_by IS 'User name of the last editor.';
