-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.card_payments of database main (PostgreSQL 16).
-- Maps entity CardPayment.

CREATE TABLE northwind.card_payments (
    id uuid NOT NULL,
    card_brand varchar(4) NOT NULL,
    last4 varchar(4) NOT NULL,
    expiry_month smallint NULL,
    expiry_year smallint NULL,
    authorization_code varchar(20) NULL,
    processor_reference varchar(64) NULL,
    stored_payment_method_id uuid NULL,
    CONSTRAINT pk_card_payments PRIMARY KEY (id),
    CONSTRAINT fk_card_payments_id FOREIGN KEY (id) REFERENCES northwind.payments (id) ON DELETE CASCADE,
    CONSTRAINT fk_card_payments_stored_payment_method_id FOREIGN KEY (stored_payment_method_id) REFERENCES northwind.stored_payment_methods (id) ON DELETE SET NULL
);
CREATE INDEX ix_card_payments_processor_reference ON northwind.card_payments (processor_reference);
