-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.carrier_services of database main (PostgreSQL 16).
-- Maps entity CarrierService.

CREATE TABLE northwind.carrier_services (
    id uuid NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    service_level varchar(20) NOT NULL,
    transit_days smallint NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    carrier_id uuid NOT NULL,
    CONSTRAINT pk_carrier_services PRIMARY KEY (id),
    CONSTRAINT fk_carrier_services_carrier_id FOREIGN KEY (carrier_id) REFERENCES northwind.parties (id) ON DELETE CASCADE
);
