-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.carts of database main (PostgreSQL 16).
-- Maps entity Cart.

CREATE TABLE northwind.carts (
    id uuid NOT NULL,
    cart_token varchar(64) NOT NULL,
    last_activity_at timestamptz(6) NOT NULL,
    is_abandoned boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    converted_order_id uuid NULL,
    user_account_id uuid NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (id),
    CONSTRAINT uq_carts_cart_token UNIQUE (cart_token),
    CONSTRAINT fk_carts_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT,
    CONSTRAINT fk_carts_converted_order_id FOREIGN KEY (converted_order_id) REFERENCES northwind.sales_orders (id) ON DELETE SET NULL,
    CONSTRAINT fk_carts_user_account_id FOREIGN KEY (user_account_id) REFERENCES northwind.user_accounts (id) ON DELETE RESTRICT
);
COMMENT ON TABLE northwind.carts IS 'A customer portal shopping cart that becomes a sales order at checkout.';
COMMENT ON COLUMN northwind.carts.id IS 'Surrogate key of the cart.';
COMMENT ON COLUMN northwind.carts.cart_token IS 'Opaque token held by the browser.';
COMMENT ON COLUMN northwind.carts.last_activity_at IS 'Last change to the cart.';
COMMENT ON COLUMN northwind.carts.is_abandoned IS 'Flagged by the abandoned-cart job.';
COMMENT ON COLUMN northwind.carts.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.carts.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.carts.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.carts.updated_by IS 'User name of the last editor.';
