-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.channel_listings of database main (PostgreSQL 16).
-- Maps entity ChannelListing.

CREATE TABLE northwind.channel_listings (
    id uuid NOT NULL,
    external_id varchar(64) NULL,
    listed_price_amount numeric(19,4) NULL,
    listed_price_currency varchar(3) NULL,
    is_published boolean NOT NULL DEFAULT false,
    published_at timestamptz(6) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    product_id uuid NOT NULL,
    sales_channel_id uuid NOT NULL,
    CONSTRAINT pk_channel_listings PRIMARY KEY (id),
    CONSTRAINT fk_channel_listings_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE CASCADE,
    CONSTRAINT fk_channel_listings_sales_channel_id FOREIGN KEY (sales_channel_id) REFERENCES northwind.sales_channels (id) ON DELETE RESTRICT
);
