-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.collection_cases of database main (PostgreSQL 16).

CREATE TABLE northwind.collection_cases (
    id uuid NOT NULL,
    case_number varchar(20) NOT NULL,
    opened_on date NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'open',
    total_overdue_amount numeric(19,4) NOT NULL,
    total_overdue_currency varchar(3) NOT NULL,
    agency_name varchar(120) NULL,
    closed_on date NULL,
    notes text NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    assigned_to_id uuid NULL,
    CONSTRAINT pk_collection_cases PRIMARY KEY (id),
    CONSTRAINT uq_collection_cases_case_number UNIQUE (case_number),
    CONSTRAINT fk_collection_cases_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT,
    CONSTRAINT fk_collection_cases_assigned_to_id FOREIGN KEY (assigned_to_id) REFERENCES northwind.employees (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.collection_cases IS 'A collection effort on a customer''s overdue balance, possibly handed to an agency.';
COMMENT ON COLUMN northwind.collection_cases.id IS 'Surrogate key of the collection case.';
COMMENT ON COLUMN northwind.collection_cases.case_number IS 'Case number.';
COMMENT ON COLUMN northwind.collection_cases.opened_on IS 'Date opened.';
COMMENT ON COLUMN northwind.collection_cases.status IS 'open, promise-to-pay, agency or closed.';
COMMENT ON COLUMN northwind.collection_cases.total_overdue_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.collection_cases.total_overdue_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.collection_cases.agency_name IS 'Collection agency, when outsourced.';
COMMENT ON COLUMN northwind.collection_cases.closed_on IS 'Date closed.';
COMMENT ON COLUMN northwind.collection_cases.notes IS 'Case notes.';
COMMENT ON COLUMN northwind.collection_cases.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.collection_cases.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.collection_cases.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.collection_cases.updated_by IS 'User name of the last editor.';
