-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.communication_preferences of database main (PostgreSQL 16).

CREATE TABLE northwind.communication_preferences (
    id uuid NOT NULL,
    channel varchar(20) NOT NULL,
    topic varchar(40) NOT NULL,
    opted_in boolean NOT NULL,
    changed_at timestamptz(6) NOT NULL,
    source varchar(40) NULL,
    contact_id uuid NOT NULL,
    CONSTRAINT pk_communication_preferences PRIMARY KEY (id),
    CONSTRAINT fk_communication_preferences_contact_id FOREIGN KEY (contact_id) REFERENCES northwind.contacts (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.communication_preferences IS 'A contact''s opt-in or opt-out for a channel and topic, kept for anti-spam compliance.';
COMMENT ON COLUMN northwind.communication_preferences.id IS 'Surrogate key of the communication preference.';
COMMENT ON COLUMN northwind.communication_preferences.channel IS 'Channel, such as email or sms.';
COMMENT ON COLUMN northwind.communication_preferences.topic IS 'Topic, such as promotions or order-updates.';
COMMENT ON COLUMN northwind.communication_preferences.opted_in IS 'Whether the contact agreed to receive it.';
COMMENT ON COLUMN northwind.communication_preferences.changed_at IS 'When the preference was last set.';
COMMENT ON COLUMN northwind.communication_preferences.source IS 'Where it was set, such as portal or phone.';
