-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.contacts of database main (PostgreSQL 16).
-- Maps entity Contact.

CREATE TABLE northwind.contacts (
    id uuid NOT NULL,
    name_given_name varchar(80) NOT NULL,
    name_family_name varchar(80) NOT NULL,
    name_title varchar(20) NULL,
    job_title varchar(100) NULL,
    email varchar(254) NULL,
    phone_number varchar(20) NULL,
    phone_extension varchar(10) NULL,
    additional_phones jsonb NULL,
    is_primary boolean NOT NULL DEFAULT false,
    is_billing_contact boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    deleted_at timestamptz(6) NULL,
    language_code varchar(5) NULL,
    party_id uuid NOT NULL,
    CONSTRAINT pk_contacts PRIMARY KEY (id),
    CONSTRAINT fk_contacts_language_code FOREIGN KEY (language_code) REFERENCES northwind.languages (code) ON DELETE SET NULL,
    CONSTRAINT fk_contacts_party_id FOREIGN KEY (party_id) REFERENCES northwind.parties (id) ON DELETE CASCADE
);
CREATE INDEX ix_contacts_email ON northwind.contacts (email);
