-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.coupons of database main (PostgreSQL 16).
-- Maps entity Coupon.

CREATE TABLE northwind.coupons (
    id uuid NOT NULL,
    code varchar(40) NOT NULL,
    max_uses integer NULL,
    used_count integer NOT NULL DEFAULT 0,
    expires_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NULL,
    promotion_id uuid NOT NULL,
    CONSTRAINT pk_coupons PRIMARY KEY (id),
    CONSTRAINT uq_coupons_code UNIQUE (code),
    CONSTRAINT fk_coupons_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE SET NULL,
    CONSTRAINT fk_coupons_promotion_id FOREIGN KEY (promotion_id) REFERENCES northwind.promotions (id) ON DELETE CASCADE
);
