-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.credit_profiles of database main (PostgreSQL 16).
-- Maps entity CreditProfile.

CREATE TABLE northwind.credit_profiles (
    id uuid NOT NULL,
    credit_limit_amount numeric(19,4) NOT NULL,
    credit_limit_currency varchar(3) NOT NULL,
    risk_rating varchar(2) NOT NULL,
    external_score integer NULL,
    last_reviewed_on date NULL,
    review_notes text NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    CONSTRAINT pk_credit_profiles PRIMARY KEY (id),
    CONSTRAINT uq_credit_profiles_customer_id UNIQUE (customer_id),
    CONSTRAINT fk_credit_profiles_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE CASCADE
);
