-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.credit_profiles of database main (PostgreSQL 16).
-- Maps entity CreditProfile.

CREATE TABLE northwind.credit_profiles (
    id uuid NOT NULL,
    credit_limit_amount numeric(19,4) NOT NULL,
    credit_limit_currency varchar(3) NOT NULL,
    risk_rating varchar(2) NOT NULL,
    external_score integer NULL,
    last_reviewed_on date NULL,
    review_notes text NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    CONSTRAINT pk_credit_profiles PRIMARY KEY (id),
    CONSTRAINT uq_credit_profiles_customer_id UNIQUE (customer_id),
    CONSTRAINT fk_credit_profiles_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.credit_profiles IS 'The credit standing of a customer, reviewed by the credit department before limits change.';
COMMENT ON COLUMN northwind.credit_profiles.id IS 'Surrogate key of the credit profile.';
COMMENT ON COLUMN northwind.credit_profiles.credit_limit_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.credit_profiles.credit_limit_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.credit_profiles.risk_rating IS 'Internal rating from A1 (best) to D (worst).';
COMMENT ON COLUMN northwind.credit_profiles.external_score IS 'Score from the credit bureau.';
COMMENT ON COLUMN northwind.credit_profiles.last_reviewed_on IS 'Date of the last credit review.';
COMMENT ON COLUMN northwind.credit_profiles.review_notes IS 'Reviewer''s notes.';
COMMENT ON COLUMN northwind.credit_profiles.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.credit_profiles.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.credit_profiles.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.credit_profiles.updated_by IS 'User name of the last editor.';
