-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.customer_groups of database main (PostgreSQL 16).
-- Maps entity CustomerGroup.

CREATE TABLE northwind.customer_groups (
    id uuid NOT NULL,
    name varchar(80) NOT NULL,
    description varchar(300) NULL,
    default_discount numeric(5,2) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_customer_groups PRIMARY KEY (id),
    CONSTRAINT uq_customer_groups_name UNIQUE (name)
);
