-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.departments of database main (PostgreSQL 16).
-- Maps entity Department.

CREATE TABLE northwind.departments (
    id uuid NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    cost_center_id uuid NULL,
    parent_id uuid NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id),
    CONSTRAINT uq_departments_code UNIQUE (code),
    CONSTRAINT fk_departments_cost_center_id FOREIGN KEY (cost_center_id) REFERENCES northwind.cost_centers (id) ON DELETE SET NULL,
    CONSTRAINT fk_departments_parent_id FOREIGN KEY (parent_id) REFERENCES northwind.departments (id) ON DELETE SET NULL
);
