-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.discount_rules of database main (PostgreSQL 16).
-- Maps entity DiscountRule.

CREATE TABLE northwind.discount_rules (
    id uuid NOT NULL,
    name varchar(120) NOT NULL,
    discount_type varchar(4) NOT NULL,
    value numeric(12,4) NOT NULL,
    priority smallint NOT NULL DEFAULT 100,
    is_stackable boolean NOT NULL DEFAULT false,
    validity_starts_on date NULL,
    validity_ends_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    product_category_id uuid NULL,
    customer_group_id uuid NULL,
    CONSTRAINT pk_discount_rules PRIMARY KEY (id),
    CONSTRAINT fk_discount_rules_product_category_id FOREIGN KEY (product_category_id) REFERENCES northwind.product_categories (id) ON DELETE SET NULL,
    CONSTRAINT fk_discount_rules_customer_group_id FOREIGN KEY (customer_group_id) REFERENCES northwind.customer_groups (id) ON DELETE SET NULL
);
