-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.dock_doors of database main (PostgreSQL 16).
-- Maps entity DockDoor.

CREATE TABLE northwind.dock_doors (
    id uuid NOT NULL,
    door_number varchar(10) NOT NULL,
    door_type varchar(20) NOT NULL,
    has_leveler boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    warehouse_id uuid NOT NULL,
    CONSTRAINT pk_dock_doors PRIMARY KEY (id),
    CONSTRAINT fk_dock_doors_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE CASCADE
);
