-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.dunning_notices of database main (PostgreSQL 16).
-- Maps entity DunningNotice.

CREATE TABLE northwind.dunning_notices (
    id uuid NOT NULL,
    level smallint NOT NULL,
    issued_on date NOT NULL,
    amount_overdue_amount numeric(19,4) NOT NULL,
    amount_overdue_currency varchar(3) NOT NULL,
    fee_amount_amount numeric(19,4) NULL,
    fee_amount_currency varchar(3) NULL,
    sent_via varchar(20) NULL,
    collection_case_id uuid NULL,
    invoice_id uuid NOT NULL,
    CONSTRAINT pk_dunning_notices PRIMARY KEY (id),
    CONSTRAINT fk_dunning_notices_collection_case_id FOREIGN KEY (collection_case_id) REFERENCES northwind.collection_cases (id) ON DELETE SET NULL,
    CONSTRAINT fk_dunning_notices_invoice_id FOREIGN KEY (invoice_id) REFERENCES northwind.invoices (id) ON DELETE CASCADE
);
