-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.employees of database main (PostgreSQL 16).
-- Maps entity Employee.

CREATE TABLE northwind.employees (
    id uuid NOT NULL,
    employee_number varchar(12) NOT NULL,
    name_given_name varchar(80) NOT NULL,
    name_family_name varchar(80) NOT NULL,
    name_title varchar(20) NULL,
    work_email varchar(254) NOT NULL,
    work_phone_number varchar(20) NULL,
    work_phone_extension varchar(10) NULL,
    job_title varchar(100) NOT NULL,
    hired_on date NOT NULL,
    terminated_on date NULL,
    is_sales_rep boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    deleted_at timestamptz(6) NULL,
    department_id uuid NOT NULL,
    home_warehouse_id uuid NULL,
    manager_id uuid NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT uq_employees_work_email UNIQUE (work_email),
    CONSTRAINT uq_employees_employee_number UNIQUE (employee_number),
    CONSTRAINT fk_employees_department_id FOREIGN KEY (department_id) REFERENCES northwind.departments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_employees_home_warehouse_id FOREIGN KEY (home_warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE SET NULL,
    CONSTRAINT fk_employees_manager_id FOREIGN KEY (manager_id) REFERENCES northwind.employees (id) ON DELETE SET NULL
);
