-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.exchange_rates of database main (PostgreSQL 16).
-- Maps entity ExchangeRate.

CREATE TABLE northwind.exchange_rates (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rate numeric(18,8) NOT NULL,
    effective_on date NOT NULL,
    rate_type varchar(10) NOT NULL DEFAULT 'spot',
    source varchar(40) NULL,
    from_currency_code varchar(3) NOT NULL,
    to_currency_code varchar(3) NOT NULL,
    CONSTRAINT pk_exchange_rates PRIMARY KEY (id),
    CONSTRAINT fk_exchange_rates_from_currency_code FOREIGN KEY (from_currency_code) REFERENCES northwind.currencies (code) ON DELETE RESTRICT,
    CONSTRAINT fk_exchange_rates_to_currency_code FOREIGN KEY (to_currency_code) REFERENCES northwind.currencies (code) ON DELETE RESTRICT
);
CREATE INDEX ix_exchange_rates_effective_on ON northwind.exchange_rates (effective_on);
COMMENT ON TABLE northwind.exchange_rates IS 'A currency conversion rate on a date, loaded daily from the central bank feed.';
COMMENT ON COLUMN northwind.exchange_rates.id IS 'Surrogate key of the exchange rate.';
COMMENT ON COLUMN northwind.exchange_rates.rate IS 'Units of the target currency per unit of the source currency.';
COMMENT ON COLUMN northwind.exchange_rates.effective_on IS 'Date the rate applies.';
COMMENT ON COLUMN northwind.exchange_rates.rate_type IS 'spot, average or budget.';
COMMENT ON COLUMN northwind.exchange_rates.source IS 'Feed the rate came from.';
