-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.fiscal_periods of database main (PostgreSQL 16).
-- Maps entity FiscalPeriod.

CREATE TABLE northwind.fiscal_periods (
    id uuid NOT NULL,
    name varchar(20) NOT NULL,
    fiscal_year smallint NOT NULL,
    period_number smallint NOT NULL,
    period_starts_on date NOT NULL,
    period_ends_on date NULL,
    is_closed boolean NOT NULL DEFAULT false,
    closed_at timestamptz(6) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_fiscal_periods PRIMARY KEY (id),
    CONSTRAINT uq_fiscal_periods_name UNIQUE (name)
);
