-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.fiscal_periods of database main (PostgreSQL 16).
-- Maps entity FiscalPeriod.

CREATE TABLE northwind.fiscal_periods (
    id uuid NOT NULL,
    name varchar(20) NOT NULL,
    fiscal_year smallint NOT NULL,
    period_number smallint NOT NULL,
    period_starts_on date NOT NULL,
    period_ends_on date NULL,
    is_closed boolean NOT NULL DEFAULT false,
    closed_at timestamptz(6) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_fiscal_periods PRIMARY KEY (id),
    CONSTRAINT uq_fiscal_periods_name UNIQUE (name)
);
COMMENT ON TABLE northwind.fiscal_periods IS 'A monthly accounting period of a fiscal year.';
COMMENT ON COLUMN northwind.fiscal_periods.id IS 'Surrogate key of the fiscal period.';
COMMENT ON COLUMN northwind.fiscal_periods.name IS 'Period name, such as FY2026-09.';
COMMENT ON COLUMN northwind.fiscal_periods.fiscal_year IS 'Fiscal year.';
COMMENT ON COLUMN northwind.fiscal_periods.period_number IS 'Period within the year; 13 is the adjustment period.';
COMMENT ON COLUMN northwind.fiscal_periods.period_starts_on IS 'First day of the range.';
COMMENT ON COLUMN northwind.fiscal_periods.period_ends_on IS 'Last day of the range; null when open-ended.';
COMMENT ON COLUMN northwind.fiscal_periods.is_closed IS 'Whether posting is closed.';
COMMENT ON COLUMN northwind.fiscal_periods.closed_at IS 'When it was closed.';
COMMENT ON COLUMN northwind.fiscal_periods.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.fiscal_periods.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.fiscal_periods.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.fiscal_periods.updated_by IS 'User name of the last editor.';
