-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.goods_receipts of database main (PostgreSQL 16).
-- Maps entity GoodsReceipt.

CREATE TABLE northwind.goods_receipts (
    id uuid NOT NULL,
    receipt_number varchar(20) NOT NULL,
    received_at timestamptz(6) NOT NULL,
    delivery_note varchar(40) NULL,
    notes varchar(500) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    purchase_order_id uuid NULL,
    advance_ship_notice_id uuid NULL,
    warehouse_id uuid NOT NULL,
    received_by_id uuid NULL,
    dock_door_id uuid NULL,
    CONSTRAINT pk_goods_receipts PRIMARY KEY (id),
    CONSTRAINT uq_goods_receipts_receipt_number UNIQUE (receipt_number),
    CONSTRAINT fk_goods_receipts_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES northwind.purchase_orders (id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipts_advance_ship_notice_id FOREIGN KEY (advance_ship_notice_id) REFERENCES northwind.advance_ship_notices (id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipts_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE RESTRICT,
    CONSTRAINT fk_goods_receipts_received_by_id FOREIGN KEY (received_by_id) REFERENCES northwind.employees (id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipts_dock_door_id FOREIGN KEY (dock_door_id) REFERENCES northwind.dock_doors (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.goods_receipts IS 'The receipt of goods at a warehouse dock, against a purchase order or an advance ship notice.';
COMMENT ON COLUMN northwind.goods_receipts.id IS 'Surrogate key of the goods receipt.';
COMMENT ON COLUMN northwind.goods_receipts.receipt_number IS 'Receipt number.';
COMMENT ON COLUMN northwind.goods_receipts.received_at IS 'When the goods were received.';
COMMENT ON COLUMN northwind.goods_receipts.delivery_note IS 'Supplier''s delivery note number.';
COMMENT ON COLUMN northwind.goods_receipts.notes IS 'Damage or discrepancies noted.';
COMMENT ON COLUMN northwind.goods_receipts.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.goods_receipts.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.goods_receipts.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.goods_receipts.updated_by IS 'User name of the last editor.';
