-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.goods_receipt_lines of database main (PostgreSQL 16).
-- Maps entity GoodsReceiptLine.

CREATE TABLE northwind.goods_receipt_lines (
    id uuid NOT NULL,
    quantity_received numeric(12,3) NOT NULL,
    quantity_rejected numeric(12,3) NOT NULL DEFAULT 0,
    rejection_reason varchar(200) NULL,
    goods_receipt_id uuid NOT NULL,
    lot_id uuid NULL,
    product_id uuid NOT NULL,
    bin_id uuid NULL,
    purchase_order_line_id uuid NULL,
    CONSTRAINT pk_goods_receipt_lines PRIMARY KEY (id),
    CONSTRAINT fk_goods_receipt_lines_goods_receipt_id FOREIGN KEY (goods_receipt_id) REFERENCES northwind.goods_receipts (id) ON DELETE CASCADE,
    CONSTRAINT fk_goods_receipt_lines_lot_id FOREIGN KEY (lot_id) REFERENCES northwind.stock_lots (id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipt_lines_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_goods_receipt_lines_bin_id FOREIGN KEY (bin_id) REFERENCES northwind.bin_locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipt_lines_purchase_order_line_id FOREIGN KEY (purchase_order_line_id) REFERENCES northwind.purchase_order_lines (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.goods_receipt_lines IS 'A product and quantity received, with rejects.';
COMMENT ON COLUMN northwind.goods_receipt_lines.id IS 'Surrogate key of the goods receipt line.';
COMMENT ON COLUMN northwind.goods_receipt_lines.quantity_received IS 'Quantity accepted.';
COMMENT ON COLUMN northwind.goods_receipt_lines.quantity_rejected IS 'Quantity refused.';
COMMENT ON COLUMN northwind.goods_receipt_lines.rejection_reason IS 'Why goods were refused.';
