-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.hazard_classes of database main (PostgreSQL 16).
-- Maps entity HazardClass.

CREATE TABLE northwind.hazard_classes (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    un_number varchar(6) NULL,
    packing_group varchar(3) NULL,
    requires_placard boolean NOT NULL DEFAULT false,
    code varchar(32) NOT NULL,
    name varchar(100) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_hazard_classes PRIMARY KEY (id),
    CONSTRAINT uq_hazard_classes_code UNIQUE (code)
);
