-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.hold_reasons of database main (PostgreSQL 16).
-- Maps entity HoldReason.

CREATE TABLE northwind.hold_reasons (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requires_credit_approval boolean NOT NULL DEFAULT false,
    code varchar(32) NOT NULL,
    name varchar(100) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_hold_reasons PRIMARY KEY (id),
    CONSTRAINT uq_hold_reasons_code UNIQUE (code)
);
COMMENT ON TABLE northwind.hold_reasons IS 'A reason for holding an order, such as Credit limit exceeded or Price below cost.';
COMMENT ON COLUMN northwind.hold_reasons.id IS 'Surrogate key of the hold reason.';
COMMENT ON COLUMN northwind.hold_reasons.requires_credit_approval IS 'Whether only the credit department can release it.';
COMMENT ON COLUMN northwind.hold_reasons.code IS 'Short stable code used in integrations and imports.';
COMMENT ON COLUMN northwind.hold_reasons.name IS 'Display name shown in pick lists.';
COMMENT ON COLUMN northwind.hold_reasons.sort_order IS 'Position in pick lists.';
COMMENT ON COLUMN northwind.hold_reasons.is_active IS 'Whether the value can be chosen for new records.';
