-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.integration_outbox of database main (PostgreSQL 16).

CREATE TABLE northwind.integration_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aggregate_type varchar(100) NOT NULL,
    aggregate_id varchar(64) NOT NULL,
    event_type varchar(100) NOT NULL,
    payload jsonb NOT NULL,
    occurred_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    relayed_at timestamptz(6) NULL,
    attempts integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_integration_outbox PRIMARY KEY (id)
);
CREATE INDEX ix_integration_outbox_pending ON northwind.integration_outbox (occurred_at) WHERE relayed_at IS NULL;
COMMENT ON TABLE northwind.integration_outbox IS 'Written by the application, drained by the outbox relay.';
COMMENT ON COLUMN northwind.integration_outbox.id IS 'Relay order.';
COMMENT ON COLUMN northwind.integration_outbox.aggregate_type IS 'Entity name of the aggregate that changed.';
COMMENT ON COLUMN northwind.integration_outbox.aggregate_id IS 'Key of the aggregate that changed.';
COMMENT ON COLUMN northwind.integration_outbox.event_type IS 'Event name, such as SalesOrderSubmitted.';
COMMENT ON COLUMN northwind.integration_outbox.payload IS 'Event body.';
COMMENT ON COLUMN northwind.integration_outbox.occurred_at IS 'When the change was committed.';
COMMENT ON COLUMN northwind.integration_outbox.relayed_at IS 'When the relay published the event; null while pending.';
COMMENT ON COLUMN northwind.integration_outbox.attempts IS 'Publish attempts so far.';
