-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.invoices of database main (PostgreSQL 16).
-- Maps entity Invoice.

CREATE TABLE northwind.invoices (
    id uuid NOT NULL,
    invoice_number varchar(20) NOT NULL,
    invoice_date date NOT NULL,
    due_date date NOT NULL,
    status varchar(8) NOT NULL DEFAULT 'DRAFT',
    billing_address_line1 varchar(120) NOT NULL,
    billing_address_line2 varchar(120) NULL,
    billing_address_city varchar(80) NOT NULL,
    billing_address_region varchar(80) NULL,
    billing_address_postal_code varchar(20) NULL,
    billing_address_country_code varchar(2) NOT NULL,
    subtotal_amount numeric(19,4) NOT NULL,
    subtotal_currency varchar(3) NOT NULL,
    tax_total_amount numeric(19,4) NOT NULL,
    tax_total_currency varchar(3) NOT NULL,
    grand_total_amount numeric(19,4) NOT NULL,
    grand_total_currency varchar(3) NOT NULL,
    amount_paid_amount numeric(19,4) NOT NULL,
    amount_paid_currency varchar(3) NOT NULL,
    balance_due_amount numeric(19,4) NOT NULL,
    balance_due_currency varchar(3) NOT NULL,
    sent_at timestamptz(6) NULL,
    notes text NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    sales_order_id uuid NULL,
    billing_account_id uuid NULL,
    currency_code varchar(3) NOT NULL,
    payment_term_id integer NULL,
    journal_entry_id bigint NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id),
    CONSTRAINT uq_invoices_invoice_number UNIQUE (invoice_number),
    CONSTRAINT fk_invoices_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoices_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES northwind.sales_orders (id) ON DELETE SET NULL,
    CONSTRAINT fk_invoices_billing_account_id FOREIGN KEY (billing_account_id) REFERENCES northwind.billing_accounts (id) ON DELETE SET NULL,
    CONSTRAINT fk_invoices_currency_code FOREIGN KEY (currency_code) REFERENCES northwind.currencies (code) ON DELETE RESTRICT,
    CONSTRAINT fk_invoices_payment_term_id FOREIGN KEY (payment_term_id) REFERENCES northwind.payment_terms (id) ON DELETE SET NULL,
    CONSTRAINT fk_invoices_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES northwind.journal_entries (id) ON DELETE SET NULL,
    CONSTRAINT ck_invoices_due_after_invoice_date CHECK (due_date >= invoice_date)
);
CREATE INDEX ix_invoices_open_by_due_date ON northwind.invoices (due_date) WHERE status <> 'PAID';
CREATE INDEX ix_invoices_invoice_date ON northwind.invoices (invoice_date);
COMMENT ON TABLE northwind.invoices IS 'The due date cannot precede the invoice date; open invoices are listed by due date.';
COMMENT ON COLUMN northwind.invoices.id IS 'Surrogate key of the invoice.';
COMMENT ON COLUMN northwind.invoices.invoice_number IS 'Invoice number.';
COMMENT ON COLUMN northwind.invoices.invoice_date IS 'Invoice date.';
COMMENT ON COLUMN northwind.invoices.due_date IS 'Payment due date.';
COMMENT ON COLUMN northwind.invoices.status IS 'Lifecycle state.';
COMMENT ON COLUMN northwind.invoices.billing_address_line1 IS 'Street and number, or PO box.';
COMMENT ON COLUMN northwind.invoices.billing_address_line2 IS 'Suite, floor or building.';
COMMENT ON COLUMN northwind.invoices.billing_address_city IS 'City or locality.';
COMMENT ON COLUMN northwind.invoices.billing_address_region IS 'State, province or county.';
COMMENT ON COLUMN northwind.invoices.billing_address_postal_code IS 'Postal or ZIP code.';
COMMENT ON COLUMN northwind.invoices.billing_address_country_code IS 'ISO country code.';
COMMENT ON COLUMN northwind.invoices.subtotal_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.invoices.subtotal_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.invoices.tax_total_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.invoices.tax_total_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.invoices.grand_total_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.invoices.grand_total_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.invoices.amount_paid_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.invoices.amount_paid_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.invoices.balance_due_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.invoices.balance_due_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.invoices.sent_at IS 'When it was delivered to the customer.';
COMMENT ON COLUMN northwind.invoices.notes IS 'Remarks printed on the invoice.';
COMMENT ON COLUMN northwind.invoices.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.invoices.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.invoices.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.invoices.updated_by IS 'User name of the last editor.';
