-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.invoice_lines of database main (PostgreSQL 16).

CREATE TABLE northwind.invoice_lines (
    id char(26) NOT NULL,
    line_number integer NOT NULL,
    description varchar(300) NOT NULL,
    quantity numeric(12,3) NOT NULL,
    unit_price_amount numeric(19,4) NOT NULL,
    unit_price_currency varchar(3) NOT NULL,
    discount numeric(5,2) NULL,
    tax_rate numeric(5,2) NULL,
    line_total_amount numeric(19,4) NOT NULL,
    line_total_currency varchar(3) NOT NULL,
    invoice_id uuid NOT NULL,
    sales_order_line_id char(26) NULL,
    product_id uuid NULL,
    shipment_line_id uuid NULL,
    revenue_account_id uuid NULL,
    CONSTRAINT pk_invoice_lines PRIMARY KEY (id),
    CONSTRAINT fk_invoice_lines_invoice_id FOREIGN KEY (invoice_id) REFERENCES northwind.invoices (id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_lines_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES northwind.sales_order_lines (id) ON DELETE SET NULL,
    CONSTRAINT fk_invoice_lines_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE SET NULL,
    CONSTRAINT fk_invoice_lines_shipment_line_id FOREIGN KEY (shipment_line_id) REFERENCES northwind.shipment_lines (id) ON DELETE SET NULL,
    CONSTRAINT fk_invoice_lines_revenue_account_id FOREIGN KEY (revenue_account_id) REFERENCES northwind.ledger_accounts (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.invoice_lines IS 'A line of an invoice - a shipped product or a charge.';
COMMENT ON COLUMN northwind.invoice_lines.id IS 'Surrogate key of the invoice line.';
COMMENT ON COLUMN northwind.invoice_lines.line_number IS 'Line number.';
COMMENT ON COLUMN northwind.invoice_lines.description IS 'Line text.';
COMMENT ON COLUMN northwind.invoice_lines.quantity IS 'Quantity invoiced.';
COMMENT ON COLUMN northwind.invoice_lines.unit_price_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.invoice_lines.unit_price_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.invoice_lines.discount IS 'Discount.';
COMMENT ON COLUMN northwind.invoice_lines.tax_rate IS 'Tax rate.';
COMMENT ON COLUMN northwind.invoice_lines.line_total_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.invoice_lines.line_total_currency IS 'The ISO 4217 currency of the amount.';
