-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.journal_lines of database main (PostgreSQL 16).
-- Maps entity JournalLine.

CREATE TABLE northwind.journal_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    debit_amount numeric(19,4) NULL,
    debit_currency varchar(3) NULL,
    credit_amount numeric(19,4) NULL,
    credit_currency varchar(3) NULL,
    memo varchar(200) NULL,
    journal_entry_id bigint NOT NULL,
    cost_center_id uuid NULL,
    ledger_account_id uuid NOT NULL,
    CONSTRAINT pk_journal_lines PRIMARY KEY (id),
    CONSTRAINT fk_journal_lines_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES northwind.journal_entries (id) ON DELETE CASCADE,
    CONSTRAINT fk_journal_lines_cost_center_id FOREIGN KEY (cost_center_id) REFERENCES northwind.cost_centers (id) ON DELETE SET NULL,
    CONSTRAINT fk_journal_lines_ledger_account_id FOREIGN KEY (ledger_account_id) REFERENCES northwind.ledger_accounts (id) ON DELETE RESTRICT
);
