-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.journal_lines of database main (PostgreSQL 16).
-- Maps entity JournalLine.

CREATE TABLE northwind.journal_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    debit_amount numeric(19,4) NULL,
    debit_currency varchar(3) NULL,
    credit_amount numeric(19,4) NULL,
    credit_currency varchar(3) NULL,
    memo varchar(200) NULL,
    journal_entry_id bigint NOT NULL,
    cost_center_id uuid NULL,
    ledger_account_id uuid NOT NULL,
    CONSTRAINT pk_journal_lines PRIMARY KEY (id),
    CONSTRAINT fk_journal_lines_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES northwind.journal_entries (id) ON DELETE CASCADE,
    CONSTRAINT fk_journal_lines_cost_center_id FOREIGN KEY (cost_center_id) REFERENCES northwind.cost_centers (id) ON DELETE SET NULL,
    CONSTRAINT fk_journal_lines_ledger_account_id FOREIGN KEY (ledger_account_id) REFERENCES northwind.ledger_accounts (id) ON DELETE RESTRICT
);
COMMENT ON TABLE northwind.journal_lines IS 'A debit or credit to one ledger account within a journal entry.';
COMMENT ON COLUMN northwind.journal_lines.id IS 'Surrogate key of the journal line.';
COMMENT ON COLUMN northwind.journal_lines.debit_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.journal_lines.debit_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.journal_lines.credit_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.journal_lines.credit_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.journal_lines.memo IS 'Line memo.';
