-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.leads of database main (PostgreSQL 16).
-- Maps entity Lead.

CREATE TABLE northwind.leads (
    id uuid NOT NULL,
    company_name varchar(200) NOT NULL,
    contact_name_given_name varchar(80) NULL,
    contact_name_family_name varchar(80) NULL,
    contact_name_title varchar(20) NULL,
    email varchar(254) NULL,
    phone_number varchar(20) NULL,
    phone_extension varchar(10) NULL,
    status varchar(3) NOT NULL DEFAULT 'NEW',
    estimated_annual_value_amount numeric(19,4) NULL,
    estimated_annual_value_currency varchar(3) NULL,
    notes text NULL,
    converted_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    deleted_at timestamptz(6) NULL,
    converted_customer_id uuid NULL,
    owner_id uuid NULL,
    source_id integer NULL,
    industry_id integer NULL,
    CONSTRAINT pk_leads PRIMARY KEY (id),
    CONSTRAINT fk_leads_converted_customer_id FOREIGN KEY (converted_customer_id) REFERENCES northwind.parties (id) ON DELETE SET NULL,
    CONSTRAINT fk_leads_owner_id FOREIGN KEY (owner_id) REFERENCES northwind.employees (id) ON DELETE SET NULL,
    CONSTRAINT fk_leads_source_id FOREIGN KEY (source_id) REFERENCES northwind.lead_sources (id) ON DELETE SET NULL,
    CONSTRAINT fk_leads_industry_id FOREIGN KEY (industry_id) REFERENCES northwind.industries (id) ON DELETE SET NULL
);
CREATE INDEX ix_leads_email ON northwind.leads (email);
