-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.manufacturers of database main (PostgreSQL 16).
-- Maps entity Manufacturer.

CREATE TABLE northwind.manufacturers (
    id uuid NOT NULL,
    name varchar(200) NOT NULL,
    website varchar(200) NULL,
    support_email varchar(254) NULL,
    support_phone_number varchar(20) NULL,
    support_phone_extension varchar(10) NULL,
    country_code varchar(2) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_manufacturers PRIMARY KEY (id),
    CONSTRAINT uq_manufacturers_name UNIQUE (name)
);
