-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.opportunities of database main (PostgreSQL 16).
-- Maps entity Opportunity.

CREATE TABLE northwind.opportunities (
    id uuid NOT NULL,
    name varchar(200) NOT NULL,
    amount_amount numeric(19,4) NOT NULL,
    amount_currency varchar(3) NOT NULL,
    probability numeric(5,2) NULL,
    expected_close_on date NOT NULL,
    closed_on date NULL,
    loss_reason varchar(300) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    stage_id integer NOT NULL,
    owner_id uuid NOT NULL,
    CONSTRAINT pk_opportunities PRIMARY KEY (id),
    CONSTRAINT fk_opportunities_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT,
    CONSTRAINT fk_opportunities_stage_id FOREIGN KEY (stage_id) REFERENCES northwind.opportunity_stages (id) ON DELETE RESTRICT,
    CONSTRAINT fk_opportunities_owner_id FOREIGN KEY (owner_id) REFERENCES northwind.employees (id) ON DELETE RESTRICT
);
CREATE INDEX ix_opportunities_expected_close_on ON northwind.opportunities (expected_close_on);
