-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.opportunity_stages of database main (PostgreSQL 16).
-- Maps entity OpportunityStage.

CREATE TABLE northwind.opportunity_stages (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    default_probability numeric(5,2) NOT NULL,
    is_closed boolean NOT NULL DEFAULT false,
    is_won boolean NOT NULL DEFAULT false,
    code varchar(32) NOT NULL,
    name varchar(100) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_opportunity_stages PRIMARY KEY (id),
    CONSTRAINT uq_opportunity_stages_code UNIQUE (code)
);
