-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.party_addresses of database main (PostgreSQL 16).
-- Maps entity PartyAddress.

CREATE TABLE northwind.party_addresses (
    id uuid NOT NULL,
    label varchar(80) NOT NULL,
    address_type varchar(3) NOT NULL,
    address_line1 varchar(120) NOT NULL,
    address_line2 varchar(120) NULL,
    address_city varchar(80) NOT NULL,
    address_region varchar(80) NULL,
    address_postal_code varchar(20) NULL,
    address_country_code varchar(2) NOT NULL,
    location_latitude numeric(9,6) NULL,
    location_longitude numeric(9,6) NULL,
    is_default boolean NOT NULL DEFAULT false,
    delivery_instructions varchar(500) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    party_id uuid NOT NULL,
    CONSTRAINT pk_party_addresses PRIMARY KEY (id),
    CONSTRAINT fk_party_addresses_party_id FOREIGN KEY (party_id) REFERENCES northwind.parties (id) ON DELETE CASCADE
);
