-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.parties_remit_to_addresses of database main (PostgreSQL 16).
-- Maps entity Party.

CREATE TABLE northwind.parties_remit_to_addresses (
    party_id uuid NOT NULL,
    position integer NOT NULL,
    line1 varchar(120) NOT NULL,
    line2 varchar(120) NULL,
    city varchar(80) NOT NULL,
    region varchar(80) NULL,
    postal_code varchar(20) NULL,
    country_code varchar(2) NOT NULL,
    CONSTRAINT pk_parties_remit_to_addresses PRIMARY KEY (party_id, position),
    CONSTRAINT fk_parties_remit_to_addresses_party_id FOREIGN KEY (party_id) REFERENCES northwind.parties (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.parties_remit_to_addresses IS 'Addresses where payments may be sent; kept in a child table.';
COMMENT ON COLUMN northwind.parties_remit_to_addresses.line1 IS 'Street and number, or PO box.';
COMMENT ON COLUMN northwind.parties_remit_to_addresses.line2 IS 'Suite, floor or building.';
COMMENT ON COLUMN northwind.parties_remit_to_addresses.city IS 'City or locality.';
COMMENT ON COLUMN northwind.parties_remit_to_addresses.region IS 'State, province or county.';
COMMENT ON COLUMN northwind.parties_remit_to_addresses.postal_code IS 'Postal or ZIP code.';
COMMENT ON COLUMN northwind.parties_remit_to_addresses.country_code IS 'ISO country code.';
