-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.party_notes of database main (PostgreSQL 16).
-- Maps entity PartyNote.

CREATE TABLE northwind.party_notes (
    id uuid NOT NULL,
    body text NOT NULL,
    is_pinned boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    party_id uuid NOT NULL,
    author_id uuid NULL,
    CONSTRAINT pk_party_notes PRIMARY KEY (id),
    CONSTRAINT fk_party_notes_party_id FOREIGN KEY (party_id) REFERENCES northwind.parties (id) ON DELETE CASCADE,
    CONSTRAINT fk_party_notes_author_id FOREIGN KEY (author_id) REFERENCES northwind.user_accounts (id) ON DELETE SET NULL
);
