-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.payment_invoice of database main (PostgreSQL 16).
-- Junction table.

CREATE TABLE northwind.payment_invoice (
    payments_id uuid NOT NULL,
    invoices_id uuid NOT NULL,
    allocated_amount_amount numeric(19,4) NOT NULL,
    allocated_amount_currency varchar(3) NOT NULL,
    allocated_at timestamptz(6) NOT NULL,
    discount_taken_amount numeric(19,4) NULL,
    discount_taken_currency varchar(3) NULL,
    CONSTRAINT pk_payment_invoice PRIMARY KEY (payments_id, invoices_id),
    CONSTRAINT fk_payment_invoice_payments_id FOREIGN KEY (payments_id) REFERENCES northwind.payments (id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_invoice_invoices_id FOREIGN KEY (invoices_id) REFERENCES northwind.invoices (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.payment_invoice IS 'How a payment is allocated to the invoices it pays; one payment can settle many invoices and one invoice can be paid in instalments.';
COMMENT ON COLUMN northwind.payment_invoice.allocated_amount_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.payment_invoice.allocated_amount_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.payment_invoice.allocated_at IS 'When the allocation was made.';
COMMENT ON COLUMN northwind.payment_invoice.discount_taken_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.payment_invoice.discount_taken_currency IS 'The ISO 4217 currency of the amount.';
