-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.permissions of database main (PostgreSQL 16).

CREATE TABLE northwind.permissions (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(80) NOT NULL,
    resource varchar(60) NOT NULL,
    action varchar(40) NOT NULL,
    description varchar(300) NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id),
    CONSTRAINT uq_permissions_code UNIQUE (code)
);
COMMENT ON TABLE northwind.permissions IS 'A single grantable right on a resource, such as sales-order:approve.';
COMMENT ON COLUMN northwind.permissions.id IS 'Surrogate key of the permission.';
COMMENT ON COLUMN northwind.permissions.code IS 'Resource and action, such as sales-order:approve.';
COMMENT ON COLUMN northwind.permissions.resource IS 'Protected resource.';
COMMENT ON COLUMN northwind.permissions.action IS 'Action on the resource.';
COMMENT ON COLUMN northwind.permissions.description IS 'What the permission allows.';
