-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.price_list_customer_group of database main (PostgreSQL 16).
-- Junction table of relation "price list serves customer group".

CREATE TABLE northwind.price_list_customer_group (
    price_lists_id uuid NOT NULL,
    customer_groups_id uuid NOT NULL,
    CONSTRAINT pk_price_list_customer_group PRIMARY KEY (price_lists_id, customer_groups_id),
    CONSTRAINT fk_price_list_customer_group_price_lists_id FOREIGN KEY (price_lists_id) REFERENCES northwind.price_lists (id) ON DELETE CASCADE,
    CONSTRAINT fk_price_list_customer_group_customer_groups_id FOREIGN KEY (customer_groups_id) REFERENCES northwind.customer_groups (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.price_list_customer_group IS 'Customer groups that buy from a price list.';
