-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.price_lists of database main (PostgreSQL 16).

CREATE TABLE northwind.price_lists (
    id uuid NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(120) NOT NULL,
    validity_starts_on date NOT NULL,
    validity_ends_on date NULL,
    is_default boolean NOT NULL DEFAULT false,
    prices_include_tax boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    currency_code varchar(3) NOT NULL,
    CONSTRAINT pk_price_lists PRIMARY KEY (id),
    CONSTRAINT uq_price_lists_code UNIQUE (code),
    CONSTRAINT fk_price_lists_currency_code FOREIGN KEY (currency_code) REFERENCES northwind.currencies (code) ON DELETE RESTRICT
);
COMMENT ON TABLE northwind.price_lists IS 'A list of prices in one currency, such as the US wholesale list or the Canada distributor list.';
COMMENT ON COLUMN northwind.price_lists.id IS 'Surrogate key of the price list.';
COMMENT ON COLUMN northwind.price_lists.code IS 'Price list code.';
COMMENT ON COLUMN northwind.price_lists.name IS 'Price list name.';
COMMENT ON COLUMN northwind.price_lists.validity_starts_on IS 'First day of the range.';
COMMENT ON COLUMN northwind.price_lists.validity_ends_on IS 'Last day of the range; null when open-ended.';
COMMENT ON COLUMN northwind.price_lists.is_default IS 'List used when a customer has no other list.';
COMMENT ON COLUMN northwind.price_lists.prices_include_tax IS 'Whether prices are tax-inclusive.';
COMMENT ON COLUMN northwind.price_lists.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.price_lists.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.price_lists.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.price_lists.updated_by IS 'User name of the last editor.';
