-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.price_list_entries of database main (PostgreSQL 16).
-- Maps entity PriceListEntry.

CREATE TABLE northwind.price_list_entries (
    id uuid NOT NULL,
    unit_price_amount numeric(19,4) NOT NULL,
    unit_price_currency varchar(3) NOT NULL,
    minimum_quantity numeric(12,3) NULL,
    validity_starts_on date NULL,
    validity_ends_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    price_list_id uuid NOT NULL,
    product_id uuid NOT NULL,
    variant_id uuid NULL,
    unit_code varchar(3) NULL,
    CONSTRAINT pk_price_list_entries PRIMARY KEY (id),
    CONSTRAINT fk_price_list_entries_price_list_id FOREIGN KEY (price_list_id) REFERENCES northwind.price_lists (id) ON DELETE CASCADE,
    CONSTRAINT fk_price_list_entries_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_price_list_entries_variant_id FOREIGN KEY (variant_id) REFERENCES northwind.product_variants (id) ON DELETE SET NULL,
    CONSTRAINT fk_price_list_entries_unit_code FOREIGN KEY (unit_code) REFERENCES northwind.units_of_measure (code) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.price_list_entries IS 'The price of a product or variant on a price list.';
COMMENT ON COLUMN northwind.price_list_entries.id IS 'Surrogate key of the price list entry.';
COMMENT ON COLUMN northwind.price_list_entries.unit_price_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.price_list_entries.unit_price_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.price_list_entries.minimum_quantity IS 'Smallest quantity the price applies to.';
COMMENT ON COLUMN northwind.price_list_entries.validity_starts_on IS 'First day of the range.';
COMMENT ON COLUMN northwind.price_list_entries.validity_ends_on IS 'Last day of the range; null when open-ended.';
COMMENT ON COLUMN northwind.price_list_entries.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.price_list_entries.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.price_list_entries.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.price_list_entries.updated_by IS 'User name of the last editor.';
