-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_statuses of database main (PostgreSQL 16).
-- Lookup table of an enum; its rows are in seed.sql.

CREATE TABLE northwind.product_statuses (
    id integer NOT NULL,
    code varchar(8) NOT NULL,
    name varchar(12) NOT NULL,
    CONSTRAINT pk_product_statuses PRIMARY KEY (id),
    CONSTRAINT uq_product_statuses_code UNIQUE (code)
);
