-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_collections of database main (PostgreSQL 16).
-- Maps entity ProductCollection.

CREATE TABLE northwind.product_collections (
    id uuid NOT NULL,
    name varchar(120) NOT NULL,
    description text NULL,
    is_featured boolean NOT NULL DEFAULT false,
    validity_starts_on date NULL,
    validity_ends_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_product_collections PRIMARY KEY (id),
    CONSTRAINT uq_product_collections_name UNIQUE (name)
);
