-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_documents of database main (PostgreSQL 16).
-- Maps entity ProductDocument.

CREATE TABLE northwind.product_documents (
    id char(26) NOT NULL,
    title varchar(200) NOT NULL,
    document_type varchar(40) NOT NULL,
    url varchar(400) NOT NULL,
    language_code varchar(5) NULL,
    revision varchar(10) NULL,
    published_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    product_id uuid NOT NULL,
    CONSTRAINT pk_product_documents PRIMARY KEY (id),
    CONSTRAINT fk_product_documents_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE CASCADE
);
