-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_substitutes of database main (PostgreSQL 16).

CREATE TABLE northwind.product_substitutes (
    id uuid NOT NULL,
    reason varchar(200) NULL,
    priority smallint NOT NULL DEFAULT 1,
    requires_approval boolean NOT NULL DEFAULT true,
    substitute_id uuid NOT NULL,
    product_id uuid NOT NULL,
    CONSTRAINT pk_product_substitutes PRIMARY KEY (id),
    CONSTRAINT fk_product_substitutes_substitute_id FOREIGN KEY (substitute_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_product_substitutes_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.product_substitutes IS 'A product that can replace another when it is out of stock, ranked by preference.';
COMMENT ON COLUMN northwind.product_substitutes.id IS 'Surrogate key of the product substitute.';
COMMENT ON COLUMN northwind.product_substitutes.reason IS 'Why the substitute fits.';
COMMENT ON COLUMN northwind.product_substitutes.priority IS 'Rank among substitutes; 1 is preferred.';
COMMENT ON COLUMN northwind.product_substitutes.requires_approval IS 'Whether the customer must approve the substitution.';
