-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_attributes of database main (PostgreSQL 16).
-- Maps entity ProductAttribute.

CREATE TABLE northwind.product_attributes (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(60) NOT NULL,
    name varchar(100) NOT NULL,
    data_type varchar(20) NOT NULL,
    unit varchar(10) NULL,
    is_filterable boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_product_attributes PRIMARY KEY (id),
    CONSTRAINT uq_product_attributes_code UNIQUE (code)
);
