-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_packagings of database main (PostgreSQL 16).

CREATE TABLE northwind.product_packagings (
    id uuid NOT NULL,
    packaging_level varchar(20) NOT NULL,
    units_per_package integer NOT NULL,
    dimensions_length numeric(10,3) NULL,
    dimensions_width numeric(10,3) NULL,
    dimensions_height numeric(10,3) NULL,
    dimensions_unit varchar(3) NULL,
    gross_weight_value numeric(12,3) NULL,
    gross_weight_unit varchar(3) NULL,
    gtin varchar(14) NULL,
    product_id uuid NOT NULL,
    unit_code varchar(3) NOT NULL,
    CONSTRAINT pk_product_packagings PRIMARY KEY (id),
    CONSTRAINT fk_product_packagings_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_packagings_unit_code FOREIGN KEY (unit_code) REFERENCES northwind.units_of_measure (code) ON DELETE RESTRICT
);
COMMENT ON TABLE northwind.product_packagings IS 'A packaging level of a product, such as a case of 12 or a pallet of 60 cases.';
COMMENT ON COLUMN northwind.product_packagings.id IS 'Surrogate key of the product packaging.';
COMMENT ON COLUMN northwind.product_packagings.packaging_level IS 'Packaging level - each, inner, case or pallet.';
COMMENT ON COLUMN northwind.product_packagings.units_per_package IS 'Base units in one package.';
COMMENT ON COLUMN northwind.product_packagings.dimensions_length IS 'Longest side.';
COMMENT ON COLUMN northwind.product_packagings.dimensions_width IS 'Second side.';
COMMENT ON COLUMN northwind.product_packagings.dimensions_height IS 'Vertical side.';
COMMENT ON COLUMN northwind.product_packagings.dimensions_unit IS 'Unit of the three measures.';
COMMENT ON COLUMN northwind.product_packagings.gross_weight_value IS 'The weight.';
COMMENT ON COLUMN northwind.product_packagings.gross_weight_unit IS 'Unit of the weight.';
COMMENT ON COLUMN northwind.product_packagings.gtin IS 'GTIN of the package.';
