-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_categories of database main (PostgreSQL 16).
-- Maps entity ProductCategory.

CREATE TABLE northwind.product_categories (
    id uuid NOT NULL,
    code varchar(40) NOT NULL,
    name varchar(120) NOT NULL,
    description text NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    parent_id uuid NULL,
    CONSTRAINT pk_product_categories PRIMARY KEY (id),
    CONSTRAINT uq_product_categories_code UNIQUE (code),
    CONSTRAINT fk_product_categories_parent_id FOREIGN KEY (parent_id) REFERENCES northwind.product_categories (id) ON DELETE SET NULL
);
