-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.products of database main (PostgreSQL 16).

CREATE TABLE northwind.products (
    id uuid NOT NULL,
    sku varchar(40) NOT NULL,
    name varchar(200) NOT NULL,
    short_description varchar(500) NULL,
    long_description text NULL,
    status varchar(8) NOT NULL DEFAULT 'DRAFT',
    is_serialized boolean NOT NULL DEFAULT false,
    is_lot_controlled boolean NOT NULL DEFAULT false,
    shelf_life_days smallint NULL,
    dimensions_length numeric(10,3) NULL,
    dimensions_width numeric(10,3) NULL,
    dimensions_height numeric(10,3) NULL,
    dimensions_unit varchar(3) NULL,
    weight_value numeric(12,3) NULL,
    weight_unit varchar(3) NULL,
    list_price_amount numeric(19,4) NULL,
    list_price_currency varchar(3) NULL,
    country_of_origin varchar(2) NULL,
    launched_on date NULL,
    discontinued_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    deleted_at timestamptz(6) NULL,
    preferred_supplier_id uuid NULL,
    hazard_class_id integer NULL,
    tariff_code_id uuid NULL,
    category_id uuid NOT NULL,
    manufacturer_id uuid NULL,
    sales_unit_code varchar(3) NULL,
    brand_id uuid NULL,
    base_unit_code varchar(3) NOT NULL,
    storage_condition_id integer NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_preferred_supplier_id FOREIGN KEY (preferred_supplier_id) REFERENCES northwind.parties (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_hazard_class_id FOREIGN KEY (hazard_class_id) REFERENCES northwind.hazard_classes (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_tariff_code_id FOREIGN KEY (tariff_code_id) REFERENCES northwind.tariff_codes (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_category_id FOREIGN KEY (category_id) REFERENCES northwind.product_categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_products_manufacturer_id FOREIGN KEY (manufacturer_id) REFERENCES northwind.manufacturers (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_sales_unit_code FOREIGN KEY (sales_unit_code) REFERENCES northwind.units_of_measure (code) ON DELETE SET NULL,
    CONSTRAINT fk_products_brand_id FOREIGN KEY (brand_id) REFERENCES northwind.brands (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_base_unit_code FOREIGN KEY (base_unit_code) REFERENCES northwind.units_of_measure (code) ON DELETE RESTRICT,
    CONSTRAINT fk_products_storage_condition_id FOREIGN KEY (storage_condition_id) REFERENCES northwind.storage_conditions (id) ON DELETE SET NULL,
    CONSTRAINT ck_products_discontinued_after_launch CHECK (discontinued_on IS NULL OR launched_on IS NULL OR discontinued_on >= launched_on)
);
CREATE INDEX ix_products_status_name ON northwind.products (status, name);
CREATE INDEX ix_products_name ON northwind.products (name);
COMMENT ON TABLE northwind.products IS 'Product search and integrity tuning.';
COMMENT ON COLUMN northwind.products.id IS 'Surrogate key of the product.';
COMMENT ON COLUMN northwind.products.sku IS 'Stock keeping unit of the base product.';
COMMENT ON COLUMN northwind.products.name IS 'Searched with a trigram index in production.';
COMMENT ON COLUMN northwind.products.short_description IS 'One-paragraph description for listings.';
COMMENT ON COLUMN northwind.products.long_description IS 'Full description in Markdown.';
COMMENT ON COLUMN northwind.products.status IS 'Lifecycle state.';
COMMENT ON COLUMN northwind.products.is_serialized IS 'Whether each unit carries a serial number.';
COMMENT ON COLUMN northwind.products.is_lot_controlled IS 'Whether stock is tracked by lot or batch.';
COMMENT ON COLUMN northwind.products.shelf_life_days IS 'Days from production to expiry, for perishables.';
COMMENT ON COLUMN northwind.products.dimensions_length IS 'Longest side.';
COMMENT ON COLUMN northwind.products.dimensions_width IS 'Second side.';
COMMENT ON COLUMN northwind.products.dimensions_height IS 'Vertical side.';
COMMENT ON COLUMN northwind.products.dimensions_unit IS 'Unit of the three measures.';
COMMENT ON COLUMN northwind.products.weight_value IS 'The weight.';
COMMENT ON COLUMN northwind.products.weight_unit IS 'Unit of the weight.';
COMMENT ON COLUMN northwind.products.list_price_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.products.list_price_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.products.country_of_origin IS 'Where the goods were produced, for customs.';
COMMENT ON COLUMN northwind.products.launched_on IS 'First sale date.';
COMMENT ON COLUMN northwind.products.discontinued_on IS 'Last sale date.';
COMMENT ON COLUMN northwind.products.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.products.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.products.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.products.updated_by IS 'User name of the last editor.';
COMMENT ON COLUMN northwind.products.deleted_at IS 'When the row was marked deleted; null while it is live.';
