-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_translations of database main (PostgreSQL 16).
-- Maps entity ProductTranslation.

CREATE TABLE northwind.product_translations (
    id uuid NOT NULL,
    name varchar(200) NOT NULL,
    short_description varchar(500) NULL,
    long_description text NULL,
    product_id uuid NOT NULL,
    language_code varchar(5) NOT NULL,
    CONSTRAINT pk_product_translations PRIMARY KEY (id),
    CONSTRAINT fk_product_translations_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_translations_language_code FOREIGN KEY (language_code) REFERENCES northwind.languages (code) ON DELETE RESTRICT
);
