-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_attribute_values of database main (PostgreSQL 16).
-- Maps entity ProductAttributeValue.

CREATE TABLE northwind.product_attribute_values (
    id char(26) NOT NULL,
    text_value varchar(500) NULL,
    numeric_value numeric(18,4) NULL,
    boolean_value boolean NULL,
    definition_id integer NOT NULL,
    option_id integer NULL,
    product_id uuid NOT NULL,
    CONSTRAINT pk_product_attribute_values PRIMARY KEY (id),
    CONSTRAINT fk_product_attribute_values_definition_id FOREIGN KEY (definition_id) REFERENCES northwind.product_attributes (id) ON DELETE RESTRICT,
    CONSTRAINT fk_product_attribute_values_option_id FOREIGN KEY (option_id) REFERENCES northwind.product_attribute_options (id) ON DELETE SET NULL,
    CONSTRAINT fk_product_attribute_values_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.product_attribute_values IS 'The value of one attribute for one product.';
COMMENT ON COLUMN northwind.product_attribute_values.id IS 'Surrogate key of the product attribute value.';
COMMENT ON COLUMN northwind.product_attribute_values.text_value IS 'Value of a text attribute.';
COMMENT ON COLUMN northwind.product_attribute_values.numeric_value IS 'Value of a number attribute.';
COMMENT ON COLUMN northwind.product_attribute_values.boolean_value IS 'Value of a boolean attribute.';
