-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.product_images of database main (PostgreSQL 16).
-- Maps entity ProductImage.

CREATE TABLE northwind.product_images (
    id char(26) NOT NULL,
    url varchar(400) NOT NULL,
    alt_text varchar(200) NULL,
    width_px integer NULL,
    height_px integer NULL,
    is_primary boolean NOT NULL DEFAULT false,
    product_id uuid NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id),
    CONSTRAINT fk_product_images_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE CASCADE
);
