-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.promotions of database main (PostgreSQL 16).
-- Maps entity Promotion.

CREATE TABLE northwind.promotions (
    id uuid NOT NULL,
    code varchar(30) NOT NULL,
    name varchar(150) NOT NULL,
    description text NULL,
    status varchar(6) NOT NULL DEFAULT 'DRAFT',
    validity_starts_on date NOT NULL,
    validity_ends_on date NULL,
    budget_amount numeric(19,4) NULL,
    budget_currency varchar(3) NULL,
    max_redemptions integer NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_promotions PRIMARY KEY (id),
    CONSTRAINT uq_promotions_code UNIQUE (code)
);
