-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.promotions of database main (PostgreSQL 16).

CREATE TABLE northwind.promotions (
    id uuid NOT NULL,
    code varchar(30) NOT NULL,
    name varchar(150) NOT NULL,
    description text NULL,
    status varchar(6) NOT NULL DEFAULT 'DRAFT',
    validity_starts_on date NOT NULL,
    validity_ends_on date NULL,
    budget_amount numeric(19,4) NULL,
    budget_currency varchar(3) NULL,
    max_redemptions integer NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_promotions PRIMARY KEY (id),
    CONSTRAINT uq_promotions_code UNIQUE (code)
);
COMMENT ON TABLE northwind.promotions IS 'A time-boxed marketing promotion with conditions and rewards, such as buy 10 cases get 1 free.';
COMMENT ON COLUMN northwind.promotions.id IS 'Surrogate key of the promotion.';
COMMENT ON COLUMN northwind.promotions.code IS 'Promotion code.';
COMMENT ON COLUMN northwind.promotions.name IS 'Promotion name.';
COMMENT ON COLUMN northwind.promotions.description IS 'Terms shown to customers.';
COMMENT ON COLUMN northwind.promotions.status IS 'Lifecycle state.';
COMMENT ON COLUMN northwind.promotions.validity_starts_on IS 'First day of the range.';
COMMENT ON COLUMN northwind.promotions.validity_ends_on IS 'Last day of the range; null when open-ended.';
COMMENT ON COLUMN northwind.promotions.budget_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.promotions.budget_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.promotions.max_redemptions IS 'Cap on redemptions across all customers.';
COMMENT ON COLUMN northwind.promotions.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.promotions.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.promotions.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.promotions.updated_by IS 'User name of the last editor.';
