-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.public_holidays of database main (PostgreSQL 16).
-- Maps entity PublicHoliday.

CREATE TABLE northwind.public_holidays (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    observed_on date NOT NULL,
    name varchar(100) NOT NULL,
    is_nationwide boolean NOT NULL DEFAULT true,
    country_code varchar(2) NOT NULL,
    CONSTRAINT pk_public_holidays PRIMARY KEY (id),
    CONSTRAINT fk_public_holidays_country_code FOREIGN KEY (country_code) REFERENCES northwind.countries (code) ON DELETE CASCADE
);
CREATE INDEX ix_public_holidays_observed_on ON northwind.public_holidays (observed_on);
