-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.purchase_requisitions of database main (PostgreSQL 16).
-- Maps entity PurchaseRequisition.

CREATE TABLE northwind.purchase_requisitions (
    id uuid NOT NULL,
    requisition_number varchar(20) NOT NULL,
    requested_on date NOT NULL,
    needed_by date NULL,
    status varchar(20) NOT NULL DEFAULT 'open',
    justification text NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    cost_center_id uuid NULL,
    requested_by_id uuid NOT NULL,
    warehouse_id uuid NULL,
    CONSTRAINT pk_purchase_requisitions PRIMARY KEY (id),
    CONSTRAINT uq_purchase_requisitions_requisition_number UNIQUE (requisition_number),
    CONSTRAINT fk_purchase_requisitions_cost_center_id FOREIGN KEY (cost_center_id) REFERENCES northwind.cost_centers (id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_requisitions_requested_by_id FOREIGN KEY (requested_by_id) REFERENCES northwind.employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_requisitions_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE SET NULL
);
