-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.purchase_orders of database main (PostgreSQL 16).
-- Maps entity PurchaseOrder.

CREATE TABLE northwind.purchase_orders (
    id uuid NOT NULL,
    po_number varchar(20) NOT NULL DEFAULT 'PO-' || lpad(nextval('northwind.purchase_order_number_seq')::text, 6, '0'),
    ordered_on date NOT NULL,
    status varchar(8) NOT NULL DEFAULT 'DRAFT',
    expected_on date NULL,
    freight_terms varchar(3) NULL,
    subtotal_amount numeric(19,4) NOT NULL,
    subtotal_currency varchar(3) NOT NULL,
    tax_total_amount numeric(19,4) NULL,
    tax_total_currency varchar(3) NULL,
    freight_total_amount numeric(19,4) NULL,
    freight_total_currency varchar(3) NULL,
    grand_total_amount numeric(19,4) NOT NULL,
    grand_total_currency varchar(3) NOT NULL,
    notes text NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    deleted_at timestamptz(6) NULL,
    requisition_id uuid NULL,
    buyer_id uuid NULL,
    warehouse_id uuid NOT NULL,
    currency_code varchar(3) NOT NULL,
    contract_id uuid NULL,
    payment_term_id integer NULL,
    supplier_id uuid NOT NULL,
    CONSTRAINT pk_purchase_orders PRIMARY KEY (id),
    CONSTRAINT uq_purchase_orders_po_number UNIQUE (po_number),
    CONSTRAINT fk_purchase_orders_requisition_id FOREIGN KEY (requisition_id) REFERENCES northwind.purchase_requisitions (id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_orders_buyer_id FOREIGN KEY (buyer_id) REFERENCES northwind.employees (id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_orders_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_currency_code FOREIGN KEY (currency_code) REFERENCES northwind.currencies (code) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_contract_id FOREIGN KEY (contract_id) REFERENCES northwind.supplier_contracts (id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_orders_payment_term_id FOREIGN KEY (payment_term_id) REFERENCES northwind.payment_terms (id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_orders_supplier_id FOREIGN KEY (supplier_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT
);
COMMENT ON COLUMN northwind.purchase_orders.po_number IS 'Assigned from purchase_order_number_seq when the application does not supply one.';
