-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.purchase_approvals of database main (PostgreSQL 16).
-- Maps entity PurchaseApproval.

CREATE TABLE northwind.purchase_approvals (
    id uuid NOT NULL,
    approval_level smallint NOT NULL,
    decision varchar(20) NOT NULL DEFAULT 'pending',
    decided_at timestamptz(6) NULL,
    comment varchar(500) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    approver_id uuid NOT NULL,
    purchase_order_id uuid NOT NULL,
    CONSTRAINT pk_purchase_approvals PRIMARY KEY (id),
    CONSTRAINT fk_purchase_approvals_approver_id FOREIGN KEY (approver_id) REFERENCES northwind.employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_approvals_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES northwind.purchase_orders (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.purchase_approvals IS 'One approval step of a purchase order, by amount threshold.';
COMMENT ON COLUMN northwind.purchase_approvals.id IS 'Surrogate key of the purchase approval.';
COMMENT ON COLUMN northwind.purchase_approvals.approval_level IS 'Step number.';
COMMENT ON COLUMN northwind.purchase_approvals.decision IS 'pending, approved or rejected.';
COMMENT ON COLUMN northwind.purchase_approvals.decided_at IS 'When the approver decided.';
COMMENT ON COLUMN northwind.purchase_approvals.comment IS 'Approver''s comment.';
COMMENT ON COLUMN northwind.purchase_approvals.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.purchase_approvals.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.purchase_approvals.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.purchase_approvals.updated_by IS 'User name of the last editor.';
