-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.putaway_tasks of database main (PostgreSQL 16).

CREATE TABLE northwind.putaway_tasks (
    id uuid NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'open',
    quantity numeric(14,3) NOT NULL,
    completed_at timestamptz(6) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    assigned_to_id uuid NULL,
    product_id uuid NOT NULL,
    goods_receipt_line_id uuid NULL,
    from_bin_id uuid NULL,
    to_bin_id uuid NOT NULL,
    CONSTRAINT pk_putaway_tasks PRIMARY KEY (id),
    CONSTRAINT fk_putaway_tasks_assigned_to_id FOREIGN KEY (assigned_to_id) REFERENCES northwind.employees (id) ON DELETE SET NULL,
    CONSTRAINT fk_putaway_tasks_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_putaway_tasks_goods_receipt_line_id FOREIGN KEY (goods_receipt_line_id) REFERENCES northwind.goods_receipt_lines (id) ON DELETE SET NULL,
    CONSTRAINT fk_putaway_tasks_from_bin_id FOREIGN KEY (from_bin_id) REFERENCES northwind.bin_locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_putaway_tasks_to_bin_id FOREIGN KEY (to_bin_id) REFERENCES northwind.bin_locations (id) ON DELETE RESTRICT
);
COMMENT ON TABLE northwind.putaway_tasks IS 'A task to move received goods from the dock to a storage bin.';
COMMENT ON COLUMN northwind.putaway_tasks.id IS 'Surrogate key of the putaway task.';
COMMENT ON COLUMN northwind.putaway_tasks.status IS 'open, in-progress or done.';
COMMENT ON COLUMN northwind.putaway_tasks.quantity IS 'Quantity to put away.';
COMMENT ON COLUMN northwind.putaway_tasks.completed_at IS 'When it was done.';
COMMENT ON COLUMN northwind.putaway_tasks.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.putaway_tasks.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.putaway_tasks.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.putaway_tasks.updated_by IS 'User name of the last editor.';
