-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.quality_inspections of database main (PostgreSQL 16).
-- Maps entity QualityInspection.

CREATE TABLE northwind.quality_inspections (
    id uuid NOT NULL,
    inspected_at timestamptz(6) NOT NULL,
    result varchar(20) NOT NULL,
    sample_size integer NULL,
    notes text NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    lot_id uuid NULL,
    product_id uuid NOT NULL,
    inspector_id uuid NULL,
    goods_receipt_line_id uuid NULL,
    CONSTRAINT pk_quality_inspections PRIMARY KEY (id),
    CONSTRAINT fk_quality_inspections_lot_id FOREIGN KEY (lot_id) REFERENCES northwind.stock_lots (id) ON DELETE SET NULL,
    CONSTRAINT fk_quality_inspections_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_quality_inspections_inspector_id FOREIGN KEY (inspector_id) REFERENCES northwind.employees (id) ON DELETE SET NULL,
    CONSTRAINT fk_quality_inspections_goods_receipt_line_id FOREIGN KEY (goods_receipt_line_id) REFERENCES northwind.goods_receipt_lines (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.quality_inspections IS 'An inspection of received or stored goods, which may put them on hold.';
COMMENT ON COLUMN northwind.quality_inspections.id IS 'Surrogate key of the quality inspection.';
COMMENT ON COLUMN northwind.quality_inspections.inspected_at IS 'When it was inspected.';
COMMENT ON COLUMN northwind.quality_inspections.result IS 'passed, failed or conditional.';
COMMENT ON COLUMN northwind.quality_inspections.sample_size IS 'Units inspected.';
COMMENT ON COLUMN northwind.quality_inspections.notes IS 'Findings.';
COMMENT ON COLUMN northwind.quality_inspections.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.quality_inspections.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.quality_inspections.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.quality_inspections.updated_by IS 'User name of the last editor.';
