-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.rebate_programs of database main (PostgreSQL 16).
-- Maps entity RebateProgram.

CREATE TABLE northwind.rebate_programs (
    id uuid NOT NULL,
    name varchar(150) NOT NULL,
    description text NULL,
    period_starts_on date NOT NULL,
    period_ends_on date NULL,
    rebate_rate numeric(5,2) NOT NULL,
    threshold_amount_amount numeric(19,4) NULL,
    threshold_amount_currency varchar(3) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    CONSTRAINT pk_rebate_programs PRIMARY KEY (id),
    CONSTRAINT fk_rebate_programs_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT
);
