-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.refunds of database main (PostgreSQL 16).
-- Maps entity Refund.

CREATE TABLE northwind.refunds (
    id uuid NOT NULL,
    refund_number varchar(20) NOT NULL,
    refunded_at timestamptz(6) NULL,
    amount_amount numeric(19,4) NOT NULL,
    amount_currency varchar(3) NOT NULL,
    method varchar(20) NOT NULL,
    status varchar(4) NOT NULL DEFAULT 'PEND',
    reference varchar(64) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    credit_note_id uuid NULL,
    payment_id uuid NULL,
    customer_id uuid NOT NULL,
    CONSTRAINT pk_refunds PRIMARY KEY (id),
    CONSTRAINT uq_refunds_refund_number UNIQUE (refund_number),
    CONSTRAINT fk_refunds_credit_note_id FOREIGN KEY (credit_note_id) REFERENCES northwind.credit_notes (id) ON DELETE SET NULL,
    CONSTRAINT fk_refunds_payment_id FOREIGN KEY (payment_id) REFERENCES northwind.payments (id) ON DELETE SET NULL,
    CONSTRAINT fk_refunds_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT
);
