-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.replacements of database main (PostgreSQL 16).

CREATE TABLE northwind.replacements (
    id uuid NOT NULL,
    quantity numeric(12,3) NOT NULL,
    shipped_on date NULL,
    is_charged boolean NOT NULL DEFAULT false,
    notes varchar(500) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    product_id uuid NOT NULL,
    return_line_id uuid NOT NULL,
    shipment_id uuid NULL,
    CONSTRAINT pk_replacements PRIMARY KEY (id),
    CONSTRAINT fk_replacements_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_replacements_return_line_id FOREIGN KEY (return_line_id) REFERENCES northwind.return_lines (id) ON DELETE RESTRICT,
    CONSTRAINT fk_replacements_shipment_id FOREIGN KEY (shipment_id) REFERENCES northwind.shipments (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.replacements IS 'A replacement sent for a returned or failed product before or instead of a credit.';
COMMENT ON COLUMN northwind.replacements.id IS 'Surrogate key of the replacement.';
COMMENT ON COLUMN northwind.replacements.quantity IS 'Quantity sent.';
COMMENT ON COLUMN northwind.replacements.shipped_on IS 'Ship date.';
COMMENT ON COLUMN northwind.replacements.is_charged IS 'Whether the customer pays for it.';
COMMENT ON COLUMN northwind.replacements.notes IS 'Remarks.';
COMMENT ON COLUMN northwind.replacements.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.replacements.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.replacements.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.replacements.updated_by IS 'User name of the last editor.';
