-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.replenishment_rules of database main (PostgreSQL 16).

CREATE TABLE northwind.replenishment_rules (
    id uuid NOT NULL,
    min_quantity numeric(14,3) NOT NULL,
    max_quantity numeric(14,3) NOT NULL,
    reorder_quantity numeric(14,3) NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    preferred_supplier_id uuid NULL,
    product_id uuid NOT NULL,
    warehouse_id uuid NOT NULL,
    CONSTRAINT pk_replenishment_rules PRIMARY KEY (id),
    CONSTRAINT fk_replenishment_rules_preferred_supplier_id FOREIGN KEY (preferred_supplier_id) REFERENCES northwind.parties (id) ON DELETE SET NULL,
    CONSTRAINT fk_replenishment_rules_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_replenishment_rules_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.replenishment_rules IS 'Min-max replenishment settings of a product in a warehouse.';
COMMENT ON COLUMN northwind.replenishment_rules.id IS 'Surrogate key of the replenishment rule.';
COMMENT ON COLUMN northwind.replenishment_rules.min_quantity IS 'Reorder when available stock falls below it.';
COMMENT ON COLUMN northwind.replenishment_rules.max_quantity IS 'Order up to this level.';
COMMENT ON COLUMN northwind.replenishment_rules.reorder_quantity IS 'Fixed order quantity, when used instead of max.';
COMMENT ON COLUMN northwind.replenishment_rules.is_active IS 'Whether the rule is evaluated.';
COMMENT ON COLUMN northwind.replenishment_rules.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.replenishment_rules.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.replenishment_rules.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.replenishment_rules.updated_by IS 'User name of the last editor.';
