-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.replenishment_rules of database main (PostgreSQL 16).
-- Maps entity ReplenishmentRule.

CREATE TABLE northwind.replenishment_rules (
    id uuid NOT NULL,
    min_quantity numeric(14,3) NOT NULL,
    max_quantity numeric(14,3) NOT NULL,
    reorder_quantity numeric(14,3) NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    preferred_supplier_id uuid NULL,
    product_id uuid NOT NULL,
    warehouse_id uuid NOT NULL,
    CONSTRAINT pk_replenishment_rules PRIMARY KEY (id),
    CONSTRAINT fk_replenishment_rules_preferred_supplier_id FOREIGN KEY (preferred_supplier_id) REFERENCES northwind.parties (id) ON DELETE SET NULL,
    CONSTRAINT fk_replenishment_rules_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_replenishment_rules_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE CASCADE
);
