-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.requisition_lines of database main (PostgreSQL 16).
-- Maps entity RequisitionLine.

CREATE TABLE northwind.requisition_lines (
    id uuid NOT NULL,
    description varchar(300) NOT NULL,
    quantity numeric(12,3) NOT NULL,
    estimated_cost_amount numeric(19,4) NULL,
    estimated_cost_currency varchar(3) NULL,
    purchase_requisition_id uuid NOT NULL,
    product_id uuid NULL,
    suggested_supplier_id uuid NULL,
    CONSTRAINT pk_requisition_lines PRIMARY KEY (id),
    CONSTRAINT fk_requisition_lines_purchase_requisition_id FOREIGN KEY (purchase_requisition_id) REFERENCES northwind.purchase_requisitions (id) ON DELETE CASCADE,
    CONSTRAINT fk_requisition_lines_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE SET NULL,
    CONSTRAINT fk_requisition_lines_suggested_supplier_id FOREIGN KEY (suggested_supplier_id) REFERENCES northwind.parties (id) ON DELETE SET NULL
);
