-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.request_for_quote_supplier of database main (PostgreSQL 16).
-- Junction table of relation "rfq invites supplier".

CREATE TABLE northwind.request_for_quote_supplier (
    requests_for_quote_id uuid NOT NULL,
    invited_suppliers_id uuid NOT NULL,
    invited_at timestamptz(6) NOT NULL,
    declined boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_request_for_quote_supplier PRIMARY KEY (requests_for_quote_id, invited_suppliers_id),
    CONSTRAINT fk_request_for_quote_supplier_requests_for_quote_id FOREIGN KEY (requests_for_quote_id) REFERENCES northwind.request_for_quotes (id) ON DELETE CASCADE,
    CONSTRAINT fk_request_for_quote_supplier_invited_suppliers_id FOREIGN KEY (invited_suppliers_id) REFERENCES northwind.parties (id) ON DELETE CASCADE
);
COMMENT ON TABLE northwind.request_for_quote_supplier IS 'Suppliers invited to quote on a request for quote, with the invitation date.';
COMMENT ON COLUMN northwind.request_for_quote_supplier.invited_at IS 'When the invitation was sent.';
COMMENT ON COLUMN northwind.request_for_quote_supplier.declined IS 'Whether the supplier declined to quote.';
