-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.request_for_quotes of database main (PostgreSQL 16).
-- Maps entity RequestForQuote.

CREATE TABLE northwind.request_for_quotes (
    id uuid NOT NULL,
    rfq_number varchar(20) NOT NULL,
    issued_on date NOT NULL,
    response_due_on date NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'open',
    description text NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    buyer_id uuid NULL,
    product_id uuid NULL,
    CONSTRAINT pk_request_for_quotes PRIMARY KEY (id),
    CONSTRAINT uq_request_for_quotes_rfq_number UNIQUE (rfq_number),
    CONSTRAINT fk_request_for_quotes_buyer_id FOREIGN KEY (buyer_id) REFERENCES northwind.employees (id) ON DELETE SET NULL,
    CONSTRAINT fk_request_for_quotes_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE SET NULL
);
