-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.return_lines of database main (PostgreSQL 16).

CREATE TABLE northwind.return_lines (
    id uuid NOT NULL,
    quantity numeric(12,3) NOT NULL,
    received_quantity numeric(12,3) NULL,
    item_condition varchar(20) NULL,
    disposition varchar(20) NULL,
    credit_amount_amount numeric(19,4) NULL,
    credit_amount_currency varchar(3) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    return_authorization_id uuid NOT NULL,
    sales_order_line_id char(26) NULL,
    lot_id uuid NULL,
    reason_id integer NOT NULL,
    product_id uuid NOT NULL,
    serial_number_id uuid NULL,
    CONSTRAINT pk_return_lines PRIMARY KEY (id),
    CONSTRAINT fk_return_lines_return_authorization_id FOREIGN KEY (return_authorization_id) REFERENCES northwind.return_authorizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_return_lines_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES northwind.sales_order_lines (id) ON DELETE SET NULL,
    CONSTRAINT fk_return_lines_lot_id FOREIGN KEY (lot_id) REFERENCES northwind.stock_lots (id) ON DELETE SET NULL,
    CONSTRAINT fk_return_lines_reason_id FOREIGN KEY (reason_id) REFERENCES northwind.return_reasons (id) ON DELETE RESTRICT,
    CONSTRAINT fk_return_lines_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_return_lines_serial_number_id FOREIGN KEY (serial_number_id) REFERENCES northwind.serial_numbers (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.return_lines IS 'A product and quantity on a return authorization, with its condition and disposition.';
COMMENT ON COLUMN northwind.return_lines.id IS 'Surrogate key of the return line.';
COMMENT ON COLUMN northwind.return_lines.quantity IS 'Quantity authorized.';
COMMENT ON COLUMN northwind.return_lines.received_quantity IS 'Quantity received.';
COMMENT ON COLUMN northwind.return_lines.item_condition IS 'new, opened or damaged.';
COMMENT ON COLUMN northwind.return_lines.disposition IS 'restock, scrap or return-to-vendor.';
COMMENT ON COLUMN northwind.return_lines.credit_amount_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.return_lines.credit_amount_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.return_lines.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.return_lines.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.return_lines.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.return_lines.updated_by IS 'User name of the last editor.';
