-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.role_permission of database main (PostgreSQL 16).
-- Junction table of relation "role grants permission".

CREATE TABLE northwind.role_permission (
    roles_id integer NOT NULL,
    permissions_id integer NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (roles_id, permissions_id),
    CONSTRAINT fk_role_permission_roles_id FOREIGN KEY (roles_id) REFERENCES northwind.roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permissions_id FOREIGN KEY (permissions_id) REFERENCES northwind.permissions (id) ON DELETE CASCADE
);
