-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.roles of database main (PostgreSQL 16).
-- Maps entity Role.

CREATE TABLE northwind.roles (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(80) NOT NULL,
    description varchar(500) NULL,
    is_system boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);
