-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.route_stops of database main (PostgreSQL 16).
-- Maps entity RouteStop.

CREATE TABLE northwind.route_stops (
    id uuid NOT NULL,
    stop_number smallint NOT NULL,
    address_line1 varchar(120) NOT NULL,
    address_line2 varchar(120) NULL,
    address_city varchar(80) NOT NULL,
    address_region varchar(80) NULL,
    address_postal_code varchar(20) NULL,
    address_country_code varchar(2) NOT NULL,
    location_latitude numeric(9,6) NULL,
    location_longitude numeric(9,6) NULL,
    planned_arrival_at timestamptz(6) NULL,
    actual_arrival_at timestamptz(6) NULL,
    delivery_route_id uuid NOT NULL,
    shipment_id uuid NULL,
    CONSTRAINT pk_route_stops PRIMARY KEY (id),
    CONSTRAINT fk_route_stops_delivery_route_id FOREIGN KEY (delivery_route_id) REFERENCES northwind.delivery_routes (id) ON DELETE CASCADE,
    CONSTRAINT fk_route_stops_shipment_id FOREIGN KEY (shipment_id) REFERENCES northwind.shipments (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.route_stops IS 'A stop on a delivery route.';
COMMENT ON COLUMN northwind.route_stops.id IS 'Surrogate key of the route stop.';
COMMENT ON COLUMN northwind.route_stops.stop_number IS 'Position on the route.';
COMMENT ON COLUMN northwind.route_stops.address_line1 IS 'Street and number, or PO box.';
COMMENT ON COLUMN northwind.route_stops.address_line2 IS 'Suite, floor or building.';
COMMENT ON COLUMN northwind.route_stops.address_city IS 'City or locality.';
COMMENT ON COLUMN northwind.route_stops.address_region IS 'State, province or county.';
COMMENT ON COLUMN northwind.route_stops.address_postal_code IS 'Postal or ZIP code.';
COMMENT ON COLUMN northwind.route_stops.address_country_code IS 'ISO country code.';
COMMENT ON COLUMN northwind.route_stops.location_latitude IS 'Degrees north of the equator.';
COMMENT ON COLUMN northwind.route_stops.location_longitude IS 'Degrees east of Greenwich.';
COMMENT ON COLUMN northwind.route_stops.planned_arrival_at IS 'Planned arrival.';
COMMENT ON COLUMN northwind.route_stops.actual_arrival_at IS 'Actual arrival.';
