-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.sales_channels of database main (PostgreSQL 16).
-- Maps entity SalesChannel.

CREATE TABLE northwind.sales_channels (
    id uuid NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    is_marketplace boolean NOT NULL DEFAULT false,
    commission_rate numeric(5,2) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_sales_channels PRIMARY KEY (id),
    CONSTRAINT uq_sales_channels_code UNIQUE (code)
);
