-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.sales_channels of database main (PostgreSQL 16).
-- Maps entity SalesChannel.

CREATE TABLE northwind.sales_channels (
    id uuid NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    is_marketplace boolean NOT NULL DEFAULT false,
    commission_rate numeric(5,2) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    CONSTRAINT pk_sales_channels PRIMARY KEY (id),
    CONSTRAINT uq_sales_channels_code UNIQUE (code)
);
COMMENT ON TABLE northwind.sales_channels IS 'A route to market, such as the customer portal, EDI or a marketplace.';
COMMENT ON COLUMN northwind.sales_channels.id IS 'Surrogate key of the sales channel.';
COMMENT ON COLUMN northwind.sales_channels.code IS 'Channel code.';
COMMENT ON COLUMN northwind.sales_channels.name IS 'Channel name.';
COMMENT ON COLUMN northwind.sales_channels.is_marketplace IS 'Whether a third party hosts the channel.';
COMMENT ON COLUMN northwind.sales_channels.commission_rate IS 'Fee the channel charges on sales.';
COMMENT ON COLUMN northwind.sales_channels.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.sales_channels.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.sales_channels.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.sales_channels.updated_by IS 'User name of the last editor.';
