-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.sales_order_lines of database main (PostgreSQL 16).

CREATE TABLE northwind.sales_order_lines (
    id char(26) NOT NULL,
    line_number integer NOT NULL,
    description varchar(300) NULL,
    quantity numeric(12,3) NOT NULL,
    unit_price_amount numeric(19,4) NOT NULL,
    unit_price_currency varchar(3) NOT NULL,
    discount numeric(5,2) NULL,
    tax_rate numeric(5,2) NULL,
    line_total_amount numeric(19,4) NOT NULL,
    line_total_currency varchar(3) NOT NULL,
    status integer NOT NULL DEFAULT 0,
    requested_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    sales_order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    variant_id uuid NULL,
    unit_code varchar(3) NOT NULL,
    warehouse_id uuid NULL,
    CONSTRAINT pk_sales_order_lines PRIMARY KEY (id),
    CONSTRAINT fk_sales_order_lines_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES northwind.sales_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_order_lines_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sales_order_lines_variant_id FOREIGN KEY (variant_id) REFERENCES northwind.product_variants (id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_order_lines_unit_code FOREIGN KEY (unit_code) REFERENCES northwind.units_of_measure (code) ON DELETE RESTRICT,
    CONSTRAINT fk_sales_order_lines_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE SET NULL,
    CONSTRAINT ck_sales_order_lines_quantity_positive CHECK (quantity > 0)
);
COMMENT ON TABLE northwind.sales_order_lines IS 'Quantity must be positive.';
COMMENT ON COLUMN northwind.sales_order_lines.id IS 'Surrogate key of the sales order line.';
COMMENT ON COLUMN northwind.sales_order_lines.line_number IS 'Line number printed on documents.';
COMMENT ON COLUMN northwind.sales_order_lines.description IS 'Line text, defaulting to the product name.';
COMMENT ON COLUMN northwind.sales_order_lines.quantity IS 'Quantity ordered, in the line''s unit.';
COMMENT ON COLUMN northwind.sales_order_lines.unit_price_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.sales_order_lines.unit_price_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.sales_order_lines.discount IS 'Line discount.';
COMMENT ON COLUMN northwind.sales_order_lines.tax_rate IS 'Sales tax rate applied.';
COMMENT ON COLUMN northwind.sales_order_lines.line_total_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.sales_order_lines.line_total_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.sales_order_lines.status IS 'Fulfillment state.';
COMMENT ON COLUMN northwind.sales_order_lines.requested_on IS 'Requested delivery date, when it differs from the order''s.';
COMMENT ON COLUMN northwind.sales_order_lines.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.sales_order_lines.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.sales_order_lines.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.sales_order_lines.updated_by IS 'User name of the last editor.';
