-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.sales_order_notes of database main (PostgreSQL 16).
-- Maps entity SalesOrderNote.

CREATE TABLE northwind.sales_order_notes (
    id uuid NOT NULL,
    body text NOT NULL,
    is_customer_visible boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    sales_order_id uuid NOT NULL,
    author_id uuid NULL,
    CONSTRAINT pk_sales_order_notes PRIMARY KEY (id),
    CONSTRAINT fk_sales_order_notes_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES northwind.sales_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_order_notes_author_id FOREIGN KEY (author_id) REFERENCES northwind.user_accounts (id) ON DELETE SET NULL
);
