-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.sales_territories of database main (PostgreSQL 16).
-- Maps entity SalesTerritory.

CREATE TABLE northwind.sales_territories (
    id uuid NOT NULL,
    code varchar(12) NOT NULL,
    name varchar(100) NOT NULL,
    annual_quota_amount numeric(19,4) NULL,
    annual_quota_currency varchar(3) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    manager_id uuid NULL,
    parent_id uuid NULL,
    CONSTRAINT pk_sales_territories PRIMARY KEY (id),
    CONSTRAINT uq_sales_territories_code UNIQUE (code),
    CONSTRAINT fk_sales_territories_manager_id FOREIGN KEY (manager_id) REFERENCES northwind.employees (id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_territories_parent_id FOREIGN KEY (parent_id) REFERENCES northwind.sales_territories (id) ON DELETE SET NULL
);
