-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.sales_quote_lines of database main (PostgreSQL 16).
-- Maps entity SalesQuoteLine.

CREATE TABLE northwind.sales_quote_lines (
    id uuid NOT NULL,
    quantity numeric(12,3) NOT NULL,
    unit_price_amount numeric(19,4) NOT NULL,
    unit_price_currency varchar(3) NOT NULL,
    discount numeric(5,2) NULL,
    line_total_amount numeric(19,4) NULL,
    line_total_currency varchar(3) NULL,
    product_id uuid NOT NULL,
    unit_code varchar(3) NULL,
    sales_quote_id uuid NOT NULL,
    CONSTRAINT pk_sales_quote_lines PRIMARY KEY (id),
    CONSTRAINT fk_sales_quote_lines_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sales_quote_lines_unit_code FOREIGN KEY (unit_code) REFERENCES northwind.units_of_measure (code) ON DELETE SET NULL,
    CONSTRAINT fk_sales_quote_lines_sales_quote_id FOREIGN KEY (sales_quote_id) REFERENCES northwind.sales_quotes (id) ON DELETE CASCADE
);
