-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.sales_activities of database main (PostgreSQL 16).
-- Maps entity SalesActivity.

CREATE TABLE northwind.sales_activities (
    id uuid NOT NULL,
    activity_type varchar(5) NOT NULL,
    subject varchar(200) NOT NULL,
    due_at timestamptz(6) NULL,
    completed_at timestamptz(6) NULL,
    notes text NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    party_id uuid NOT NULL,
    contact_id uuid NULL,
    owner_id uuid NOT NULL,
    opportunity_id uuid NULL,
    CONSTRAINT pk_sales_activities PRIMARY KEY (id),
    CONSTRAINT fk_sales_activities_party_id FOREIGN KEY (party_id) REFERENCES northwind.parties (id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_activities_contact_id FOREIGN KEY (contact_id) REFERENCES northwind.contacts (id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_activities_owner_id FOREIGN KEY (owner_id) REFERENCES northwind.employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sales_activities_opportunity_id FOREIGN KEY (opportunity_id) REFERENCES northwind.opportunities (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.sales_activities IS 'A call, email, meeting, visit or task logged against a party.';
COMMENT ON COLUMN northwind.sales_activities.id IS 'Surrogate key of the sales activity.';
COMMENT ON COLUMN northwind.sales_activities.activity_type IS 'Kind of activity.';
COMMENT ON COLUMN northwind.sales_activities.subject IS 'One-line summary.';
COMMENT ON COLUMN northwind.sales_activities.due_at IS 'When the activity is scheduled or due.';
COMMENT ON COLUMN northwind.sales_activities.completed_at IS 'When it was done.';
COMMENT ON COLUMN northwind.sales_activities.notes IS 'Outcome and details.';
COMMENT ON COLUMN northwind.sales_activities.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.sales_activities.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.sales_activities.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.sales_activities.updated_by IS 'User name of the last editor.';
