-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.sales_order_attachments of database main (PostgreSQL 16).
-- Maps entity SalesOrderAttachment.

CREATE TABLE northwind.sales_order_attachments (
    id char(26) NOT NULL,
    file_name varchar(255) NOT NULL,
    content_type varchar(100) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_key varchar(400) NOT NULL,
    uploaded_at timestamptz(6) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    uploaded_by_id uuid NULL,
    sales_order_id uuid NOT NULL,
    CONSTRAINT pk_sales_order_attachments PRIMARY KEY (id),
    CONSTRAINT fk_sales_order_attachments_uploaded_by_id FOREIGN KEY (uploaded_by_id) REFERENCES northwind.user_accounts (id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_order_attachments_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES northwind.sales_orders (id) ON DELETE CASCADE
);
