-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.shipping_zones of database main (PostgreSQL 16).
-- Maps entity ShippingZone.

CREATE TABLE northwind.shipping_zones (
    id uuid NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(300) NULL,
    country_code varchar(2) NULL,
    origin_warehouse_id uuid NULL,
    CONSTRAINT pk_shipping_zones PRIMARY KEY (id),
    CONSTRAINT uq_shipping_zones_code UNIQUE (code),
    CONSTRAINT fk_shipping_zones_country_code FOREIGN KEY (country_code) REFERENCES northwind.countries (code) ON DELETE SET NULL,
    CONSTRAINT fk_shipping_zones_origin_warehouse_id FOREIGN KEY (origin_warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE SET NULL
);
