-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.sign_in_attempts of database main (PostgreSQL 16).
-- Maps entity SignInAttempt.

CREATE TABLE northwind.sign_in_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    attempted_at timestamptz(6) NOT NULL,
    user_name varchar(64) NOT NULL,
    succeeded boolean NOT NULL,
    failure_reason varchar(60) NULL,
    ip_address varchar(45) NOT NULL,
    user_account_id uuid NULL,
    CONSTRAINT pk_sign_in_attempts PRIMARY KEY (id),
    CONSTRAINT fk_sign_in_attempts_user_account_id FOREIGN KEY (user_account_id) REFERENCES northwind.user_accounts (id) ON DELETE CASCADE
);
CREATE INDEX ix_sign_in_attempts_attempted_at ON northwind.sign_in_attempts (attempted_at);
