-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.standing_orders of database main (PostgreSQL 16).
-- Maps entity StandingOrder.

CREATE TABLE northwind.standing_orders (
    id uuid NOT NULL,
    name varchar(120) NOT NULL,
    frequency varchar(20) NOT NULL,
    next_run_on date NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    validity_starts_on date NULL,
    validity_ends_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    ship_to_id uuid NULL,
    CONSTRAINT pk_standing_orders PRIMARY KEY (id),
    CONSTRAINT fk_standing_orders_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT,
    CONSTRAINT fk_standing_orders_ship_to_id FOREIGN KEY (ship_to_id) REFERENCES northwind.party_addresses (id) ON DELETE SET NULL
);
CREATE INDEX ix_standing_orders_next_run_on ON northwind.standing_orders (next_run_on);
