-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.state_provinces of database main (PostgreSQL 16).
-- Maps entity StateProvince.

CREATE TABLE northwind.state_provinces (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(6) NOT NULL,
    name varchar(100) NOT NULL,
    subdivision_type varchar(40) NULL,
    country_code varchar(2) NOT NULL,
    CONSTRAINT pk_state_provinces PRIMARY KEY (id),
    CONSTRAINT uq_state_provinces_code UNIQUE (code),
    CONSTRAINT fk_state_provinces_country_code FOREIGN KEY (country_code) REFERENCES northwind.countries (code) ON DELETE CASCADE
);
