-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.stock_lots of database main (PostgreSQL 16).
-- Maps entity StockLot.

CREATE TABLE northwind.stock_lots (
    id uuid NOT NULL,
    lot_number varchar(40) NOT NULL,
    supplier_lot_number varchar(40) NULL,
    manufactured_on date NULL,
    expires_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    product_id uuid NOT NULL,
    supplier_id uuid NULL,
    CONSTRAINT pk_stock_lots PRIMARY KEY (id),
    CONSTRAINT fk_stock_lots_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_lots_supplier_id FOREIGN KEY (supplier_id) REFERENCES northwind.parties (id) ON DELETE SET NULL
);
CREATE INDEX ix_stock_lots_lot_number ON northwind.stock_lots (lot_number);
CREATE INDEX ix_stock_lots_expires_on ON northwind.stock_lots (expires_on);
