-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.stock_reservations of database main (PostgreSQL 16).
-- Maps entity StockReservation.

CREATE TABLE northwind.stock_reservations (
    id uuid NOT NULL,
    quantity numeric(14,3) NOT NULL,
    reserved_at timestamptz(6) NOT NULL,
    expires_at timestamptz(6) NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    inventory_item_id uuid NOT NULL,
    sales_order_line_id char(26) NOT NULL,
    CONSTRAINT pk_stock_reservations PRIMARY KEY (id),
    CONSTRAINT fk_stock_reservations_inventory_item_id FOREIGN KEY (inventory_item_id) REFERENCES northwind.inventory_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_reservations_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES northwind.sales_order_lines (id) ON DELETE CASCADE
);
