-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.supplier_invoices of database main (PostgreSQL 16).
-- Maps entity SupplierInvoice.

CREATE TABLE northwind.supplier_invoices (
    id uuid NOT NULL,
    invoice_number varchar(40) NOT NULL,
    invoice_date date NOT NULL,
    due_date date NOT NULL,
    total_amount_amount numeric(19,4) NOT NULL,
    total_amount_currency varchar(3) NOT NULL,
    tax_amount_amount numeric(19,4) NULL,
    tax_amount_currency varchar(3) NULL,
    status varchar(20) NOT NULL DEFAULT 'received',
    matched_at timestamptz(6) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    purchase_order_id uuid NULL,
    journal_entry_id bigint NULL,
    supplier_id uuid NOT NULL,
    CONSTRAINT pk_supplier_invoices PRIMARY KEY (id),
    CONSTRAINT fk_supplier_invoices_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES northwind.purchase_orders (id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_invoices_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES northwind.journal_entries (id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_invoices_supplier_id FOREIGN KEY (supplier_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT
);
CREATE INDEX ix_supplier_invoices_due_date ON northwind.supplier_invoices (due_date);
