-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.supplier_certifications of database main (PostgreSQL 16).
-- Maps entity SupplierCertification.

CREATE TABLE northwind.supplier_certifications (
    id uuid NOT NULL,
    certification_type varchar(60) NOT NULL,
    certificate_number varchar(60) NULL,
    validity_starts_on date NOT NULL,
    validity_ends_on date NULL,
    document_url varchar(400) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    supplier_id uuid NOT NULL,
    CONSTRAINT pk_supplier_certifications PRIMARY KEY (id),
    CONSTRAINT fk_supplier_certifications_supplier_id FOREIGN KEY (supplier_id) REFERENCES northwind.parties (id) ON DELETE CASCADE
);
