-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.tax_jurisdictions of database main (PostgreSQL 16).
-- Maps entity TaxJurisdiction.

CREATE TABLE northwind.tax_jurisdictions (
    id uuid NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(120) NOT NULL,
    level varchar(20) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    country_code varchar(2) NOT NULL,
    state_province_id integer NULL,
    parent_id uuid NULL,
    CONSTRAINT pk_tax_jurisdictions PRIMARY KEY (id),
    CONSTRAINT uq_tax_jurisdictions_code UNIQUE (code),
    CONSTRAINT fk_tax_jurisdictions_country_code FOREIGN KEY (country_code) REFERENCES northwind.countries (code) ON DELETE RESTRICT,
    CONSTRAINT fk_tax_jurisdictions_state_province_id FOREIGN KEY (state_province_id) REFERENCES northwind.state_provinces (id) ON DELETE SET NULL,
    CONSTRAINT fk_tax_jurisdictions_parent_id FOREIGN KEY (parent_id) REFERENCES northwind.tax_jurisdictions (id) ON DELETE SET NULL
);
