-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.tax_rates of database main (PostgreSQL 16).

CREATE TABLE northwind.tax_rates (
    id uuid NOT NULL,
    name varchar(100) NOT NULL,
    rate numeric(5,2) NOT NULL,
    tax_category varchar(30) NOT NULL,
    validity_starts_on date NOT NULL,
    validity_ends_on date NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    jurisdiction_id uuid NOT NULL,
    sales_tax_account_id uuid NULL,
    CONSTRAINT pk_tax_rates PRIMARY KEY (id),
    CONSTRAINT fk_tax_rates_jurisdiction_id FOREIGN KEY (jurisdiction_id) REFERENCES northwind.tax_jurisdictions (id) ON DELETE CASCADE,
    CONSTRAINT fk_tax_rates_sales_tax_account_id FOREIGN KEY (sales_tax_account_id) REFERENCES northwind.ledger_accounts (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.tax_rates IS 'A sales tax rate of a jurisdiction for a tax category and period.';
COMMENT ON COLUMN northwind.tax_rates.id IS 'Surrogate key of the tax rate.';
COMMENT ON COLUMN northwind.tax_rates.name IS 'Rate name, such as Colorado state sales tax.';
COMMENT ON COLUMN northwind.tax_rates.rate IS 'Rate.';
COMMENT ON COLUMN northwind.tax_rates.tax_category IS 'Goods category, such as general or food.';
COMMENT ON COLUMN northwind.tax_rates.validity_starts_on IS 'First day of the range.';
COMMENT ON COLUMN northwind.tax_rates.validity_ends_on IS 'Last day of the range; null when open-ended.';
COMMENT ON COLUMN northwind.tax_rates.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.tax_rates.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.tax_rates.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.tax_rates.updated_by IS 'User name of the last editor.';
