-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.tracking_events of database main (PostgreSQL 16).
-- Maps entity TrackingEvent.

CREATE TABLE northwind.tracking_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    occurred_at timestamptz(6) NOT NULL,
    event_code varchar(10) NOT NULL,
    description varchar(200) NULL,
    city varchar(80) NULL,
    country_code varchar(2) NULL,
    shipment_id uuid NOT NULL,
    CONSTRAINT pk_tracking_events PRIMARY KEY (id),
    CONSTRAINT fk_tracking_events_shipment_id FOREIGN KEY (shipment_id) REFERENCES northwind.shipments (id) ON DELETE CASCADE
);
