-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.units_of_measure of database main (PostgreSQL 16).
-- Maps entity UnitOfMeasure.

CREATE TABLE northwind.units_of_measure (
    code varchar(3) NOT NULL,
    name varchar(60) NOT NULL,
    dimension varchar(20) NOT NULL,
    is_base_unit boolean NOT NULL DEFAULT false,
    decimals_allowed smallint NOT NULL DEFAULT 0,
    CONSTRAINT pk_units_of_measure PRIMARY KEY (code)
);
