-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.user_sessions of database main (PostgreSQL 16).
-- Maps entity UserSession.

CREATE TABLE northwind.user_sessions (
    id char(26) NOT NULL,
    started_at timestamptz(6) NOT NULL,
    expires_at timestamptz(6) NOT NULL,
    last_seen_at timestamptz(6) NULL,
    ip_address varchar(45) NULL,
    user_agent varchar(400) NULL,
    revoked_at timestamptz(6) NULL,
    user_account_id uuid NOT NULL,
    CONSTRAINT pk_user_sessions PRIMARY KEY (id),
    CONSTRAINT fk_user_sessions_user_account_id FOREIGN KEY (user_account_id) REFERENCES northwind.user_accounts (id) ON DELETE CASCADE
);
CREATE INDEX ix_user_sessions_expires_at ON northwind.user_sessions (expires_at);
COMMENT ON TABLE northwind.user_sessions IS 'A signed-in session of a user account, kept to support sign-out everywhere and anomaly detection.';
COMMENT ON COLUMN northwind.user_sessions.id IS 'Surrogate key of the user session.';
COMMENT ON COLUMN northwind.user_sessions.started_at IS 'When the session was created.';
COMMENT ON COLUMN northwind.user_sessions.expires_at IS 'Absolute expiry.';
COMMENT ON COLUMN northwind.user_sessions.last_seen_at IS 'Last request on the session.';
COMMENT ON COLUMN northwind.user_sessions.ip_address IS 'Client IP address (IPv4 or IPv6).';
COMMENT ON COLUMN northwind.user_sessions.user_agent IS 'Client user agent string.';
COMMENT ON COLUMN northwind.user_sessions.revoked_at IS 'When the session was revoked; null while valid.';
