-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.warehouse_equipment of database main (PostgreSQL 16).
-- Maps entity WarehouseEquipment.

CREATE TABLE northwind.warehouse_equipment (
    id uuid NOT NULL,
    asset_tag varchar(20) NOT NULL,
    equipment_type varchar(40) NOT NULL,
    manufacturer_name varchar(80) NULL,
    model_name varchar(80) NULL,
    last_inspected_on date NULL,
    is_operational boolean NOT NULL DEFAULT true,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    warehouse_id uuid NOT NULL,
    CONSTRAINT pk_warehouse_equipment PRIMARY KEY (id),
    CONSTRAINT uq_warehouse_equipment_asset_tag UNIQUE (asset_tag),
    CONSTRAINT fk_warehouse_equipment_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE RESTRICT
);
