-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.warehouse_zones of database main (PostgreSQL 16).
-- Maps entity WarehouseZone.

CREATE TABLE northwind.warehouse_zones (
    id uuid NOT NULL,
    code varchar(10) NOT NULL,
    name varchar(100) NOT NULL,
    zone_type varchar(20) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    warehouse_id uuid NOT NULL,
    storage_condition_id integer NULL,
    CONSTRAINT pk_warehouse_zones PRIMARY KEY (id),
    CONSTRAINT fk_warehouse_zones_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES northwind.warehouses (id) ON DELETE CASCADE,
    CONSTRAINT fk_warehouse_zones_storage_condition_id FOREIGN KEY (storage_condition_id) REFERENCES northwind.storage_conditions (id) ON DELETE SET NULL
);
COMMENT ON TABLE northwind.warehouse_zones IS 'An area of a warehouse with one purpose, such as receiving, bulk storage, pick faces or a freezer.';
COMMENT ON COLUMN northwind.warehouse_zones.id IS 'Surrogate key of the warehouse zone.';
COMMENT ON COLUMN northwind.warehouse_zones.code IS 'Zone code within the warehouse.';
COMMENT ON COLUMN northwind.warehouse_zones.name IS 'Zone name.';
COMMENT ON COLUMN northwind.warehouse_zones.zone_type IS 'receiving, bulk, pick, staging, quarantine or shipping.';
COMMENT ON COLUMN northwind.warehouse_zones.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.warehouse_zones.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.warehouse_zones.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.warehouse_zones.updated_by IS 'User name of the last editor.';
