-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.warehouses of database main (PostgreSQL 16).
-- Maps entity Warehouse.

CREATE TABLE northwind.warehouses (
    id uuid NOT NULL,
    code varchar(10) NOT NULL,
    name varchar(100) NOT NULL,
    address_line1 varchar(120) NOT NULL,
    address_line2 varchar(120) NULL,
    address_city varchar(80) NOT NULL,
    address_region varchar(80) NULL,
    address_postal_code varchar(20) NULL,
    address_country_code varchar(2) NOT NULL,
    location_latitude numeric(9,6) NULL,
    location_longitude numeric(9,6) NULL,
    time_zone varchar(40) NOT NULL,
    floor_area_sqm numeric(10,2) NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    cost_center_id uuid NULL,
    manager_id uuid NULL,
    CONSTRAINT pk_warehouses PRIMARY KEY (id),
    CONSTRAINT uq_warehouses_code UNIQUE (code),
    CONSTRAINT fk_warehouses_cost_center_id FOREIGN KEY (cost_center_id) REFERENCES northwind.cost_centers (id) ON DELETE SET NULL,
    CONSTRAINT fk_warehouses_manager_id FOREIGN KEY (manager_id) REFERENCES northwind.employees (id) ON DELETE SET NULL
);
