-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.warranty_claims of database main (PostgreSQL 16).
-- Maps entity WarrantyClaim.

CREATE TABLE northwind.warranty_claims (
    id uuid NOT NULL,
    claim_number varchar(20) NOT NULL,
    filed_on date NOT NULL,
    failure_description text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'filed',
    claim_amount_amount numeric(19,4) NULL,
    claim_amount_currency varchar(3) NULL,
    resolution varchar(500) NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    customer_id uuid NOT NULL,
    manufacturer_id uuid NULL,
    product_id uuid NOT NULL,
    serial_number_id uuid NULL,
    CONSTRAINT pk_warranty_claims PRIMARY KEY (id),
    CONSTRAINT uq_warranty_claims_claim_number UNIQUE (claim_number),
    CONSTRAINT fk_warranty_claims_customer_id FOREIGN KEY (customer_id) REFERENCES northwind.parties (id) ON DELETE RESTRICT,
    CONSTRAINT fk_warranty_claims_manufacturer_id FOREIGN KEY (manufacturer_id) REFERENCES northwind.manufacturers (id) ON DELETE SET NULL,
    CONSTRAINT fk_warranty_claims_product_id FOREIGN KEY (product_id) REFERENCES northwind.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_warranty_claims_serial_number_id FOREIGN KEY (serial_number_id) REFERENCES northwind.serial_numbers (id) ON DELETE SET NULL
);
