-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table northwind.write_offs of database main (PostgreSQL 16).

CREATE TABLE northwind.write_offs (
    id uuid NOT NULL,
    written_off_on date NOT NULL,
    amount_amount numeric(19,4) NOT NULL,
    amount_currency varchar(3) NOT NULL,
    reason varchar(300) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    created_by varchar(64) NULL,
    updated_at timestamptz(6) NULL,
    updated_by varchar(64) NULL,
    approved_by_id uuid NULL,
    journal_entry_id bigint NULL,
    invoice_id uuid NOT NULL,
    CONSTRAINT pk_write_offs PRIMARY KEY (id),
    CONSTRAINT fk_write_offs_approved_by_id FOREIGN KEY (approved_by_id) REFERENCES northwind.employees (id) ON DELETE SET NULL,
    CONSTRAINT fk_write_offs_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES northwind.journal_entries (id) ON DELETE SET NULL,
    CONSTRAINT fk_write_offs_invoice_id FOREIGN KEY (invoice_id) REFERENCES northwind.invoices (id) ON DELETE RESTRICT
);
COMMENT ON TABLE northwind.write_offs IS 'A bad debt write-off of an uncollectable invoice balance.';
COMMENT ON COLUMN northwind.write_offs.id IS 'Surrogate key of the write off.';
COMMENT ON COLUMN northwind.write_offs.written_off_on IS 'Date written off.';
COMMENT ON COLUMN northwind.write_offs.amount_amount IS 'The amount in the currency''s major unit.';
COMMENT ON COLUMN northwind.write_offs.amount_currency IS 'The ISO 4217 currency of the amount.';
COMMENT ON COLUMN northwind.write_offs.reason IS 'Why it is uncollectable.';
COMMENT ON COLUMN northwind.write_offs.created_at IS 'When the row was created.';
COMMENT ON COLUMN northwind.write_offs.created_by IS 'User name of the creator.';
COMMENT ON COLUMN northwind.write_offs.updated_at IS 'When the row was last changed.';
COMMENT ON COLUMN northwind.write_offs.updated_by IS 'User name of the last editor.';
