-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table customer_notes of database local (SQLite).
-- Maps entity CustomerNote.
-- A note on a customer. Stored in the shared notes table with entity_type 'customer'.

CREATE TABLE customer_notes (
    id text NOT NULL,
    customer_id text NOT NULL,
    body text NOT NULL,
    created_at text NULL,
    CONSTRAINT pk_customer_notes PRIMARY KEY (id)
);
