-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table invoice_notes of database local (SQLite).
-- A note on an invoice. Stored in the shared notes table with entity_type 'invoice'.

CREATE TABLE invoice_notes (
    id text NOT NULL,
    invoice_id text NOT NULL,
    body text NOT NULL,
    created_at text NULL,
    CONSTRAINT pk_invoice_notes PRIMARY KEY (id)
);
