-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table invoices of database local (SQLite).
-- Maps entity Invoice.
-- # Invoice  A bill issued to a customer. Its number is assigned when it is issued and never reused.

CREATE TABLE invoices (
    id text NOT NULL,
    number text NOT NULL,
    issued_on text NOT NULL,
    total_amount numeric NULL,
    total_currency text NULL,
    status integer NOT NULL DEFAULT 0,
    notes text NULL,
    created_at text NOT NULL,
    updated_at text NULL,
    deleted_at text NULL,
    reason text NULL,
    discriminator text NOT NULL,
    customer_id text NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id),
    CONSTRAINT uq_invoices_number UNIQUE (number),
    CONSTRAINT fk_invoices_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT
);
CREATE INDEX ix_invoices_issued_on ON invoices (issued_on);
