-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table revenue_months of database local (SQLite).
-- Maps entity RevenueMonth.
-- Invoiced revenue per month, read through the RevenueByMonth query; read-only.

CREATE TABLE revenue_months (
    month text NOT NULL,
    invoice_count integer NOT NULL,
    revenue numeric NOT NULL,
    CONSTRAINT pk_revenue_months PRIMARY KEY (month)
);
