using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Maquettiste.Engine;
using Maquettiste.Engine.Diagnostics;
using Maquettiste.Engine.Pipeline;
using Maquettiste.Testing;

namespace Maquettiste.Packs.Tests;

/// <summary>
/// The <c>process-docs</c> pack over the gate 3 fixture (phase-3-design.md sections 7.2 and 8.1): the golden pages under
/// <c>tests/fixtures/golden/process-docs/processes/</c> (<c>MAQUETTISTE_UPDATE_GOLDEN=1</c> rewrites them), determinism across
/// parallelism, a second run that writes nothing, and a syntax check of every state diagram the pages hold.
/// </summary>
public sealed partial class ProcessDocsTests
{
    // The opening of a page's diagram block. Its language tag names the syntax of the diagram text because renderers draw only a
    // tagged block; it is the one place the tests name that syntax.
    private const string DiagramFence = "```mermaid\n";

    private static readonly FileChangeKind[] Writes = [FileChangeKind.Added, FileChangeKind.Modified, FileChangeKind.Deleted, FileChangeKind.HandEdited, FileChangeKind.Conflict, FileChangeKind.OrphanedOwned];

    [Fact]
    public async Task Process_docs_over_the_gate_3_fixture_matches_the_golden_tree()
    {
        using var repo = new DocsRepo("processes");
        await repo.GenerateCleanlyAsync(jobs: 4);
        Golden.AssertMatches(Fixtures.Path("golden", "process-docs", "processes"), repo.PathOf("docs"));
    }

    [Fact]
    public void The_gate_3_fixture_registers_the_pack_with_a_committed_docs_root()
    {
        var settings = JsonNode.Parse(File.ReadAllText(Fixtures.Path("models", "processes", ".maquettiste", "maquettiste.json")))!;
        Assert.Equal("docs", (string?)settings["packs"]!["process-docs"]!["output"]);
        Assert.Contains(settings["outputs"]!["allow"]!.AsArray(), root => (string?)root!["path"] == "docs" && (bool?)root["commit"] == true);
    }

    [Fact]
    public async Task One_job_and_eight_jobs_write_the_same_bytes()
    {
        using var one = new DocsRepo("processes");
        using var eight = new DocsRepo("processes");
        await one.GenerateCleanlyAsync(jobs: 1);
        await eight.GenerateCleanlyAsync(jobs: 8);
        Assert.Empty(Golden.Compare(one.PathOf("docs"), eight.PathOf("docs")));
        Assert.NotEmpty(Directory.EnumerateFiles(one.PathOf("docs"), "*.md", SearchOption.AllDirectories));
    }

    [Fact]
    public async Task A_second_run_renders_nothing_and_check_finds_no_drift()
    {
        using var repo = new DocsRepo("processes");
        var first = await repo.GenerateCleanlyAsync();
        Assert.Equal(25, first.FilesWritten);

        var again = await repo.GenerateCleanlyAsync();
        Assert.DoesNotContain(again.Changes, c => Writes.Contains(c.Kind));
        Assert.Equal(0, again.UnitsRendered);
        Assert.Equal(0, again.FilesWritten);

        var check = await repo.GenerateAsync(GenerationMode.Check);
        Assert.True(check.Outcome == RunOutcome.Succeeded, DocsRepo.Describe(check));
    }

    [Fact]
    public async Task Every_page_starts_with_the_banner_and_ends_with_one_newline()
    {
        using var repo = new DocsRepo("processes");
        await repo.GenerateCleanlyAsync();
        foreach (var file in Directory.EnumerateFiles(repo.PathOf("docs"), "*.md", SearchOption.AllDirectories))
        {
            var text = File.ReadAllText(file);
            Assert.StartsWith("<!-- Generated by Maquettiste (process-docs/", text, StringComparison.Ordinal);
            Assert.EndsWith("\n", text, StringComparison.Ordinal);
            Assert.DoesNotContain("\n\n\n", text, StringComparison.Ordinal);
        }
    }

    [Fact]
    public async Task Every_state_diagram_of_the_gate_3_fixture_parses()
    {
        using var repo = new DocsRepo("processes");
        await repo.GenerateCleanlyAsync();
        var diagrams = DiagramsOf(repo);
        Assert.Equal(2, diagrams.Count);
        foreach (var (path, text) in diagrams)
        {
            var problems = DiagramText.Problems(text);
            Assert.True(problems.Count == 0, path + ":\n" + string.Join('\n', problems));
        }

        // The shapes the design asks for: nested blocks, "--" between regions, the choice, the deep history and its default,
        // the targetless timer as a note, the gate's count on the gated edge.
        var sales = diagrams["processes/sales-order-lifecycle.md"];
        Assert.Contains("    state Fulfilment {\n        [*] --> Processing\n        state Processing {\n", sales, StringComparison.Ordinal);
        Assert.Contains("            }\n            --\n            state Shipping {\n", sales, StringComparison.Ordinal);
        Assert.Contains("    state CreditCheck <<choice>>\n", sales, StringComparison.Ordinal);
        Assert.Contains("        state \"Resume H*\" as Resume\n", sales, StringComparison.Ordinal);
        Assert.Contains("        Resume --> Processing : default\n", sales, StringComparison.Ordinal);
        Assert.Contains("    CreditReview --> Fulfilment : approveCredit (gate 2 of 2)\n", sales, StringComparison.Ordinal);
        Assert.Contains("    Fulfilment --> Cancelled : cancel [notShipped]\n", sales, StringComparison.Ordinal);
        var purchase = diagrams["processes/purchase-approval.md"];
        Assert.Contains("    note right of Approval\n        internal: after 5d / sendReminder\n    end note\n", purchase, StringComparison.Ordinal);
        Assert.Contains("    BudgetRejected --> Drafting : requestChanges\n", purchase, StringComparison.Ordinal);
    }

    [Fact]
    public async Task Diagrams_give_repeated_and_reserved_names_path_ids_and_put_notes_inside_blocks()
    {
        using var repo = new DocsRepo("process-basics");
        repo.EditJson(".maquettiste/model/processes/order-lifecycle.json", process =>
        {
            // Billing.Paid becomes a second "Shipped" (Shipping has one) and Review.Escalated becomes "State", a keyword of the
            // diagram text; a targetless transition on Review.Pending gives the Review block a note, and one on the region Billing
            // of the parallel state Fulfilment gives that region a note inside its part of the parallel block.
            Rename(process["states"]!, "01JSTA00000000000000000013", "Shipped");
            Rename(process["states"]!, "01JSTA00000000000000000005", "State");
            process["transitions"]!.AsArray().Add(new JsonObject
            {
                ["id"] = "01JTRN0000000000000000P5D1",
                ["source"] = "01JSTA00000000000000000004",
                ["event"] = "01JPRX00000000000000000004",
                ["actions"] = new JsonArray("01JPRX00000000000000000022"),
            });
            process["transitions"]!.AsArray().Add(new JsonObject
            {
                ["id"] = "01JTRN0000000000000000P5D2",
                ["source"] = "01JSTA00000000000000000011",
                ["event"] = "01JPRX00000000000000000004",
                ["actions"] = new JsonArray("01JPRX00000000000000000022"),
            });
        });
        await repo.GenerateCleanlyAsync();

        var (path, text) = Assert.Single(DiagramsOf(repo));
        Assert.Equal("processes/order-lifecycle.md", path);
        var problems = DiagramText.Problems(text);
        Assert.True(problems.Count == 0, string.Join('\n', problems));
        Assert.Contains("            state \"Shipped\" as s_Fulfilment_Shipping_Shipped\n", text, StringComparison.Ordinal);
        Assert.Contains("            state \"Shipped\" as s_Fulfilment_Billing_Shipped\n", text, StringComparison.Ordinal);
        Assert.Contains("        state \"State\" as s_Review_State\n", text, StringComparison.Ordinal);
        Assert.Contains("        note right of Pending\n            internal: pay / notifyClerk\n        end note\n", text, StringComparison.Ordinal);
        Assert.Contains("    Decide --> s_Review_State : always [isLarge]\n", text, StringComparison.Ordinal);
        Assert.Matches(new Regex(@"\n        --\n        state Billing \{\n(?:            .*\n)*        \}\n        note right of Billing\n            internal: pay / notifyClerk\n        end note\n    \}\n"), text);
    }

    [Fact]
    public async Task The_diagrams_parameter_leaves_the_diagram_out()
    {
        using var repo = new DocsRepo("processes");
        repo.EditJson(".maquettiste/maquettiste.json", settings => settings["packs"]!["process-docs"]!["parameters"] = new JsonObject { ["diagrams"] = false });
        await repo.GenerateCleanlyAsync();
        Assert.Empty(DiagramsOf(repo));
        Assert.Contains("## Transitions", repo.Read("docs/processes/purchase-approval.md"), StringComparison.Ordinal);
    }

    [Fact]
    public void The_syntax_check_finds_broken_diagrams()
    {
        Assert.Empty(DiagramText.Problems("stateDiagram-v2\n    [*] --> A\n    A\n    state B {\n        [*] --> C\n        C\n    }\n    A --> B : go\n"));
        Assert.NotEmpty(DiagramText.Problems("stateDiagram-v2\n    state B {\n        C\n"));
        Assert.NotEmpty(DiagramText.Problems("stateDiagram-v2\n    A\n    }\n"));
        Assert.NotEmpty(DiagramText.Problems("stateDiagram-v2\n    A\n    A --> Z : go\n"));
        Assert.NotEmpty(DiagramText.Problems("stateDiagram-v2\n    A\n    A\n"));
        Assert.NotEmpty(DiagramText.Problems("stateDiagram-v2\n    --\n    A\n"));
        Assert.NotEmpty(DiagramText.Problems("stateDiagram-v2\n    A\n    A --> A : one; two\n"));
        Assert.NotEmpty(DiagramText.Problems("stateDiagram-v2\n    A\n    note right of A\n        x\n"));
        Assert.NotEmpty(DiagramText.Problems("stateDiagram\n    A\n"));
    }

    private static void Rename(JsonNode states, string id, string name)
    {
        foreach (var state in states.AsArray())
        {
            if ((string?)state!["id"] == id)
                state["name"] = name;
            if (state["states"] is { } children)
                Rename(children, id, name);
        }
    }

    /// <summary>The fenced diagram blocks of the generated pages, by page path under <c>docs/</c>.</summary>
    private static Dictionary<string, string> DiagramsOf(DocsRepo repo)
    {
        var diagrams = new Dictionary<string, string>(StringComparer.Ordinal);
        var root = repo.PathOf("docs");
        foreach (var file in Directory.EnumerateFiles(root, "*.md", SearchOption.AllDirectories).Order(StringComparer.Ordinal))
        {
            var text = File.ReadAllText(file);
            var start = text.IndexOf(DiagramFence, StringComparison.Ordinal);
            if (start < 0)
                continue;
            start += DiagramFence.Length;
            var end = text.IndexOf("\n```", start, StringComparison.Ordinal);
            Assert.True(end > start, file + ": the diagram block is not closed");
            Assert.Equal(-1, text.IndexOf(DiagramFence, end, StringComparison.Ordinal));
            diagrams[Path.GetRelativePath(root, file).Replace(Path.DirectorySeparatorChar, '/')] = text[start..(end + 1)];
        }

        return diagrams;
    }

    /// <summary>
    /// A small syntax check of the state diagram text the pack writes: the header line; every statement one of the forms the pack
    /// emits (a state, a quoted label as an id, a choice, a block opening or closing, a region separator inside a block, an edge,
    /// an edge from or to <c>[*]</c>, a note block); blocks balanced and notes closed; each id declared once (a quoted label may
    /// precede the block of the same id); every edge's and note's ends declared; one initial edge per block at most; and labels
    /// free of the characters that end a statement.
    /// </summary>
    internal static partial class DiagramText
    {
        public static IReadOnlyList<string> Problems(string text)
        {
            var problems = new List<string>();
            var lines = text.Split('\n');
            if (lines[0] != "stateDiagram-v2")
                problems.Add("the first line is not the diagram header");
            var declared = new Dictionary<string, string>(StringComparer.Ordinal);
            var referenced = new List<(int Line, string Id)>();
            var blocks = new Stack<(string Id, int Initials)>();
            var topInitials = 0;
            var inNote = false;
            for (var n = 1; n < lines.Length; n++)
            {
                var line = lines[n].Trim();
                if (line.Length == 0)
                    continue;
                if (inNote)
                {
                    if (line == "end note")
                        inNote = false;
                    else if (!Label(line))
                        problems.Add($"line {n + 1}: the note text holds a statement end");
                    continue;
                }

                Match m;
                if ((m = BlockOpen().Match(line)).Success)
                {
                    Declare(declared, m.Groups[1].Value, "block", n, problems);
                    blocks.Push((m.Groups[1].Value, 0));
                }
                else if (line == "}")
                {
                    if (blocks.Count == 0)
                        problems.Add($"line {n + 1}: a block closes that never opened");
                    else
                        blocks.Pop();
                }
                else if (line == "--")
                {
                    if (blocks.Count == 0)
                        problems.Add($"line {n + 1}: a region separator outside a block");
                }
                else if ((m = Choice().Match(line)).Success)
                    Declare(declared, m.Groups[1].Value, "state", n, problems);
                else if ((m = Labelled().Match(line)).Success)
                    Declare(declared, m.Groups[2].Value, "label", n, problems);
                else if ((m = Initial().Match(line)).Success)
                {
                    referenced.Add((n, m.Groups[1].Value));
                    if (blocks.Count == 0)
                        topInitials++;
                    else
                    {
                        var top = blocks.Pop();
                        blocks.Push((top.Id, top.Initials + 1));
                    }

                    if (topInitials > 1 || (blocks.Count > 0 && blocks.Peek().Initials > 1))
                        problems.Add($"line {n + 1}: a second initial edge in one block");
                }
                else if ((m = Final().Match(line)).Success)
                    referenced.Add((n, m.Groups[1].Value));
                else if ((m = Edge().Match(line)).Success)
                {
                    referenced.Add((n, m.Groups[1].Value));
                    referenced.Add((n, m.Groups[2].Value));
                    if (!Label(m.Groups[3].Value))
                        problems.Add($"line {n + 1}: the edge label holds a statement end");
                }
                else if ((m = Note().Match(line)).Success)
                {
                    referenced.Add((n, m.Groups[1].Value));
                    inNote = true;
                }
                else if (Id().IsMatch(line))
                    Declare(declared, line, "state", n, problems);
                else
                    problems.Add($"line {n + 1}: not a statement of the diagram: {line}");
            }

            if (blocks.Count > 0)
                problems.Add($"{blocks.Count} block(s) left open ({string.Join(", ", blocks.Select(b => b.Id))})");
            if (inNote)
                problems.Add("a note is left open");
            foreach (var (line, id) in referenced)
            {
                if (!declared.ContainsKey(id))
                    problems.Add($"line {line + 1}: '{id}' is not declared");
            }

            return problems;
        }

        private static void Declare(Dictionary<string, string> declared, string id, string how, int line, List<string> problems)
        {
            if (Reserved.Contains(id.ToLowerInvariant()))
                problems.Add($"line {line + 1}: '{id}' is a keyword of the diagram text");
            if (!declared.TryGetValue(id, out var before))
            {
                declared[id] = how;
                return;
            }

            // A quoted label names an id whose block follows; any other second declaration is a duplicate.
            if (before == "label" && how == "block")
                declared[id] = "block";
            else
                problems.Add($"line {line + 1}: '{id}' is declared twice");
        }

        // A label may hold entity codes (#35;) but no bare ';' or '#' and no double quote.
        private static bool Label(string text) => !BareEntity().IsMatch(text.Replace("\"", ";", StringComparison.Ordinal));

        private static readonly HashSet<string> Reserved =
        [
            "accdescr", "acctitle", "as", "class", "classdef", "click", "direction", "end", "hide", "href", "left", "note", "of", "right",
            "scale", "state", "style",
        ];

        [GeneratedRegex(@"^state ([A-Za-z_][A-Za-z0-9_]*) \{$")]
        private static partial Regex BlockOpen();

        [GeneratedRegex(@"^state ([A-Za-z_][A-Za-z0-9_]*) <<choice>>$")]
        private static partial Regex Choice();

        [GeneratedRegex("^state \"([^\"]+)\" as ([A-Za-z_][A-Za-z0-9_]*)$")]
        private static partial Regex Labelled();

        [GeneratedRegex(@"^\[\*\] --> ([A-Za-z_][A-Za-z0-9_]*)$")]
        private static partial Regex Initial();

        [GeneratedRegex(@"^([A-Za-z_][A-Za-z0-9_]*) --> \[\*\]$")]
        private static partial Regex Final();

        [GeneratedRegex(@"^([A-Za-z_][A-Za-z0-9_]*) --> ([A-Za-z_][A-Za-z0-9_]*) : (\S.*)$")]
        private static partial Regex Edge();

        [GeneratedRegex(@"^note right of ([A-Za-z_][A-Za-z0-9_]*)$")]
        private static partial Regex Note();

        [GeneratedRegex(@"^[A-Za-z_][A-Za-z0-9_]*$")]
        private static partial Regex Id();

        // A ';' that does not close an entity code, or a '#' that does not open one.
        [GeneratedRegex(@"(?<!#[A-Za-z0-9]+);|#(?![A-Za-z0-9]+;)")]
        private static partial Regex BareEntity();
    }

    /// <summary>A temporary repo holding one fixture model and the <c>process-docs</c> pack, writing to the committed root <c>docs</c>.</summary>
    private sealed class DocsRepo : IDisposable
    {
        public DocsRepo(string fixture)
        {
            Repo = new TempRepo();
            PackRepo.CopyTree(Fixtures.Path("models", fixture, ".maquettiste"), Repo.ModelRoot);
            PackRepo.CopyTree(Path.Combine(Fixtures.RepoRoot, "packs", "process-docs"), Path.Combine(Repo.ModelRoot, "templates", "process-docs"));
            // The gate 3 fixture registers the pack itself; another fixture gets the same registration here.
            EditJson(".maquettiste/maquettiste.json", settings =>
            {
                if (settings["packs"]?["process-docs"] is not null)
                    return;
                settings["outputs"] = JsonNode.Parse("""{ "allow": [ { "path": "docs", "commit": true } ] }""");
                settings["packs"] = JsonNode.Parse("""{ "process-docs": { "output": "docs" } }""");
            });
        }

        private TempRepo Repo { get; }

        public string PathOf(string path) => Repo.PathOf(path);

        public string Read(string path) => Repo.ReadFile(path);

        public void EditJson(string path, Action<JsonNode> edit)
        {
            var node = JsonNode.Parse(Repo.ReadFile(path))!;
            edit(node);
            Repo.WriteFile(path, node.ToJsonString(new System.Text.Json.JsonSerializerOptions { WriteIndented = true }) + "\n");
        }

        public async Task<GenerationResult> GenerateAsync(GenerationMode mode = GenerationMode.Apply, int? jobs = null)
        {
            await using var store = new ModelStore(Repo.Options);
            var service = new GenerationService(store, Repo.Options);
            var request = new GenerationRequest { Mode = mode, Packs = ["process-docs"], Jobs = jobs };
            return await service.RunAsync(request, progress: null, TestContext.Current.CancellationToken);
        }

        public async Task<GenerationResult> GenerateCleanlyAsync(int? jobs = null)
        {
            var result = await GenerateAsync(GenerationMode.Apply, jobs);
            var errors = result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
            Assert.True(result.Outcome == RunOutcome.Succeeded && errors.Count == 0, Describe(result));
            return result;
        }

        public static string Describe(GenerationResult result) => PackRepo.Describe(result);

        public void Dispose() => Repo.Dispose();
    }
}
