-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table sales.customers of database postgres (PostgreSQL).

CREATE TABLE sales.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) NOT NULL,
    code char(10) NOT NULL,
    name varchar(100) COLLATE "C" NOT NULL,
    email varchar(200) NOT NULL,
    notes text NULL,
    balance numeric(12,2) NOT NULL DEFAULT 0,
    status varchar(1) NOT NULL DEFAULT 'A',
    created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    balance_twice numeric(14,2) GENERATED ALWAYS AS (balance * 2) STORED,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_status CHECK (status IN ('A', 'I')),
    CONSTRAINT ck_customers_balance CHECK (balance >= 0)
);
CREATE INDEX ix_customers_name ON sales.customers (name, created_at DESC) INCLUDE (email);
CREATE INDEX ix_customers_active ON sales.customers (status) WHERE status = 'A';
CREATE UNIQUE INDEX ix_customers_code ON sales.customers USING btree (code);
CREATE INDEX ix_customers_email_lower ON sales.customers ((lower(email)));
COMMENT ON TABLE sales.customers IS 'Customers who place orders.';
COMMENT ON COLUMN sales.customers.notes IS 'Free-form notes.';
