-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table shop.order_items of database postgres (PostgreSQL).

CREATE TABLE shop.order_items (
    order_id bigint NOT NULL,
    line_no integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku char(20) NOT NULL,
    quantity bigint NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES shop.orders (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0)
);
CREATE INDEX ix_order_lines_product ON shop.order_items (sku);
