-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table dbo.customers of database reporting (SQL Server).
-- Maps entity Customer.

CREATE TABLE dbo.customers (
    id uniqueidentifier NOT NULL,
    name nvarchar(120) NOT NULL,
    email nvarchar(254) NOT NULL,
    customer_since date NULL,
    created_at datetimeoffset(6) NOT NULL,
    updated_at datetimeoffset(6) NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uq_customers_email UNIQUE (email)
);
