-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table dbo.invoice_notes of database reporting (SQL Server).
-- Maps entity InvoiceNote.

CREATE TABLE dbo.invoice_notes (
    id uniqueidentifier NOT NULL,
    invoice_id uniqueidentifier NOT NULL,
    body nvarchar(max) NOT NULL,
    created_at datetimeoffset(6) NULL,
    CONSTRAINT pk_invoice_notes PRIMARY KEY (id)
);
EXEC sys.sp_addextendedproperty @name = N'MS_Description', @value = N'A note on an invoice. Stored in the shared notes table with entity_type ''invoice''.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'invoice_notes';
