-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table dbo.invoices of database reporting (SQL Server).
-- Maps entity Invoice.

CREATE TABLE dbo.invoices (
    id uniqueidentifier NOT NULL,
    number nvarchar(32) NOT NULL,
    issued_on date NOT NULL,
    total_amount decimal(18,2) NULL,
    total_currency nvarchar(3) NULL,
    status int NOT NULL CONSTRAINT df_invoices_status DEFAULT 0,
    notes nvarchar(max) NULL,
    created_at datetimeoffset(6) NOT NULL,
    updated_at datetimeoffset(6) NULL,
    deleted_at datetimeoffset(6) NULL,
    reason nvarchar(200) NULL,
    discriminator nvarchar(64) NOT NULL,
    customer_id uniqueidentifier NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id),
    CONSTRAINT uq_invoices_number UNIQUE (number),
    CONSTRAINT fk_invoices_customer_id FOREIGN KEY (customer_id) REFERENCES dbo.customers (id)
);
CREATE INDEX ix_invoices_issued_on ON dbo.invoices (issued_on);
BEGIN DECLARE @mq_rc1 int; EXEC @mq_rc1 = sys.sp_addextendedproperty @name = N'MS_Description', @value = N'# Invoice

A bill issued to a customer. Its number is assigned when it is issued and never reused.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'invoices'; IF @mq_rc1 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
