-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table dbo.invoice_lines of database reporting (SQL Server).
-- Maps entity InvoiceLine.

CREATE TABLE dbo.invoice_lines (
    id char(26) NOT NULL,
    quantity int NOT NULL,
    unit_price_amount decimal(18,2) NOT NULL,
    unit_price_currency nvarchar(3) NOT NULL,
    description nvarchar(500) NULL,
    invoice_id uniqueidentifier NOT NULL,
    product_id uniqueidentifier NOT NULL,
    CONSTRAINT pk_invoice_lines PRIMARY KEY (id),
    CONSTRAINT fk_invoice_lines_invoice_id FOREIGN KEY (invoice_id) REFERENCES dbo.invoices (id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_lines_product_id FOREIGN KEY (product_id) REFERENCES dbo.products (id)
);
