-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table dbo.payment_invoice of database reporting (SQL Server).
-- Junction table.

CREATE TABLE dbo.payment_invoice (
    payments_id bigint NOT NULL,
    invoices_id uniqueidentifier NOT NULL,
    allocated_amount decimal(18,2) NOT NULL,
    allocated_currency nvarchar(3) NOT NULL,
    CONSTRAINT pk_payment_invoice PRIMARY KEY (payments_id, invoices_id),
    CONSTRAINT fk_payment_invoice_payments_id FOREIGN KEY (payments_id) REFERENCES dbo.payments (id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_invoice_invoices_id FOREIGN KEY (invoices_id) REFERENCES dbo.invoices (id) ON DELETE CASCADE
);
