-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table dbo.revenue_months of database reporting (SQL Server).
-- Maps entity RevenueMonth.

CREATE TABLE dbo.revenue_months (
    month date NOT NULL,
    invoice_count bigint NOT NULL,
    revenue decimal(18,2) NOT NULL,
    CONSTRAINT pk_revenue_months PRIMARY KEY (month)
);
EXEC sys.sp_addextendedproperty @name = N'MS_Description', @value = N'Invoiced revenue per month, read through the RevenueByMonth query; read-only.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'revenue_months';
