using System.Text.Json;
using Maquettiste.Cli.Commands;
using Maquettiste.Engine.Json;
using Maquettiste.Testing;

namespace Maquettiste.Cli.Tests;

public sealed class InitTests
{
    [Fact]
    public async Task Init_creates_the_layout_settings_schemas_starter_pack_and_gitignore_block()
    {
        using var repo = CliRepo.Empty();
        var result = await repo.RunAsync("init");
        Assert.Equal(0, result.ExitCode);
        Assert.Equal("", result.Out);

        foreach (var folder in InitCommand.Folders.Where(f => f != "templates"))
            Assert.True(File.Exists(repo.PathOf(".maquettiste/" + folder + "/.gitkeep")), folder);

        // Settings: canonical format 1 with the two default roots and the starter pack's output folder.
        var settings = repo.Read(".maquettiste/maquettiste.json");
        Assert.True(TestServices.Json.IsCanonical(Text.Utf8(settings), "maquettiste.json", "maquettiste.json"), settings);
        using (var doc = JsonDocument.Parse(settings))
        {
            var root = doc.RootElement;
            Assert.Equal(".schema/v1/maquettiste.json", root.GetProperty("$schema").GetString());
            Assert.Equal(1, root.GetProperty("formatVersion").GetInt32());
            var allow = root.GetProperty("outputs").GetProperty("allow").EnumerateArray().ToList();
            Assert.Equal("db", allow[0].GetProperty("path").GetString());
            Assert.True(allow[0].GetProperty("commit").GetBoolean());
            Assert.Equal("src/Generated", allow[1].GetProperty("path").GetString());
            Assert.False(allow[1].TryGetProperty("commit", out _));
            Assert.Equal("db", root.GetProperty("packs").GetProperty("sql-ddl").GetProperty("output").GetString());
        }

        // Every embedded schema, byte for byte.
        foreach (var name in TestServices.Schemas.FileNames)
            Assert.Equal(TestServices.Schemas.GetFileBytes(name).ToArray(), File.ReadAllBytes(repo.PathOf(".maquettiste/.schema/v1/" + name)));
        Assert.Equal(TestServices.Schemas.FileNames.Count, Directory.GetFiles(repo.PathOf(".maquettiste/.schema/v1")).Length);

        Assert.True(File.Exists(repo.PathOf(".maquettiste/templates/sql-ddl/pack.json")));
        Assert.False(File.Exists(repo.PathOf(".maquettiste/templates/.gitkeep")));

        var gitignore = repo.Read(".gitignore");
        Assert.Equal("# maquettiste:begin\n# Built output roots and the run journal; regenerated by maquettiste generate.\n/src/Generated/\n/.maquettiste/.cache/\n# maquettiste:end\n", gitignore);

        // The fresh repo validates cleanly.
        var validate = await repo.RunAsync("validate");
        Assert.Equal(0, validate.ExitCode);
    }

    [Fact]
    public async Task Init_is_idempotent_keeps_existing_files_and_refreshes_schemas()
    {
        using var repo = CliRepo.Empty();
        Directory.CreateDirectory(repo.RepoRoot);
        repo.Write(".gitignore", "bin/\nobj/\n");
        Assert.Equal(0, (await repo.RunAsync("init")).ExitCode);

        // Hand changes: settings with another built root, a pack template edit, a stale schema, a foreign schema file.
        repo.Replace(".maquettiste/maquettiste.json", "\"path\": \"src/Generated\"", "\"path\": \"gen/out\"");
        repo.Write(".maquettiste/templates/sql-ddl/table.scriban", "custom\n");
        repo.Write(".maquettiste/.schema/v1/entity.json", "{}\n");
        repo.Write(".maquettiste/.schema/v1/retired.json", "{}\n");
        repo.Write(".gitignore", repo.Read(".gitignore") + "*.log\n");

        var again = await repo.RunAsync("init");
        Assert.Equal(0, again.ExitCode);
        Assert.Contains("\"path\": \"gen/out\"", repo.Read(".maquettiste/maquettiste.json"), StringComparison.Ordinal);
        Assert.Equal("custom\n", repo.Read(".maquettiste/templates/sql-ddl/table.scriban"));
        Assert.Equal(TestServices.Schemas.GetFileBytes("entity.json").ToArray(), File.ReadAllBytes(repo.PathOf(".maquettiste/.schema/v1/entity.json")));
        Assert.False(File.Exists(repo.PathOf(".maquettiste/.schema/v1/retired.json")));

        // The block is rewritten in place from the current settings; the other lines stay.
        Assert.Equal(
            "bin/\nobj/\n\n# maquettiste:begin\n# Built output roots and the run journal; regenerated by maquettiste generate.\n/gen/out/\n/.maquettiste/.cache/\n# maquettiste:end\n*.log\n",
            repo.Read(".gitignore"));

        var third = await repo.RunAsync("init");
        Assert.Equal(0, third.ExitCode);
        Assert.Equal(1, repo.Read(".gitignore").Split("# maquettiste:begin").Length - 1);
    }

    [Theory]
    [InlineData("none")]
    [InlineData("csharp-dapper")]
    public async Task Init_pack_option_chooses_the_starter_pack(string pack)
    {
        using var repo = CliRepo.Empty();
        var result = await repo.RunAsync("init", "--pack", pack);
        Assert.Equal(0, result.ExitCode);
        var templates = Directory.GetDirectories(repo.PathOf(".maquettiste/templates")).Select(Path.GetFileName).ToList();
        if (pack == "none")
        {
            Assert.Empty(templates);
            Assert.DoesNotContain("\"packs\"", repo.Read(".maquettiste/maquettiste.json"), StringComparison.Ordinal);
        }
        else
        {
            Assert.Equal([pack], templates);
            Assert.Contains("\"output\": \"src/Generated\"", repo.Read(".maquettiste/maquettiste.json"), StringComparison.Ordinal);
        }
    }

    [Theory]
    [InlineData("sql-ddl", "db")]
    [InlineData("csharp-dapper", "src/Generated")]
    public async Task The_starter_packs_generate_the_billing_model_cleanly(string pack, string root)
    {
        using var repo = CliRepo.Empty();
        Assert.Equal(0, (await repo.RunAsync("init", "--pack", pack)).ExitCode);
        CliRepo.CopyTree(Fixtures.Path("models", "billing", ".maquettiste", "model"), repo.PathOf(".maquettiste/model"));

        var result = await repo.RunAsync("generate");
        Assert.True(result.ExitCode == 0, result.ToString());
        Assert.NotEmpty(repo.Tree(root));
        Assert.DoesNotContain(": warning ", result.Error, StringComparison.Ordinal);
        Assert.DoesNotContain(": error ", result.Error, StringComparison.Ordinal);
    }

    [Fact]
    public async Task The_csharp_dapper_starter_output_compiles_with_nullable_and_warnings_as_errors()
    {
        using var repo = CliRepo.Empty();
        Assert.Equal(0, (await repo.RunAsync("init", "--pack", "csharp-dapper")).ExitCode);
        CliRepo.CopyTree(Fixtures.Path("models", "billing", ".maquettiste", "model"), repo.PathOf(".maquettiste/model"));
        var result = await repo.RunAsync("generate");
        Assert.True(result.ExitCode == 0, result.ToString());

        // The billing model's entities use an enum (InvoiceStatus) and a value object (Money): both must be generated too.
        var tree = repo.Tree("src/Generated");
        Assert.Contains("Billing/InvoiceStatus.g.cs", tree.Keys);
        Assert.Contains("Billing/Money.g.cs", tree.Keys);

        // Compile the generated folder as a net10.0 library (Nullable, ImplicitUsings, TreatWarningsAsErrors) with the SDK's compiler.
        var project = repo.PathOf("compile-check");
        CliRepo.CopyTree(repo.PathOf("src/Generated"), project);
        await File.WriteAllTextAsync(Path.Combine(project, "Check.csproj"), """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
                <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
              </PropertyGroup>
              <ItemGroup>
                <!-- The embedded csharp-dapper pack generates Dapper repositories and type handlers. -->
                <PackageReference Include="Dapper" Version="2.1.66" />
              </ItemGroup>
            </Project>
            """, TestContext.Current.CancellationToken);
        var (code, output) = await DotnetAsync(project, "build", "-nologo", "-nodeReuse:false", "-p:UseSharedCompilation=false", "-clp:NoSummary");
        Assert.True(code == 0, output);
        Assert.DoesNotContain(": error ", output, StringComparison.Ordinal);
        Assert.DoesNotContain(": warning ", output, StringComparison.Ordinal);
    }

    private static async Task<(int Code, string Output)> DotnetAsync(string cwd, params string[] args)
    {
        var host = Environment.ProcessPath is { } p && Path.GetFileNameWithoutExtension(p) == "dotnet" ? p : "dotnet";
        var start = new System.Diagnostics.ProcessStartInfo(host)
        {
            WorkingDirectory = cwd,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        foreach (var arg in args)
            start.ArgumentList.Add(arg);
        // The test host's MSBuild settings would point the child build at this repo's build; it gets a clean environment instead.
        foreach (var name in start.Environment.Keys.Where(k => k.StartsWith("MSBUILD", StringComparison.OrdinalIgnoreCase) || k.StartsWith("VSTEST", StringComparison.OrdinalIgnoreCase)).ToList())
            start.Environment.Remove(name);
        start.Environment["DOTNET_CLI_TELEMETRY_OPTOUT"] = "1";
        start.Environment["DOTNET_NOLOGO"] = "1";
        using var cts = CancellationTokenSource.CreateLinkedTokenSource(TestContext.Current.CancellationToken);
        cts.CancelAfter(TimeSpan.FromMinutes(3));
        using var process = System.Diagnostics.Process.Start(start)!;
        var stdout = process.StandardOutput.ReadToEndAsync(cts.Token);
        var stderr = process.StandardError.ReadToEndAsync(cts.Token);
        await process.WaitForExitAsync(cts.Token);
        return (process.ExitCode, await stdout + await stderr);
    }

    [Theory]
    [InlineData("sql-ddl")]
    [InlineData("csharp-dapper")]
    public void Every_file_of_an_example_pack_folder_is_embedded(string pack)
    {
        var folder = Path.Combine(Fixtures.RepoRoot, "packs", pack);
        var onDisk = Directory.Exists(folder)
            ? Directory.EnumerateFiles(folder, "*", SearchOption.AllDirectories).Select(f => Path.GetRelativePath(folder, f).Replace('\\', '/')).Order(StringComparer.Ordinal).ToList()
            : [];
        var files = StarterPacks.Files(pack, out var embedded);
        Assert.Equal(onDisk.Count > 0, embedded);
        if (embedded)
            Assert.Equal(onDisk, files.Select(f => f.Key).ToList());
    }

    [Fact]
    public async Task Init_with_another_starter_pack_adds_its_output_entry_to_the_kept_settings()
    {
        using var repo = CliRepo.Empty();
        Assert.Equal(0, (await repo.RunAsync("init")).ExitCode);
        var second = await repo.RunAsync("init", "--pack", "csharp-dapper");
        Assert.True(second.ExitCode == 0, second.ToString());
        Assert.Contains("added packs.csharp-dapper.output", second.Error + second.Out, StringComparison.Ordinal);

        using var settings = JsonDocument.Parse(repo.Read(".maquettiste/maquettiste.json"));
        var packs = settings.RootElement.GetProperty("packs");
        Assert.Equal("db", packs.GetProperty("sql-ddl").GetProperty("output").GetString());
        Assert.Equal("src/Generated", packs.GetProperty("csharp-dapper").GetProperty("output").GetString());

        CliRepo.CopyTree(Fixtures.Path("models", "billing", ".maquettiste", "model"), repo.PathOf(".maquettiste/model"));
        var generate = await repo.RunAsync("generate");
        Assert.True(generate.ExitCode == 0, generate.ToString());
        Assert.NotEmpty(repo.Tree("src/Generated"));

        // A third run changes nothing.
        var before = repo.Read(".maquettiste/maquettiste.json");
        Assert.Equal(0, (await repo.RunAsync("init", "--pack", "csharp-dapper")).ExitCode);
        Assert.Equal(before, repo.Read(".maquettiste/maquettiste.json"));
    }

    [Fact]
    public async Task Init_refuses_a_gitignore_with_a_dangling_begin_marker_and_keeps_the_user_lines()
    {
        using var repo = CliRepo.Empty();
        const string text = "a\n# maquettiste:begin\nsecrets.env\nbar/\n";
        repo.Write(".gitignore", text);
        for (var i = 0; i < 2; i++)
        {
            var result = await repo.RunAsync("init", "--pack", "none");
            Assert.Equal(4, result.ExitCode);
            Assert.Contains(".gitignore line 2: '# maquettiste:begin' has no matching '# maquettiste:end'", result.Error, StringComparison.Ordinal);
            Assert.Equal(text, repo.Read(".gitignore"));
        }

        Assert.False(File.Exists(repo.PathOf(".maquettiste/maquettiste.json")));
    }

    [Fact]
    public async Task Init_hooks_installs_executable_post_checkout_and_post_merge_hooks()
    {
        using var repo = CliRepo.Empty();
        Directory.CreateDirectory(repo.PathOf(".git/hooks"));
        var result = await repo.RunAsync("init", "--hooks");
        Assert.Equal(0, result.ExitCode);
        foreach (var hook in new[] { "post-checkout", "post-merge" })
        {
            var path = repo.PathOf(".git/hooks/" + hook);
            var text = File.ReadAllText(path);
            Assert.StartsWith("#!/bin/sh\n", text, StringComparison.Ordinal);
            Assert.Contains("generate --roots built --quiet", text, StringComparison.Ordinal);
            Assert.DoesNotContain('\r', text);
            if (!OperatingSystem.IsWindows())
                Assert.True(File.GetUnixFileMode(path).HasFlag(UnixFileMode.UserExecute));
        }

        // A foreign hook is kept; our own is rewritten.
        repo.Write(".git/hooks/post-merge", "#!/bin/sh\necho mine\n");
        var again = await repo.RunAsync("init", "--hooks");
        Assert.Equal(0, again.ExitCode);
        Assert.Equal("#!/bin/sh\necho mine\n", repo.Read(".git/hooks/post-merge"));
        Assert.Contains("kept .git/hooks/post-merge", again.Error, StringComparison.Ordinal);
    }

    [Fact]
    public async Task Init_hooks_without_a_git_folder_skips_the_hooks()
    {
        using var repo = CliRepo.Empty();
        var result = await repo.RunAsync("init", "--hooks");
        Assert.Equal(0, result.ExitCode);
        Assert.Contains("skipped --hooks", result.Error, StringComparison.Ordinal);
        Assert.False(Directory.Exists(repo.PathOf(".git")));
    }

    [Fact]
    public async Task Init_refuses_a_missing_repo_folder()
    {
        using var repo = CliRepo.Empty();
        var result = await repo.RunAsync("init", "--repo", repo.PathOf("missing"));
        Assert.Equal(4, result.ExitCode);
    }

    [Fact]
    public async Task Init_refuses_a_gitignore_that_is_a_link_out_of_the_repo()
    {
        if (OperatingSystem.IsWindows())
            return;
        using var repo = CliRepo.Empty();
        Directory.CreateDirectory(repo.RepoRoot);
        var outside = Path.Combine(repo.Temp.Root, "outside.txt");
        File.WriteAllText(outside, "x\n");
        File.CreateSymbolicLink(repo.PathOf(".gitignore"), outside);
        var result = await repo.RunAsync("init");
        Assert.Equal(4, result.ExitCode);
        Assert.Contains("MQ6004", result.Error, StringComparison.Ordinal);
        Assert.Equal("x\n", File.ReadAllText(outside));
    }

    [Fact]
    public void Gitignore_block_is_replaced_in_place()
    {
        var text = InitCommand.WithBlock("a\n# maquettiste:begin\nold\n# maquettiste:end\nb\n", ["x", "/y/"]);
        Assert.Equal("a\n# maquettiste:begin\n# Built output roots and the run journal; regenerated by maquettiste generate.\n/x/\n/y/\n/.maquettiste/.cache/\n# maquettiste:end\nb\n", text);
        Assert.Equal(text, InitCommand.WithBlock(text, ["x", "/y/"]));
        Assert.StartsWith("# maquettiste:begin\n", InitCommand.WithBlock(null, []), StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("a\n# maquettiste:begin\nsecrets.env\nbar/\n", "line 2: '# maquettiste:begin' has no matching")]
    [InlineData("a\n# maquettiste:end\nsecrets.env\n", "line 2: '# maquettiste:end' has no matching")]
    [InlineData("# maquettiste:end\nsecrets.env\n# maquettiste:begin\n", "line 1: '# maquettiste:end' has no matching")]
    [InlineData("# maquettiste:begin\nx\n# maquettiste:begin\ny\n# maquettiste:end\n", "line 3: '# maquettiste:begin' has no matching")]
    [InlineData("# maquettiste:begin\nx\n# maquettiste:end\ny\n# maquettiste:end\n", "line 5: '# maquettiste:end' has no matching")]
    public void Gitignore_block_with_malformed_markers_is_refused(string existing, string message)
    {
        // Run twice, as a second init would: the first refusal must not leave a state that the second run "repairs" by deleting lines.
        for (var i = 0; i < 2; i++)
        {
            var e = Assert.Throws<UsageException>(() => InitCommand.WithBlock(existing, ["x"]));
            Assert.Contains(message, e.Message, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void Embedded_schema_registry_is_what_init_writes() =>
        Assert.Contains("maquettiste.json", new SchemaRegistry().FileNames);
}
