using System.Text;
using Maquettiste.Cli.Commands;
using Maquettiste.Cli.Mcp;
using Maquettiste.Engine;
using Maquettiste.Testing;
using ModelContextProtocol.Protocol;

namespace Maquettiste.Cli.Tests;

/// <summary>
/// <c>init --skill</c> owns <c>SKILL.md</c> and nothing else in its folder: an untouched copy of any release is refreshed, a copy
/// edited by hand is left alone (the new version goes to <c>SKILL.md.new</c>) unless <c>--force</c>, <c>--check</c> reports drift, and
/// the repository's <c>CONVENTIONS.md</c> survives and ends the MCP conventions.
/// </summary>
public sealed class SkillRefreshTests
{
    private const string NewPath = AgentSetup.SkillPath + ".new";

    private const string Conventions = "# Our conventions\n\n- Every entity has an `audit` stereotype.\n";

    private const string Section = "\n## This repository's conventions\n\n- Tables are named in the singular.\n- Every entity has an owner.\n";

    /// <summary>The skill source of this repository, LF line endings.</summary>
    private static string Source()
    {
        var text = File.ReadAllText(Path.Combine(Fixtures.RepoRoot, "skills", "maquettiste-modeling", "SKILL.md"));
        return text.Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    /// <summary>The skill this build writes.</summary>
    internal static string CurrentSkill() => AgentSetup.WithHeader(Source(), EngineVersion.Product);

    /// <summary>The bytes <c>init --skill</c> of 0.5.3 and 0.5.4 wrote.</summary>
    private static string Skill054() =>
        File.ReadAllText(Fixtures.Path("skills", "maquettiste-modeling-0.5.4.md")).Replace("\r\n", "\n", StringComparison.Ordinal);

    private static async Task<CliRepo> InitializedAsync()
    {
        var repo = CliRepo.Empty();
        Assert.Equal(0, (await repo.RunAsync("init")).ExitCode);
        return repo;
    }

    [Fact]
    public async Task The_written_skill_starts_with_a_header_that_explains_who_owns_it_and_a_second_run_keeps_it()
    {
        using var repo = CliRepo.Empty();
        var first = await repo.RunAsync("init", "--skill");
        Assert.Equal(0, first.ExitCode);
        Assert.Contains("created " + AgentSetup.SkillPath, first.Error, StringComparison.Ordinal);
        var written = repo.Read(AgentSetup.SkillPath);
        Assert.Equal(CurrentSkill(), written);

        // Front matter, then the marker comment and the paragraph, then the source's body.
        var lines = written.Split('\n');
        Assert.Equal(["---", "name: maquettiste-modeling"], lines[..2]);
        var close = Array.IndexOf(lines, "---", 1);
        Assert.Equal("", lines[close + 1]);
        Assert.Matches("^<!-- maquettiste-skill: version=" + System.Text.RegularExpressions.Regex.Escape(EngineVersion.Product) + "; sha256=[0-9a-f]{64} -->$", lines[close + 2]);
        var paragraph = string.Join(' ', lines[(close + 3)..(close + 7)]);
        Assert.StartsWith($"This file is generated by maquettiste {EngineVersion.Product} and rewritten by `maquettiste init --skill`. Do not edit it:", paragraph, StringComparison.Ordinal);
        Assert.Contains("`CONVENTIONS.md` next to this file; `init --skill` never touches that file,", paragraph, StringComparison.Ordinal);
        Assert.Contains("`SKILL.md.new` (`--force` overwrites)", paragraph, StringComparison.Ordinal);
        Assert.Equal("", lines[close + 7]);
        Assert.Equal("# Modeling with Maquettiste", lines[close + 8]);

        // The body ends by sending the agent to CONVENTIONS.md.
        var tail = written[written.LastIndexOf("\n## ", StringComparison.Ordinal)..];
        Assert.StartsWith("\n## This repository's conventions\n", tail, StringComparison.Ordinal);
        Assert.Contains("`CONVENTIONS.md`, in the same folder as this file", tail, StringComparison.Ordinal);
        Assert.Contains("where the two\ndisagree, it wins", tail, StringComparison.Ordinal);

        // Idempotent: the second run keeps the file and writes nothing beside it.
        var second = await repo.RunAsync("init", "--skill");
        Assert.Equal(0, second.ExitCode);
        Assert.Contains("kept " + AgentSetup.SkillPath + " (current)", second.Error, StringComparison.Ordinal);
        Assert.Equal(written, repo.Read(AgentSetup.SkillPath));
        Assert.Equal(["SKILL.md"], repo.Tree(".claude/skills/maquettiste-modeling").Keys);
    }

    [Fact]
    public async Task A_pristine_0_5_4_skill_is_upgraded_and_nothing_else_is_touched()
    {
        using var repo = await InitializedAsync();
        repo.Write(AgentSetup.SkillPath, Skill054());
        repo.Write(AgentSetup.ConventionsPath, Conventions);
        var before = repo.Tree(".");

        var result = await repo.RunAsync("init", "--skill");
        Assert.Equal(0, result.ExitCode);
        Assert.Contains($"updated {AgentSetup.SkillPath} (from the 0.5.3 or 0.5.4 version to {EngineVersion.Product})", result.Error, StringComparison.Ordinal);
        Assert.Equal(CurrentSkill(), repo.Read(AgentSetup.SkillPath));

        var after = repo.Tree(".");
        Assert.Equal(before.Keys.Order(StringComparer.Ordinal), after.Keys.Order(StringComparer.Ordinal));
        Assert.All(before.Where(f => f.Key != AgentSetup.SkillPath), f => Assert.Equal(f.Value, after[f.Key]));
        Assert.Equal(Conventions, repo.Read(AgentSetup.ConventionsPath));
    }

    [Fact]
    public async Task The_customer_repro_a_section_appended_to_the_0_5_4_skill_is_kept_and_the_new_version_goes_beside_it()
    {
        using var repo = await InitializedAsync();
        var edited = Skill054() + Section;
        repo.Write(AgentSetup.SkillPath, edited);

        var result = await repo.RunAsync("init", "--skill");
        Assert.Equal(0, result.ExitCode);
        Assert.Contains(
            "skill not updated: .claude/skills/maquettiste-modeling/SKILL.md was edited by hand; the new version is in SKILL.md.new "
            + "(diff them, move your additions to CONVENTIONS.md, then run init --skill --force)", result.Error, StringComparison.Ordinal);
        Assert.Equal(edited, repo.Read(AgentSetup.SkillPath));
        Assert.Equal(CurrentSkill(), repo.Read(NewPath));

        // Again: still nothing written to SKILL.md.
        var again = await repo.RunAsync("init", "--skill");
        Assert.Equal(0, again.ExitCode);
        Assert.Contains("skill not updated:", again.Error, StringComparison.Ordinal);
        Assert.Equal(edited, repo.Read(AgentSetup.SkillPath));

        // The customer moves the section to CONVENTIONS.md and forces the refresh, which also removes SKILL.md.new.
        repo.Write(AgentSetup.ConventionsPath, Section.TrimStart('\n'));
        var forced = await repo.RunAsync("init", "--skill", "--force");
        Assert.Equal(0, forced.ExitCode);
        Assert.Contains($"replaced {AgentSetup.SkillPath}, which was edited by hand (--force)", forced.Error, StringComparison.Ordinal);
        Assert.Contains("removed " + NewPath, forced.Error, StringComparison.Ordinal);
        Assert.Equal(CurrentSkill(), repo.Read(AgentSetup.SkillPath));
        Assert.False(File.Exists(repo.PathOf(NewPath)));
        Assert.Equal(Section.TrimStart('\n'), repo.Read(AgentSetup.ConventionsPath));
    }

    [Fact]
    public async Task An_edited_copy_with_a_header_is_left_alone_and_a_leftover_new_file_goes_once_the_skill_is_current()
    {
        using var repo = await InitializedAsync();
        Assert.Equal(0, (await repo.RunAsync("init", "--skill")).ExitCode);
        var edited = repo.Read(AgentSetup.SkillPath).Replace("# Modeling with Maquettiste", "# Modeling with Maquettiste here", StringComparison.Ordinal);
        repo.Write(AgentSetup.SkillPath, edited);
        Assert.Contains("skill not updated:", (await repo.RunAsync("init", "--skill")).Error, StringComparison.Ordinal);
        Assert.Equal(edited, repo.Read(AgentSetup.SkillPath));
        Assert.True(File.Exists(repo.PathOf(NewPath)));

        // Putting the current file back by hand: the next run finds it current and removes the leftover SKILL.md.new.
        repo.Write(AgentSetup.SkillPath, CurrentSkill());
        var result = await repo.RunAsync("init", "--skill");
        Assert.Contains("kept " + AgentSetup.SkillPath + " (current)", result.Error, StringComparison.Ordinal);
        Assert.Contains("removed " + NewPath, result.Error, StringComparison.Ordinal);
        Assert.False(File.Exists(repo.PathOf(NewPath)));

        // A SKILL.md.new someone edited is kept.
        repo.Write(NewPath, "notes\n");
        var kept = await repo.RunAsync("init", "--skill");
        Assert.Contains($"kept {NewPath}: it was edited", kept.Error, StringComparison.Ordinal);
        Assert.Equal("notes\n", repo.Read(NewPath));
    }

    [Fact]
    public async Task Check_exits_2_when_the_skill_is_missing_stale_or_edited_and_0_when_current_and_writes_nothing()
    {
        using var repo = CliRepo.Empty();
        var missing = await repo.RunAsync("init", "--skill", "--check");
        Assert.Equal(2, missing.ExitCode);
        Assert.Equal($"skill missing: {AgentSetup.SkillPath} (run maquettiste init --skill)\n", missing.Out);
        Assert.False(Directory.Exists(repo.PathOf(".maquettiste")));
        Assert.False(Directory.Exists(repo.PathOf(".claude")));

        repo.Write(AgentSetup.SkillPath, Skill054());
        var stale = await repo.RunAsync("init", "--skill", "--check");
        Assert.Equal(2, stale.ExitCode);
        Assert.Equal($"skill stale: {AgentSetup.SkillPath} is the 0.5.3 or 0.5.4 version, not {EngineVersion.Product} (run maquettiste init --skill)\n", stale.Out);
        Assert.Equal(Skill054(), repo.Read(AgentSetup.SkillPath));

        repo.Write(AgentSetup.SkillPath, Skill054() + Section);
        var edited = await repo.RunAsync("init", "--skill", "--check");
        Assert.Equal(2, edited.ExitCode);
        Assert.StartsWith($"skill edited: {AgentSetup.SkillPath} was edited by hand", edited.Out, StringComparison.Ordinal);
        Assert.False(File.Exists(repo.PathOf(NewPath)));

        repo.Write(AgentSetup.SkillPath, CurrentSkill());
        var current = await repo.RunAsync("init", "--skill", "--check");
        Assert.Equal(0, current.ExitCode);
        Assert.Equal($"skill current: {AgentSetup.SkillPath} (maquettiste {EngineVersion.Product})\n", current.Out);
        Assert.False(Directory.Exists(repo.PathOf(".maquettiste")));

        Assert.Equal(4, (await repo.RunAsync("init", "--check")).ExitCode);
        Assert.Equal(4, (await repo.RunAsync("init", "--skill", "--check", "--mcp")).ExitCode);
        Assert.Equal(4, (await repo.RunAsync("init", "--mcp", "--force")).ExitCode);
    }

    [Fact]
    public void Classify_recognizes_every_shipped_release_a_headed_copy_of_another_release_and_a_checkout_with_crlf()
    {
        var current = new UTF8Encoding(false).GetBytes(CurrentSkill());
        Assert.Equal(AgentSetup.SkillState.Missing, AgentSetup.Classify(null, current, out _));
        Assert.Equal(AgentSetup.SkillState.Current, AgentSetup.Classify(Encoding.UTF8.GetBytes(CurrentSkill().Replace("\n", "\r\n", StringComparison.Ordinal)), current, out _));

        // An untouched copy that a later release wrote with its header is refreshed too (a downgrade, or a release the table lacks).
        var other = AgentSetup.WithHeader(Source(), "9.9.9");
        Assert.Equal(AgentSetup.SkillState.Shipped, AgentSetup.Classify(Encoding.UTF8.GetBytes(other), current, out var version));
        Assert.Equal("9.9.9", version);
        Assert.Equal(AgentSetup.SkillState.Edited, AgentSetup.Classify(Encoding.UTF8.GetBytes(other.Replace("9.9.9 and", "9.9.8 and", StringComparison.Ordinal)), current, out _));
        Assert.Equal(AgentSetup.SkillState.Edited, AgentSetup.Classify(Encoding.UTF8.GetBytes(other + "\nmore\n"), current, out _));

        // The table: every release from 0.1.0, 0.5.3 and 0.5.4 with the same bytes.
        Assert.Equal(AgentSetup.SkillState.Shipped, AgentSetup.Classify(Encoding.UTF8.GetBytes(Skill054()), current, out version));
        Assert.Equal("0.5.3 or 0.5.4", version);
        Assert.Contains(ShippedSkills.Releases, r => r.Version == "0.1.0");
        Assert.Contains(ShippedSkills.Releases, r => r == ("0.5.5", "590ab6d0678eaee1a7b141e31c28850f3ba918f1659d188de6064ababeaa362f"));
        Assert.All(ShippedSkills.Releases, r => Assert.Matches("^[0-9a-f]{64}$", r.Sha256));
    }

    [Fact]
    public async Task Conventions_md_ends_the_conventions_resource_and_prompt_and_is_read_on_each_request()
    {
        var ct = TestContext.Current.CancellationToken;
        using var repo = CliRepo.Billing();
        await using var session = await McpSession.StartAsync(repo, ct);
        var embedded = McpServerSetup.ReadConventions();

        // Without the file, the embedded text alone.
        Assert.Equal(embedded, await ResourceAsync(session, ct));

        repo.Write(AgentSetup.ConventionsPath, Conventions.Replace("\n", "\r\n", StringComparison.Ordinal));
        var expected = embedded.TrimEnd('\n') + "\n\n---\n\n# This repository's conventions (CONVENTIONS.md)\n\n" + Conventions;
        var text = await ResourceAsync(session, ct);
        Assert.Equal(expected, text);
        Assert.EndsWith("- Every entity has an `audit` stereotype.\n", text, StringComparison.Ordinal);
        var prompt = await session.Client.GetPromptAsync("modeling-conventions", cancellationToken: ct);
        Assert.Equal(expected, Assert.IsType<TextContentBlock>(Assert.Single(prompt.Messages).Content).Text);

        // Changed while the server runs: the next read sees it.
        repo.Write(AgentSetup.ConventionsPath, "Use singular names.\n");
        Assert.EndsWith("# This repository's conventions (CONVENTIONS.md)\n\nUse singular names.\n", await ResourceAsync(session, ct), StringComparison.Ordinal);
    }

    [Fact]
    public void A_conventions_file_over_64_KB_is_cut_on_a_character_boundary_with_a_note()
    {
        using var temp = new TempRepo();
        var path = Path.Combine(temp.RepoRoot, AgentSetup.ConventionsPath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        // One ASCII byte, then three-byte characters: the limit falls inside a character.
        File.WriteAllText(path, "x" + new string('€', 30_000), new UTF8Encoding(false));
        var text = McpServerSetup.WithProjectConventions("# Body\n", temp.RepoRoot);
        Assert.StartsWith("# Body\n\n---\n\n# This repository's conventions (CONVENTIONS.md)\n\nx€", text, StringComparison.Ordinal);
        Assert.EndsWith("\n\n(CONVENTIONS.md is longer than 64 KB; only its first 64 KB are shown here. Read the file for the rest.)\n", text, StringComparison.Ordinal);
        Assert.DoesNotContain('�', text);
        var shown = text[(text.IndexOf("\nx", StringComparison.Ordinal) + 1)..text.IndexOf("\n\n(CONVENTIONS.md", StringComparison.Ordinal)];
        Assert.Equal(1 + ((McpServerSetup.ProjectConventionsLimit - 1) / 3), shown.Length);

        File.WriteAllText(path, "");
        Assert.Equal("# Body\n", McpServerSetup.WithProjectConventions("# Body\n", temp.RepoRoot));
    }

    private static async Task<string> ResourceAsync(McpSession session, CancellationToken ct)
    {
        var read = await session.Client.ReadResourceAsync(new Uri(McpServerSetup.ConventionsUri), cancellationToken: ct);
        return Assert.IsType<TextResourceContents>(Assert.Single(read.Contents)).Text;
    }
}
