-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table public.notes of database main (PostgreSQL 16).

CREATE TABLE public.notes (
    id uuid NOT NULL,
    entity_type varchar(32) NOT NULL,
    entity_id varchar(40) NOT NULL,
    body text NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notes PRIMARY KEY (id)
);
CREATE INDEX ix_notes_entity_type_entity_id ON public.notes (entity_type, entity_id);
