-- Generated by Maquettiste (sql-ddl/routine). Do not edit; changes are overwritten.
-- Function dbo.invoice_total of database reporting (SQL Server).

CREATE FUNCTION dbo.invoice_total(@invoice_id uniqueidentifier)
RETURNS decimal(18,2)
AS
BEGIN
    RETURN (SELECT COALESCE(SUM(quantity * unit_price_amount), 0) FROM dbo.invoice_lines WHERE invoice_id = @invoice_id);
END
