-- Generated by Maquettiste (sql-ddl/schema). Do not edit; changes are overwritten.
-- Schema of database local (SQLite): tables 9, views 0, sequences 0, routines 1, database types 1, SQL objects 1.
-- Tables are in foreign-key dependency order: every table follows the tables it references.

PRAGMA foreign_keys = ON;

-- SQLite has no domain types; email_address is not created (columns of this type are text).

-- customer_notes
CREATE TABLE customer_notes (
    id text NOT NULL,
    customer_id text NOT NULL,
    body text NOT NULL,
    created_at text NULL,
    CONSTRAINT pk_customer_notes PRIMARY KEY (id)
);

-- customers
CREATE TABLE customers (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    customer_since text NULL,
    created_at text NOT NULL,
    updated_at text NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uq_customers_email UNIQUE (email)
);

-- invoices
CREATE TABLE invoices (
    id text NOT NULL,
    number text NOT NULL,
    issued_on text NOT NULL,
    total_amount numeric NULL,
    total_currency text NULL,
    status integer NOT NULL DEFAULT 0,
    notes text NULL,
    created_at text NOT NULL,
    updated_at text NULL,
    deleted_at text NULL,
    reason text NULL,
    discriminator text NOT NULL,
    customer_id text NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id),
    CONSTRAINT uq_invoices_number UNIQUE (number),
    CONSTRAINT fk_invoices_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT
);
CREATE INDEX ix_invoices_issued_on ON invoices (issued_on);

-- products
CREATE TABLE products (
    id text NOT NULL,
    sku text NOT NULL,
    name text NOT NULL,
    list_price_amount numeric NULL,
    list_price_currency text NULL,
    deleted_at text NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_sku UNIQUE (sku)
);

-- invoice_lines
CREATE TABLE invoice_lines (
    id text NOT NULL,
    quantity integer NOT NULL,
    unit_price_amount numeric NOT NULL,
    unit_price_currency text NOT NULL,
    description text NULL,
    invoice_id text NOT NULL,
    product_id text NOT NULL,
    CONSTRAINT pk_invoice_lines PRIMARY KEY (id),
    CONSTRAINT fk_invoice_lines_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_lines_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

-- invoice_notes
CREATE TABLE invoice_notes (
    id text NOT NULL,
    invoice_id text NOT NULL,
    body text NOT NULL,
    created_at text NULL,
    CONSTRAINT pk_invoice_notes PRIMARY KEY (id)
);

-- payments
CREATE TABLE payments (
    id INTEGER NOT NULL CONSTRAINT pk_payments PRIMARY KEY,
    amount_amount numeric NOT NULL,
    amount_currency text NOT NULL,
    received_at text NOT NULL,
    reference text NULL,
    method text NULL,
    ledger_position blob NULL,
    created_at text NOT NULL,
    updated_at text NULL
);

-- payment_invoice
CREATE TABLE payment_invoice (
    payments_id integer NOT NULL,
    invoices_id text NOT NULL,
    allocated_amount numeric NOT NULL,
    allocated_currency text NOT NULL,
    CONSTRAINT pk_payment_invoice PRIMARY KEY (payments_id, invoices_id),
    CONSTRAINT fk_payment_invoice_payments_id FOREIGN KEY (payments_id) REFERENCES payments (id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_invoice_invoices_id FOREIGN KEY (invoices_id) REFERENCES invoices (id) ON DELETE CASCADE
);

-- revenue_months
CREATE TABLE revenue_months (
    month text NOT NULL,
    invoice_count integer NOT NULL,
    revenue numeric NOT NULL,
    CONSTRAINT pk_revenue_months PRIMARY KEY (month)
);

-- SQLite has no stored routines; function invoice_total is not created.

CREATE TRIGGER invoices_keep_number BEFORE UPDATE OF number ON invoices FOR EACH ROW WHEN NEW.number <> OLD.number
BEGIN
    SELECT RAISE(ABORT, 'an invoice keeps its number');
END;
