-- Generated by Maquettiste (sql-ddl/seed). Edit only inside the protected region below; the rest is regenerated.
-- Seed data of database local (SQLite). Run it after the schema script or the migrations; it can run again.

-- Reference data, reconciled on every run: these tables, constraints and types are not in the schema snapshot.

-- PaymentMethod: lookup table payment_methods, rows upserted by code.
CREATE TABLE IF NOT EXISTS payment_methods (
    code TEXT NOT NULL,
    label TEXT NOT NULL,
    CONSTRAINT pk_payment_methods PRIMARY KEY (code)
);
INSERT INTO payment_methods (code, label) VALUES
    ('card', 'Card'),
    ('transfer', 'Bank transfer'),
    ('cash', 'Cash')
ON CONFLICT (code) DO UPDATE SET label = excluded.label;

-- payments.method (PaymentMethod, lookup-table).
DROP TRIGGER IF EXISTS ck_payments_method_ref_i;
DROP TRIGGER IF EXISTS ck_payments_method_ref_u;
DROP TRIGGER IF EXISTS fk_payments_method_ref_i;
DROP TRIGGER IF EXISTS fk_payments_method_ref_u;
DROP TRIGGER IF EXISTS fk_payments_method_ref_d;
CREATE TRIGGER fk_payments_method_ref_i BEFORE INSERT ON payments WHEN NEW.method IS NOT NULL AND NOT EXISTS (SELECT 1 FROM payment_methods WHERE code = NEW.method) BEGIN SELECT RAISE(ABORT, 'fk_payments_method_ref: payments.method must be a code of PaymentMethod'); END;
CREATE TRIGGER fk_payments_method_ref_u BEFORE UPDATE OF method ON payments WHEN NEW.method IS NOT NULL AND NOT EXISTS (SELECT 1 FROM payment_methods WHERE code = NEW.method) BEGIN SELECT RAISE(ABORT, 'fk_payments_method_ref: payments.method must be a code of PaymentMethod'); END;
CREATE TRIGGER fk_payments_method_ref_d BEFORE DELETE ON payment_methods WHEN EXISTS (SELECT 1 FROM payments WHERE method = OLD.code) BEGIN SELECT RAISE(ABORT, 'fk_payments_method_ref: a code still stored in payments.method cannot be deleted'); END;

-- Codes no longer in the seeds of PaymentMethod.
DELETE FROM payment_methods WHERE code NOT IN ('card', 'transfer', 'cash');

-- maquettiste:keep id=seed-data
-- Hand-written seed data for local goes here, for example:
-- INSERT INTO ... VALUES (...);
-- maquettiste:end-keep
