-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table public.recipe_ingredient of database main (PostgreSQL).
-- Junction table of relation "contains".

CREATE TABLE public.recipe_ingredient (
    recipe_code varchar(32) NOT NULL,
    ingredient_sku varchar(32) NOT NULL,
    quantity numeric(12,3) NOT NULL,
    unit_of_measure varchar(8) NOT NULL DEFAULT 'g',
    CONSTRAINT pk_recipe_ingredient PRIMARY KEY (recipe_code, ingredient_sku),
    CONSTRAINT fk_recipe_ingredient_recipe_code FOREIGN KEY (recipe_code) REFERENCES public.recipes (code) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ingredient_ingredient_sku FOREIGN KEY (ingredient_sku) REFERENCES public.ingredients (sku) ON DELETE CASCADE
);
