-- Generated by Maquettiste (sql-ddl/routine). Do not edit; changes are overwritten.
-- Function invoice_total of database local (SQLite).

-- SQLite has no stored routines; function invoice_total is not created.
