-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table public.gate_signatures of database main (PostgreSQL 16).
-- Maps entity GateSignature.

CREATE TABLE public.gate_signatures (
    id uuid NOT NULL,
    instance varchar(255) NOT NULL,
    gate varchar(255) NOT NULL,
    sequence bigint NOT NULL,
    signer varchar(255) NOT NULL,
    actor varchar(255) NOT NULL,
    meaning varchar(255) NULL,
    reason text NULL,
    outcome varchar(255) NOT NULL,
    at timestamptz(6) NOT NULL,
    CONSTRAINT pk_gate_signatures PRIMARY KEY (id)
);
