-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table public.sales_orders of database main (PostgreSQL 16).

CREATE TABLE public.sales_orders (
    id uuid NOT NULL,
    status integer NOT NULL DEFAULT 0,
    configuration jsonb NULL,
    total numeric(18,2) NOT NULL,
    credit_limit numeric(18,2) NOT NULL,
    CONSTRAINT pk_sales_orders PRIMARY KEY (id)
);
COMMENT ON COLUMN public.sales_orders.configuration IS 'The active states of the lifecycle, for the nested states the status cannot hold.';
