-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table public.sales_order_histories of database main (PostgreSQL 16).

CREATE TABLE public.sales_order_histories (
    id uuid NOT NULL,
    sales_order_id uuid NOT NULL,
    from_state varchar(255) NULL,
    to_state varchar(255) NOT NULL,
    at timestamptz(6) NOT NULL,
    CONSTRAINT pk_sales_order_histories PRIMARY KEY (id)
);
COMMENT ON TABLE public.sales_order_histories IS 'One row per status change of a sales order.';
