// Generated by Maquettiste (csharp-dapper/entity). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace Shop.Model.Shop;

/// <summary>A customer; deleting one only marks it deleted.</summary>
public partial class Customer
{
    public Guid Id { get; set; }
    public string Name { get; set; } = default!;
    public string? Email { get; set; }
}
