// Generated by Maquettiste (csharp-dapper/entity). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace Shop.Model.Shop;

/// <summary>A product we sell, bound one to one to its table.</summary>
public partial class Product
{
    public long Id { get; set; }
    public string Sku { get; set; } = default!;
    public string Name { get; set; } = default!;
    public decimal Price { get; set; }
}
