// Generated by Maquettiste (csharp-dapper/repository). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Dapper;

namespace Shop.Model.Shop;

/// <summary>Reads and writes <see cref="Product"/> rows through its binding to table products (database main, postgresql).</summary>
public partial interface IProductRepository
{
    /// <summary>Returns the entity with the given key, or null.</summary>
    Task<Product?> GetAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>Returns a page of entities in key order.</summary>
    Task<IReadOnlyList<Product>> ListAsync(int mq_skip = 0, int mq_take = 100, CancellationToken cancellationToken = default);

    /// <summary>Inserts the entity and sets its database-generated key.</summary>
    Task InsertAsync(Product entity, CancellationToken cancellationToken = default);

    /// <summary>Updates the entity; returns false when no row has its key.</summary>
    Task<bool> UpdateAsync(Product entity, CancellationToken cancellationToken = default);

    /// <summary>Deletes the entity with the given key; returns false when there was none.</summary>
    Task<bool> DeleteAsync(long id, CancellationToken cancellationToken = default);
}

/// <summary>The Dapper implementation of <see cref="IProductRepository"/> over an open or closed <see cref="IDbConnection"/>.</summary>
public partial class ProductRepository(IDbConnection connection, IDbTransaction? transaction = null) : IProductRepository
{
    private const string SelectSql = """
        SELECT t.id AS id, t.sku AS sku, t.name AS name, t.price AS price
        FROM public.products t
        WHERE t.id = @id
        """;

    private const string ListSql = """
        SELECT t.id AS id, t.sku AS sku, t.name AS name, t.price AS price
        FROM public.products t
        ORDER BY id LIMIT @mq_take OFFSET @mq_skip
        """;

    private const string InsertSql = """
        INSERT INTO public.products (sku, name, price)
        VALUES (@sku, @name, @price)
        RETURNING id AS id
        """;

    private const string UpdateSql = """
        UPDATE public.products SET sku = @sku, name = @name, price = @price
        WHERE id = @id
        """;

    private const string DeleteSql = """
        DELETE FROM public.products
        WHERE id = @id
        """;

    /// <inheritdoc/>
    public async Task<Product?> GetAsync(long id, CancellationToken cancellationToken = default)
    {
        var row = await connection.QuerySingleOrDefaultAsync<Row>(new CommandDefinition(SelectSql, new { id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return row is null ? null : Row.ToEntity(row);
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyList<Product>> ListAsync(int mq_skip = 0, int mq_take = 100, CancellationToken cancellationToken = default)
    {
        var rows = await connection.QueryAsync<Row>(new CommandDefinition(ListSql, new { mq_skip, mq_take }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows.Select(Row.ToEntity).ToList();
    }

    /// <inheritdoc/>
    public async Task InsertAsync(Product entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        entity.Id = await connection.ExecuteScalarAsync<long>(new CommandDefinition(InsertSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    /// <inheritdoc/>
    public async Task<bool> UpdateAsync(Product entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return await connection.ExecuteAsync(new CommandDefinition(UpdateSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <inheritdoc/>
    public async Task<bool> DeleteAsync(long id, CancellationToken cancellationToken = default)
    {
        return await connection.ExecuteAsync(new CommandDefinition(DeleteSql, new { id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <summary>One row of table products as the binding reads and writes it, field by field.</summary>
    private sealed class Row
    {
        public long id { get; set; }
        public string sku { get; set; } = default!;
        public string name { get; set; } = default!;
        public decimal price { get; set; }

        public static Product ToEntity(Row row) => new()
        {
            Id = row.id,
            Sku = row.sku,
            Name = row.name,
            Price = row.price,
        };

        public static Row From(Product entity) => new()
        {
            id = entity.Id,
            sku = entity.Sku,
            name = entity.Name,
            price = entity.Price,
        };
    }
}
