// Generated by Maquettiste (csharp-dapper/repository). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Dapper;

namespace Shop.Model.Shop;

/// <summary>Reads and writes <see cref="ProductNote"/> rows through its binding to table notes (database main, postgresql).</summary>
public partial interface IProductNoteRepository
{
    /// <summary>Returns the entity with the given key, or null.</summary>
    Task<ProductNote?> GetAsync(Guid id, CancellationToken cancellationToken = default);

    /// <summary>Returns a page of entities in key order.</summary>
    Task<IReadOnlyList<ProductNote>> ListAsync(int mq_skip = 0, int mq_take = 100, CancellationToken cancellationToken = default);

    /// <summary>Inserts the entity.</summary>
    Task InsertAsync(ProductNote entity, CancellationToken cancellationToken = default);

    /// <summary>Updates the entity; returns false when no row has its key.</summary>
    Task<bool> UpdateAsync(ProductNote entity, CancellationToken cancellationToken = default);

    /// <summary>Deletes the entity with the given key; returns false when there was none.</summary>
    Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default);
}

/// <summary>The Dapper implementation of <see cref="IProductNoteRepository"/> over an open or closed <see cref="IDbConnection"/>.</summary>
public partial class ProductNoteRepository(IDbConnection connection, IDbTransaction? transaction = null) : IProductNoteRepository
{
    private const string SelectSql = """
        SELECT t.id AS id, t.entity_id AS sku, t.body AS body, t.created_at AS createdAt
        FROM public.notes t
        WHERE t.entity_type = 'product' AND t.id = @id
        """;

    private const string ListSql = """
        SELECT t.id AS id, t.entity_id AS sku, t.body AS body, t.created_at AS createdAt
        FROM public.notes t
        WHERE t.entity_type = 'product'
        ORDER BY id LIMIT @mq_take OFFSET @mq_skip
        """;

    private const string InsertSql = """
        INSERT INTO public.notes (id, entity_id, body, entity_type)
        VALUES (@id, @sku, @body, 'product')
        """;

    private const string UpdateSql = """
        UPDATE public.notes SET entity_id = @sku, body = @body
        WHERE id = @id AND entity_type = 'product'
        """;

    private const string DeleteSql = """
        DELETE FROM public.notes
        WHERE id = @id AND entity_type = 'product'
        """;

    /// <inheritdoc/>
    public async Task<ProductNote?> GetAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var row = await connection.QuerySingleOrDefaultAsync<Row>(new CommandDefinition(SelectSql, new { id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return row is null ? null : Row.ToEntity(row);
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyList<ProductNote>> ListAsync(int mq_skip = 0, int mq_take = 100, CancellationToken cancellationToken = default)
    {
        var rows = await connection.QueryAsync<Row>(new CommandDefinition(ListSql, new { mq_skip, mq_take }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows.Select(Row.ToEntity).ToList();
    }

    /// <inheritdoc/>
    public async Task InsertAsync(ProductNote entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        if (entity.Id == Guid.Empty)
            entity.Id = Guid.CreateVersion7();
        await connection.ExecuteAsync(new CommandDefinition(InsertSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    /// <inheritdoc/>
    public async Task<bool> UpdateAsync(ProductNote entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return await connection.ExecuteAsync(new CommandDefinition(UpdateSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <inheritdoc/>
    public async Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default)
    {
        return await connection.ExecuteAsync(new CommandDefinition(DeleteSql, new { id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <summary>One row of table notes as the binding reads and writes it, field by field.</summary>
    private sealed class Row
    {
        public Guid id { get; set; }
        public string sku { get; set; } = default!;
        public string body { get; set; } = default!;
        public DateTimeOffset? createdAt { get; set; }

        public static ProductNote ToEntity(Row row) => new()
        {
            Id = row.id,
            Sku = row.sku,
            Body = row.body,
            CreatedAt = row.createdAt,
        };

        public static Row From(ProductNote entity) => new()
        {
            id = entity.Id,
            sku = entity.Sku,
            body = entity.Body,
            createdAt = entity.CreatedAt,
        };
    }
}
