// Generated by Maquettiste (csharp-dapper/registrations). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;

namespace Shop.Model.Shop;

/// <summary>The Dapper repositories of package Shop.</summary>
/// <example><code>ShopRepositories.Register((service, implementation) => services.AddScoped(service, implementation));</code></example>
public static partial class ShopRepositories
{
    /// <summary>Every repository of the package: the interface to register and the class that implements it.</summary>
    public static IReadOnlyList<(Type Service, Type Implementation)> All { get; } =
    [
        (typeof(ICustomerRepository), typeof(CustomerRepository)),
        (typeof(ICustomerNoteRepository), typeof(CustomerNoteRepository)),
        (typeof(ICustomerSummaryRepository), typeof(CustomerSummaryRepository)),
        (typeof(IProductRepository), typeof(ProductRepository)),
        (typeof(IProductNoteRepository), typeof(ProductNoteRepository)),
    ];

    /// <summary>Calls <paramref name="register"/> once per repository.</summary>
    public static void Register(Action<Type, Type> register)
    {
        ArgumentNullException.ThrowIfNull(register);
        foreach (var (service, implementation) in All)
            register(service, implementation);
    }
}
