// Generated by Maquettiste (csharp-dapper/reference-type). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;

namespace App.Model;

/// <summary>How a payment was made.</summary>
public sealed record PaymentMethod(string Code, string Label);

/// <summary>The rows of <see cref="PaymentMethod"/> in seed order, one field per row.</summary>
public static partial class PaymentMethods
{
    public static readonly PaymentMethod Card = new("card", "Card");
    public static readonly PaymentMethod Transfer = new("transfer", "Bank transfer");
    public static readonly PaymentMethod Cash = new("cash", "Cash");

    /// <summary>Every row, in seed order.</summary>
    public static IReadOnlyList<PaymentMethod> All { get; } = [Card, Transfer, Cash];

    /// <summary>The row with a code, or null.</summary>
    public static PaymentMethod? Find(string code) => code switch
    {
        "card" => Card,
        "transfer" => Transfer,
        "cash" => Cash,
        _ => null,
    };
}
