-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table customers of database oracle (Oracle).

CREATE TABLE customers (
    id number(19) GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 2) NOT NULL,
    code char(10 char) NOT NULL,
    name varchar2(150 char) NOT NULL,
    email varchar2(200 char) NULL,
    remarks clob NULL,
    balance number(10,2) DEFAULT 10 NOT NULL,
    status varchar2(1 char) DEFAULT 'A' NOT NULL,
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    balance_twice number(14,2) GENERATED ALWAYS AS (balance * 2) VIRTUAL,
    vip number(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT ck_customers_balance CHECK (balance >= -100)
);
CREATE INDEX ix_customers_name ON customers (name, created_at DESC);
CREATE UNIQUE INDEX ix_customers_code_lookup ON customers (code);
CREATE INDEX ix_customers_email_lower ON customers ((lower(email)));
COMMENT ON TABLE customers IS 'Customers who place orders, with their balance.';
COMMENT ON COLUMN customers.remarks IS 'Remarks about the customer.';
