-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table orders of database oracle (Oracle).

CREATE TABLE orders (
    id number(19) DEFAULT order_number_seq.NEXTVAL NOT NULL,
    "number" varchar2(16 char) NOT NULL,
    customer_id number(19) NOT NULL,
    total number(12,2) DEFAULT 0 NOT NULL,
    placed_on date NULL,
    CONSTRAINT pk_orders_id PRIMARY KEY (id),
    CONSTRAINT uq_orders_customer_number UNIQUE (customer_id, "number"),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT ck_orders_total CHECK (total >= 0)
);
