-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table order_lines of database sqlite (SQLite).

CREATE TABLE IF NOT EXISTS order_lines (
    order_id integer NOT NULL,
    line_no integer NOT NULL,
    product_code text NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0)
);
CREATE INDEX IF NOT EXISTS ix_order_lines_product ON order_lines (product_code);
