-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table shop.customers of database sqlserver (SQL Server).

CREATE TABLE shop.customers (
    id bigint IDENTITY(100,1) NOT NULL,
    code char(10) NOT NULL,
    name varchar(150) COLLATE Latin1_General_100_CI_AS NOT NULL,
    email nvarchar(200) NULL,
    remarks nvarchar(max) NULL,
    balance decimal(10,2) NOT NULL CONSTRAINT customers_balance_dflt DEFAULT 10,
    status nvarchar(1) NOT NULL CONSTRAINT df_customers_status DEFAULT N'A',
    created_at datetime2(6) NOT NULL CONSTRAINT df_customers_created_at DEFAULT SYSUTCDATETIME(),
    balance_twice AS (balance * 2) PERSISTED,
    vip bit NOT NULL CONSTRAINT df_customers_vip DEFAULT 0,
    CONSTRAINT pk_customers PRIMARY KEY NONCLUSTERED (id),
    CONSTRAINT ck_customers_balance CHECK (balance >= -100)
);
CREATE INDEX ix_customers_name ON shop.customers (name, created_at DESC) INCLUDE (email);
CREATE UNIQUE INDEX ix_customers_code_lookup ON shop.customers (code);
BEGIN DECLARE @mq_rc2 int; EXEC @mq_rc2 = sys.sp_addextendedproperty @name = N'MS_Description', @value = N'Customers who place orders, with their balance.', @level0type = N'SCHEMA', @level0name = N'shop', @level1type = N'TABLE', @level1name = N'customers'; IF @mq_rc2 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
BEGIN DECLARE @mq_rc1 int; EXEC @mq_rc1 = sys.sp_addextendedproperty @name = N'MS_Description', @value = N'Remarks about the customer.', @level0type = N'SCHEMA', @level0name = N'shop', @level1type = N'TABLE', @level1name = N'customers', @level2type = N'COLUMN', @level2name = N'remarks'; IF @mq_rc1 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
