// A small tokenizer for syntax colors in the diff viewer, by file extension: SQL, C#, JSON.
export type TokenKind = "keyword" | "string" | "comment" | "plain";
export interface Token {
  kind: TokenKind;
  text: string;
}

const KEYWORDS: Record<string, Set<string>> = {
  sql: new Set(
    "select from where create table alter add constraint primary foreign key references unique index on delete update cascade restrict set null not default as insert into values drop schema if exists and or in is varchar integer bigint text uuid date numeric boolean timestamptz generated by identity".split(
      " ",
    ),
  ),
  cs: new Set(
    "namespace using public private protected internal sealed partial class record struct enum interface get set init return new null true false var static readonly void string int long short bool decimal double float byte object async await this base override virtual".split(
      " ",
    ),
  ),
  json: new Set(["true", "false", "null"]),
};

export function languageOf(path: string): "sql" | "cs" | "json" | null {
  if (/\.sql$/i.test(path)) return "sql";
  if (/\.cs$/i.test(path)) return "cs";
  if (/\.json$/i.test(path)) return "json";
  return null;
}

export function tokenize(line: string, language: "sql" | "cs" | "json" | null): Token[] {
  if (!language) return [{ kind: "plain", text: line }];
  const keywords = KEYWORDS[language];
  const comment = language === "sql" ? "--" : language === "cs" ? "//" : null;
  const tokens: Token[] = [];
  let i = 0;
  let plain = "";
  const flush = () => {
    if (plain) tokens.push({ kind: "plain", text: plain });
    plain = "";
  };
  while (i < line.length) {
    if (comment && line.startsWith(comment, i)) {
      flush();
      tokens.push({ kind: "comment", text: line.slice(i) });
      return tokens;
    }
    const ch = line[i];
    if (ch === "'" || ch === '"') {
      flush();
      let j = i + 1;
      while (j < line.length && line[j] !== ch) j += line[j] === "\\" ? 2 : 1;
      tokens.push({ kind: "string", text: line.slice(i, j + 1) });
      i = j + 1;
      continue;
    }
    if (/[A-Za-z_]/.test(ch)) {
      let j = i;
      while (j < line.length && /[A-Za-z0-9_]/.test(line[j])) j++;
      const word = line.slice(i, j);
      if (keywords.has(language === "sql" ? word.toLowerCase() : word)) {
        flush();
        tokens.push({ kind: "keyword", text: word });
      } else plain += word;
      i = j;
      continue;
    }
    plain += ch;
    i++;
  }
  flush();
  return tokens;
}
