// Pack authoring for the mock backend (generation-ui.md section 5.1): the files of every pack under
// .maquettiste/templates/<pack>/, with hashes as ETags, 409 on a stale hash, roles and users derived the
// way the engine derives them (the units' templates, literal includes, scripts, type maps). The pack.json
// text comes from the fixture's manifests; template texts are synthetic, one per unit plus a shared partial.
import type { components } from "@/api/schema";
import { sha256Hex } from "@/lib/sha256";
import type { MockModel } from "./store";

type S = components["schemas"];
type Diagnostic = S["Diagnostic"];
export type PackWriteResult = S["PackWriteResult"];
type WriteAnswer = { status: 200 | 201 | 404 | 409 | 422; body: PackWriteResult };

const NAME = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;
const INCLUDE = /include\s+["']([^"'\r\n]+)["']/g;
const MAX_BYTES = 1024 * 1024;

function diagnostic(rule: string, message: string, filePath: string | null, jsonPointer: string | null = null): Diagnostic {
  const severity = rule === "MQ6024" || rule === "MQ6025" ? "warning" : "error";
  return { rule, severity, message, elementId: null, filePath, jsonPointer, line: null, column: null };
}

function result(outcome: PackWriteResult["outcome"], hash: string | null, extra: Partial<PackWriteResult> = {}): PackWriteResult {
  return { outcome, hash, current: null, diagnostics: [], files: [], ...extra };
}

/** Whether a pack-relative path is one the engine accepts (relative, `/` separators, no `.`, `..` or hidden segment). */
export function validPackPath(path: string): boolean {
  if (!path || path.startsWith("/") || path.includes("\\") || path.includes(":")) return false;
  return path.split("/").every((s) => s.length > 0 && s !== "." && s !== ".." && !s.startsWith("."));
}

export class MockPacks {
  private readonly files = new Map<string, Map<string, string>>();

  constructor(private readonly model: MockModel) {
    for (const manifest of model.packs) {
      const files = new Map<string, string>();
      files.set("pack.json", `${JSON.stringify(manifest, null, 2)}\n`);
      files.set("_shared.scriban", `{{~ # Shared by every template of ${manifest.name} (mock partial). ~}}\n-- Generated by Maquettiste (${manifest.name}).\n`);
      files.set("README.md", `# ${manifest.name}\n\n${manifest.description ?? ""}\n`);
      for (const unit of manifest.units) {
        files.set(unit.template, `{{ include "_shared.scriban" }}\n-- ${manifest.name}/${unit.id}: ${unit.for}\n{{ element.name }}\n`);
        if (unit.companion) files.set(unit.companion.template, `-- companion of ${unit.id}\n`);
      }
      this.files.set(manifest.name, files);
    }
  }

  names(): string[] {
    return [...this.files.keys()].sort();
  }

  /** A pack's files, pack-relative, ordinal. */
  fileNames(pack: string): string[] {
    return [...(this.files.get(pack)?.keys() ?? [])].sort();
  }

  has(pack: string): boolean {
    return this.files.has(pack);
  }

  private settings(pack: string): { enabled: boolean; output: string; parameters: Record<string, unknown> } {
    const s = (
      this.model.settingsDocument().settings.packs as Record<string, { enabled?: boolean; output?: string; parameters?: Record<string, unknown> }> | undefined
    )?.[pack];
    return { enabled: s?.enabled ?? true, output: s?.output ?? "", parameters: s?.parameters ?? {} };
  }

  private manifest(pack: string): S["PackManifest"] | null {
    const text = this.files.get(pack)?.get("pack.json");
    if (text === undefined) return null;
    try {
      const json = JSON.parse(text) as S["PackManifest"];
      return { ...json, units: json.units ?? [], parameters: json.parameters ?? {}, scripts: json.scripts ?? [] };
    } catch {
      return null;
    }
  }

  private diagnostics(pack: string): Diagnostic[] {
    const manifest = this.manifest(pack);
    const file = `.maquettiste/templates/${pack}/pack.json`;
    if (!manifest) return [diagnostic("MQ6001", "pack.json is not valid JSON.", file)];
    const files = this.files.get(pack)!;
    const found: Diagnostic[] = [];
    manifest.units.forEach((unit, i) => {
      if (!files.has(unit.template))
        found.push(diagnostic("MQ6022", `Template '${unit.template}' does not exist in the pack folder.`, file, `/units/${i}/template`));
    });
    const declared = new Set([...Object.keys(manifest.parameters ?? {}), ...Object.keys((manifest.parameterSchema?.properties as object | undefined) ?? {})]);
    for (const key of Object.keys(this.settings(pack).parameters).sort()) {
      if (!declared.has(key))
        found.push(
          diagnostic(
            "MQ6024",
            `Pack '${pack}' neither defaults nor declares the parameter '${key}'.`,
            ".maquettiste/maquettiste.json",
            `/packs/${pack}/parameters/${key}`,
          ),
        );
    }
    return found;
  }

  /** What the pack's scripts register, read from their text (the server runs them): by kind, then name. */
  registrations(pack: string): S["ScriptRegistration"][] {
    const files = this.files.get(pack);
    if (!files) return [];
    const order = ["helper", "selector", "filter", "transform", "rule"];
    const found: S["ScriptRegistration"][] = [];
    for (const [path, text] of [...files].filter(([p]) => p.endsWith(".js")).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
      for (const match of text.matchAll(/maquettiste\.(helper|selector|filter|transform|rule)\(\s*["']([^"']+)["']/g))
        found.push({ kind: match[1] as S["ScriptRegistration"]["kind"], name: match[2]!, declaredIn: path });
    }
    const key = (r: S["ScriptRegistration"]) => `${order.indexOf(r.kind)}\u0000${r.name}\u0000${r.declaredIn}`;
    return found.sort((a, b) => (key(a) < key(b) ? -1 : key(a) > key(b) ? 1 : 0));
  }

  fileInfos(pack: string): S["PackFileInfo"][] {
    const files = this.files.get(pack)!;
    const manifest = this.manifest(pack);
    const used = new Map<string, Set<string>>([...files.keys()].map((p) => [p, new Set<string>()]));
    const named = new Set<string>();
    for (const unit of manifest?.units ?? []) {
      named.add(unit.template);
      used.get(unit.template)?.add(`unit:${unit.id}`);
      if (unit.companion) {
        named.add(unit.companion.template);
        used.get(unit.companion.template)?.add(`companion:${unit.id}`);
      }
    }
    const scripts = new Set(manifest?.scripts?.length ? manifest.scripts : [...files.keys()].filter((p) => p.endsWith(".js")));
    const included = new Set<string>();
    for (const [path, text] of files) {
      if (scripts.has(path) || path === "pack.json") continue;
      for (const m of text.matchAll(INCLUDE)) {
        if (m[1] !== path && used.has(m[1])) {
          used.get(m[1])!.add(`include:${path}`);
          included.add(m[1]);
        }
      }
    }
    const role = (p: string): S["PackFileInfo"]["role"] =>
      p === "pack.json"
        ? "manifest"
        : scripts.has(p)
          ? "script"
          : /^types\/[^/]+\.json$/.test(p)
            ? "type-map"
            : named.has(p)
              ? "template"
              : included.has(p)
                ? "partial"
                : "other";
    return [...files.keys()].sort().map((p) => ({
      path: p,
      size: new TextEncoder().encode(files.get(p)!).length,
      hash: sha256Hex(files.get(p)!),
      role: role(p),
      usedBy: [...used.get(p)!].sort(),
    }));
  }

  list(): S["PackListResponse"] {
    return {
      packs: this.names().map((name) => {
        const manifest = this.manifest(name);
        const s = this.settings(name);
        return {
          name,
          version: manifest?.version ?? null,
          description: manifest?.description ?? null,
          enabled: s.enabled,
          output: s.output,
          units: manifest?.units ?? [],
          fileCount: this.files.get(name)!.size,
          diagnostics: this.diagnostics(name),
        };
      }),
    };
  }

  get(pack: string): S["PackDocument"] | null {
    const files = this.files.get(pack);
    if (!files) return null;
    const manifest = this.manifest(pack);
    const s = this.settings(pack);
    const schema = (manifest?.parameterSchema?.properties ?? {}) as Record<string, Record<string, unknown>>;
    const required = new Set((manifest?.parameterSchema?.required as string[] | undefined) ?? []);
    const defaults = (manifest?.parameters ?? {}) as Record<string, unknown>;
    const names = [...new Set([...Object.keys(schema), ...Object.keys(defaults), ...Object.keys(s.parameters)])].sort();
    let document: Record<string, unknown> | null = null;
    try {
      document = JSON.parse(files.get("pack.json")!) as Record<string, unknown>;
    } catch {
      document = null;
    }
    return {
      name: pack,
      enabled: s.enabled,
      output: s.output,
      hash: sha256Hex(files.get("pack.json")!),
      document,
      parameters: names.map((n) => ({
        name: n,
        default: defaults[n] ?? null,
        value: s.parameters[n] ?? null,
        schema: schema[n] ?? null,
        required: required.has(n),
      })),
      files: this.fileInfos(pack),
      diagnostics: this.diagnostics(pack),
      registrations: this.registrations(pack),
    };
  }

  readFile(pack: string, path: string): S["PackFileContent"] | null {
    const text = this.files.get(pack)?.get(path);
    return text === undefined ? null : { path, hash: sha256Hex(text), text };
  }

  /** `expected` null creates the file (409 when it exists). */
  writeFile(pack: string, path: string, text: string, expected: string | null): WriteAnswer {
    const files = this.files.get(pack);
    if (!files) return { status: 404, body: result("not-found", null) };
    const file = `.maquettiste/templates/${pack}/${path}`;
    if (text.includes("\u0000"))
      return { status: 422, body: result("invalid", null, { diagnostics: [diagnostic("MQ6001", "A pack file must be text.", file)] }) };
    if (new TextEncoder().encode(text).length > MAX_BYTES)
      return { status: 422, body: result("invalid", null, { diagnostics: [diagnostic("MQ6001", "A pack file is at most 1 MB.", file)] }) };
    const disk = files.get(path);
    const diskHash = disk === undefined ? null : sha256Hex(disk);
    if (diskHash !== expected) return { status: 409, body: result("conflict", diskHash, { current: disk ?? null }) };
    files.set(path, text);
    const unbalanced = (text.match(/\{\{/g)?.length ?? 0) !== (text.match(/\}\}/g)?.length ?? 0);
    const diagnostics =
      unbalanced && !path.endsWith(".md") ? [{ ...diagnostic("MQ6003", "The template does not parse: unbalanced code span.", file), line: 1, column: 1 }] : [];
    return { status: expected === null ? 201 : 200, body: result("saved", sha256Hex(text), { diagnostics, files: [path] }) };
  }

  deleteFile(pack: string, path: string, expected: string): WriteAnswer {
    const files = this.files.get(pack);
    const disk = files?.get(path);
    if (!files || disk === undefined) return { status: 404, body: result("not-found", null) };
    const usedBy = this.fileInfos(pack).find((f) => f.path === path)?.usedBy ?? [];
    if (usedBy.length)
      return {
        status: 409,
        body: result("referenced", null, { diagnostics: [diagnostic("MQ6022", `'${path}' is used by ${usedBy.join(", ")}; change those first.`, path)] }),
      };
    if (sha256Hex(disk) !== expected) return { status: 409, body: result("conflict", sha256Hex(disk), { current: disk }) };
    files.delete(path);
    return { status: 200, body: result("saved", null, { files: [path] }) };
  }

  /** Moves a file (If-Match on the source); updateUnits rewrites the unit templates that name it, checked against expectedPackHash. */
  moveFile(pack: string, move: { from: string; to: string; updateUnits?: boolean; expectedPackHash?: string | null }, expected: string): WriteAnswer {
    const files = this.files.get(pack);
    const disk = files?.get(move.from);
    if (!files || disk === undefined) return { status: 404, body: result("not-found", null) };
    if (files.has(move.to))
      return { status: 422, body: result("invalid", null, { diagnostics: [diagnostic("MQ6001", `'${move.to}' already exists.`, move.to)] }) };
    if (move.updateUnits && !move.expectedPackHash)
      return {
        status: 422,
        body: result("invalid", null, { diagnostics: [diagnostic("MQ6001", "expectedPackHash is required when updateUnits is set.", "pack.json")] }),
      };
    const usedBy = this.fileInfos(pack).find((f) => f.path === move.from)?.usedBy ?? [];
    const included = usedBy.filter((u) => u.startsWith("include:"));
    if (included.length || (!move.updateUnits && usedBy.length))
      return {
        status: 409,
        body: result("referenced", null, { diagnostics: [diagnostic("MQ6022", `'${move.from}' is used by ${usedBy.join(", ")}.`, move.from)] }),
      };
    if (sha256Hex(disk) !== expected) return { status: 409, body: result("conflict", sha256Hex(disk), { current: disk }) };
    const written = [move.from, move.to];
    if (move.updateUnits) {
      const packJson = files.get("pack.json")!;
      if (sha256Hex(packJson) !== move.expectedPackHash)
        return { status: 409, body: result("conflict", sha256Hex(packJson), { current: packJson, files: ["pack.json"] }) };
      const document = JSON.parse(packJson) as { units?: { template: string; companion?: { template: string } }[] };
      for (const unit of document.units ?? []) {
        if (unit.template === move.from) unit.template = move.to;
        if (unit.companion?.template === move.from) unit.companion.template = move.to;
      }
      files.set("pack.json", `${JSON.stringify(document, null, 2)}\n`);
      const index = this.model.packs.findIndex((p) => p.name === pack);
      const manifest = this.manifest(pack);
      if (index >= 0 && manifest) this.model.packs[index] = manifest;
      written.splice(1, 0, "pack.json");
    }
    files.delete(move.from);
    files.set(move.to, disk);
    return { status: 200, body: result("saved", sha256Hex(disk), { diagnostics: this.diagnostics(pack), files: written }) };
  }

  saveManifest(pack: string, document: Record<string, unknown>, expected: string): WriteAnswer {
    const files = this.files.get(pack);
    if (!files) return { status: 404, body: result("not-found", null) };
    const file = `.maquettiste/templates/${pack}/pack.json`;
    const units = (document.units as { for?: string }[] | undefined) ?? [];
    const scope = units.findIndex(
      (u) =>
        typeof u.for !== "string" ||
        !/^(model|each (package|entity|relation|enum|value object|table|view|sequence|routine|database type|sql object|reference type|seed|locale|process|actor|scenario)|select [A-Za-z_]\w*)$/.test(
          u.for,
        ),
    );
    if (scope >= 0)
      return {
        status: 422,
        body: result("invalid", null, {
          diagnostics: [diagnostic("MQ6021", `Unit ${scope} has an unknown scope '${units[scope].for}'.`, file, `/units/${scope}/for`)],
        }),
      };
    if (document.name !== pack)
      return { status: 422, body: result("invalid", null, { diagnostics: [diagnostic("MQ6001", `pack.json must name the pack '${pack}'.`, file, "/name")] }) };
    const disk = files.get("pack.json")!;
    if (sha256Hex(disk) !== expected) return { status: 409, body: result("conflict", sha256Hex(disk), { current: disk }) };
    const text = `${JSON.stringify(document, null, 2)}\n`;
    files.set("pack.json", text);
    const index = this.model.packs.findIndex((p) => p.name === pack);
    const manifest = this.manifest(pack);
    if (index >= 0 && manifest) this.model.packs[index] = manifest;
    return { status: 200, body: result("saved", sha256Hex(text), { diagnostics: this.diagnostics(pack), files: ["pack.json"] }) };
  }

  /** Why a pack cannot be removed with this pack.json hash (404, or 409 with the disk version), or null when it can. */
  removalRefusal(pack: string, expected: string): { status: 404 | 409; hash: string | null; current: string | null } | null {
    const disk = this.files.get(pack)?.get("pack.json");
    if (disk === undefined) return { status: 404, hash: null, current: null };
    return sha256Hex(disk) === expected ? null : { status: 409, hash: sha256Hex(disk), current: disk };
  }

  /** Drops a pack's folder and its manifest from the model's pack list; answers the files it held, ordinal. */
  drop(pack: string): string[] {
    const files = [...(this.files.get(pack)?.keys() ?? [])].sort();
    this.files.delete(pack);
    const index = this.model.packs.findIndex((p) => p.name === pack);
    if (index >= 0) this.model.packs.splice(index, 1);
    return files;
  }

  /**
   * Renames a pack's folder (its files keep their bytes, pack.json names the new folder) and its entry in the model's
   * pack list; answers the files that moved, ordinal, and the new pack.json hash.
   */
  rename(from: string, to: string): { files: string[]; hash: string } {
    const files = this.files.get(from)!;
    const manifest = JSON.parse(files.get("pack.json")!) as Record<string, unknown>;
    files.set("pack.json", `${JSON.stringify({ ...manifest, name: to }, null, 2)}\n`);
    this.files.delete(from);
    this.files.set(to, files);
    const index = this.model.packs.findIndex((p) => p.name === from);
    const renamed = this.manifest(to);
    if (index >= 0) this.model.packs.splice(index, 1);
    if (renamed) {
      this.model.packs.push(renamed);
      this.model.packs.sort((a, b) => a.name.localeCompare(b.name));
    }
    return { files: [...files.keys()].sort(), hash: sha256Hex(files.get("pack.json")!) };
  }

  create(name: string, from: string): WriteAnswer | { problem: string } {
    if (!NAME.test(name)) return { problem: `'${name}' is not a pack name.` };
    if (this.files.has(name))
      return { status: 409, body: result("conflict", null, { diagnostics: [diagnostic("MQ6001", `templates/${name}/ already exists.`, null)] }) };
    let files: Map<string, string>;
    if (from === "empty") {
      const manifest = {
        name,
        version: "0.1.0",
        engine: ">=1.0 <2.0",
        description: "A new template pack.",
        units: [{ id: "entity", template: "entity.scriban", for: "each entity", output: "{{ kebab entity.name }}.txt" }],
      };
      files = new Map([
        ["entity.scriban", "{{ entity.name }}\n"],
        ["pack.json", `${JSON.stringify(manifest, null, 2)}\n`],
      ]);
    } else if (this.files.has(from)) {
      files = new Map(this.files.get(from)!);
      const manifest = JSON.parse(files.get("pack.json")!) as Record<string, unknown>;
      files.set("pack.json", `${JSON.stringify({ ...manifest, name }, null, 2)}\n`);
    } else {
      return {
        status: 422,
        body: result("invalid", null, { diagnostics: [diagnostic("MQ6001", `'${from}' is neither 'empty' nor a pack of this project.`, null)] }),
      };
    }
    this.files.set(name, files);
    // The new pack is a pack of the project from now on: plans, paths and outputs see it.
    const created = this.manifest(name);
    if (created) {
      this.model.packs.push(created);
      this.model.packs.sort((a, b) => a.name.localeCompare(b.name));
    }
    return { status: 201, body: result("saved", sha256Hex(files.get("pack.json")!), { files: [...files.keys()].sort() }) };
  }
}
