// The mock's renderers for the two example packs: sql-ddl (table, schema and, once the model has reference rows, seed units) and
// csharp-dapper (entity pairs, enums, value objects). Output paths follow the packs' pack.json;
// the text is plausible generated code, not the packs' templates.
import type { DatabaseTypeView, DatabaseView, RenderedFile, RoutineView, SequenceView, SqlObjectView, TableView, ViewView } from "@/api/types";
import { applyCase } from "./physical";

type Json = Record<string, unknown>;
const arr = (v: unknown): Json[] => (Array.isArray(v) ? (v as Json[]) : []);

export interface RenderUnit {
  pack: string;
  unit: string;
  /** Element id or resolved table key; null for model units. */
  elementId: string | null;
  unitKey: string;
  files: RenderedFile[];
}

const DIALECT_LABEL: Record<string, string> = {
  postgresql: "PostgreSQL",
  sqlserver: "SQL Server",
  sqlite: "SQLite",
  mysql: "MySQL",
  oracle: "Oracle",
};

function qualified(table: TableView): string {
  return table.schema ? `${table.schema}.${table.name}` : table.name;
}

export function tablePath(root: string, view: DatabaseView, table: TableView): string {
  const schema = table.schema ? `${table.schema}/` : "";
  return `${root}/${applyCase(view.name, "kebab")}/${schema}tables/${table.name}.sql`;
}

/**
 * A table's DDL options its file says and the resolved view does not carry (schemas/v1 table.json): each column entry's identity
 * seed, increment and generated always, each unique constraint's nulls-not-distinct and each index column's key prefix length,
 * by column id and by place.
 */
function tableFileOptions(table: TableView, docs: ReadonlyMap<string, Json> | undefined) {
  const file = docs?.get(table.key);
  const own = file && file.kind === "table" && file.origin !== "synthesized" ? file : undefined;
  return {
    identity: (key: string) => arr(own?.columns).find((c) => c.id === key)?.identity as { seed?: number; increment?: number; always?: boolean } | undefined,
    nullsNotDistinct: (at: number) => arr(own?.uniques)[at]?.nullsNotDistinct === true,
    length: (index: number, at: number) => {
      const n = arr(arr(own?.indexes)[index]?.columns)[at]?.length;
      return typeof n === "number" ? n : undefined;
    },
  };
}

/** A column's identity clause for a dialect, with the seed, increment and generated always the file sets. */
function identityClause(dialect: string, identity: { seed?: number; increment?: number; always?: boolean } | undefined): string {
  const seed = identity?.seed;
  const increment = identity?.increment;
  if (dialect === "sqlserver") return ` IDENTITY(${seed ?? 1}, ${increment ?? 1})`;
  if (dialect === "mysql") return " AUTO_INCREMENT";
  if (dialect === "sqlite") return "";
  const options = [seed !== undefined ? `START WITH ${seed}` : "", increment !== undefined ? `INCREMENT BY ${increment}` : ""].filter(Boolean).join(" ");
  return ` GENERATED ${identity?.always ? "ALWAYS" : "BY DEFAULT"} AS IDENTITY${options ? ` (${options})` : ""}`;
}

export function renderTable(view: DatabaseView, table: TableView, entityName: string | null, root: string, docs?: ReadonlyMap<string, Json>): RenderedFile {
  const options = tableFileOptions(table, docs);
  const lines = [
    "-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.",
    `-- Table ${qualified(table)} of database ${view.name} (${DIALECT_LABEL[view.dialect] ?? view.dialect}${view.version ? " " + view.version : ""}).`,
    entityName ? `-- Maps entity ${entityName}.` : table.isJunction ? "-- Junction table of a many-to-many relation." : "-- Designed table.",
    "",
    `CREATE TABLE ${qualified(table)} (`,
  ];
  // Comments as the pack writes them (its `comments` parameter is on by default): COMMENT ON, an extended property, or a trailing
  // line comment on SQLite.
  const sqlite = view.dialect === "sqlite";
  const body: string[] = table.columns.map(
    (c) =>
      `    ${c.name} ${c.nativeType}${c.identity ? identityClause(view.dialect, options.identity(c.key)) : ""} ${c.nullable ? "NULL" : "NOT NULL"}${sqlite && c.comment ? ` -- ${c.comment.replace(/\n/g, " ")}` : ""}`,
  );
  const nameOf = (key: string) => table.columns.find((c) => c.key === key)?.name ?? key;
  if (table.primaryKey) body.push(`    CONSTRAINT ${table.primaryKey.name} PRIMARY KEY (${table.primaryKey.columns.map(nameOf).join(", ")})`);
  table.uniques.forEach((u, i) =>
    body.push(
      `    CONSTRAINT ${u.name} UNIQUE${options.nullsNotDistinct(i) && view.dialect === "postgresql" ? " NULLS NOT DISTINCT" : ""} (${u.columns.map(nameOf).join(", ")})`,
    ),
  );
  lines.push(body.join(",\n"), ");");
  table.indexes.forEach((ix, n) => {
    const length = (at: number) => (view.dialect === "mysql" && options.length(n, at) !== undefined ? `(${options.length(n, at)})` : "");
    lines.push(
      "",
      `CREATE ${ix.unique ? "UNIQUE " : ""}INDEX ${ix.name} ON ${qualified(table)} (${ix.columns.map((c, at) => nameOf(c.column) + length(at) + (c.descending ? " DESC" : "")).join(", ")});`,
    );
  });
  if (!sqlite) {
    const literal = (text: string) => `'${text.replace(/'/g, "''")}'`;
    const comment = (text: string, column?: string) =>
      view.dialect === "sqlserver"
        ? `EXEC sys.sp_addextendedproperty @name = N'MS_Description', @value = N${literal(text)}, @level0type = N'SCHEMA', @level0name = N'${table.schema ?? "dbo"}', @level1type = N'TABLE', @level1name = N'${table.name}'${column ? `, @level2type = N'COLUMN', @level2name = N'${column}'` : ""};`
        : column
          ? `COMMENT ON COLUMN ${qualified(table)}.${column} IS ${literal(text)};`
          : `COMMENT ON TABLE ${qualified(table)} IS ${literal(text)};`;
    const comments = [...(table.comment ? [comment(table.comment)] : []), ...table.columns.filter((c) => c.comment).map((c) => comment(c.comment!, c.name))];
    if (comments.length) lines.push("", ...comments);
  }
  return { path: tablePath(root, view, table), text: lines.join("\n") + "\n", role: "main" };
}

export function renderSchema(view: DatabaseView, root: string, docs?: ReadonlyMap<string, Json>): RenderedFile {
  const byKey = new Map(view.tables.map((t) => [t.key, t]));
  const lines = [
    "-- Generated by Maquettiste (sql-ddl/schema). Do not edit; changes are overwritten.",
    `-- Database ${view.name} (${DIALECT_LABEL[view.dialect] ?? view.dialect}${view.version ? " " + view.version : ""}), ${view.tables.length} tables.`,
    "",
  ];
  if (view.defaultSchema) lines.push(`CREATE SCHEMA IF NOT EXISTS ${view.defaultSchema};`, "");
  // The schema script creates every object (sql-ddl's _objects.scriban), whatever objectScripts says, in the pack's DDL order:
  // SQL objects that run before, database types, sequences, tables, routines and views, then the other SQL objects.
  const objects = view.objects ?? [];
  for (const o of objects.filter((x) => x.phase === "before")) lines.push(objectSql(o), "");
  for (const t of view.types ?? []) lines.push(typeSql(t, view.dialect), "");
  for (const table of view.tables) lines.push(`\\i tables/${table.name}.sql`);
  for (const s of view.sequences) lines.push("", sequenceSql(s));
  for (const r of view.routines ?? []) lines.push("", routineSql(r, view.dialect));
  for (const v of view.views) lines.push("", viewSql(v, view.dialect, docs));
  for (const o of objects.filter((x) => x.phase === "after")) lines.push("", objectSql(o));
  const fks = view.tables.flatMap((t) => t.foreignKeys.map((fk) => ({ t, fk })));
  if (fks.length) lines.push("");
  for (const { t, fk } of fks) {
    const target = byKey.get(fk.referencedTable);
    const colName = (table: TableView | undefined, key: string) => table?.columns.find((c) => c.key === key)?.name ?? key;
    lines.push(
      `ALTER TABLE ${qualified(t)} ADD CONSTRAINT ${fk.name} FOREIGN KEY (${fk.columns.map((k) => colName(t, k)).join(", ")}) REFERENCES ${target ? qualified(target) : fk.referencedTable} (${fk.referencedColumns.map((k) => colName(target, k)).join(", ")}) ON DELETE ${fk.onDelete.toUpperCase()};`,
    );
  }
  return { path: `${root}/${applyCase(view.name, "kebab")}/schema.sql`, text: lines.join("\n") + "\n", role: "main" };
}

/** A reference type's rows as the mock's seed script needs them, with its storage strategy in the database. */
export interface SeedRows {
  name: string;
  pluralName?: string;
  /** The strategy in use in the database, or null when the packs decide. */
  strategy: string | null;
  rows: { code: string; label: string }[];
}

/**
 * The sql-ddl `seed` unit of a database, much simplified: one upsert of the rows of each type stored as a lookup table
 * (a table named after the type), one statement per type, separated by blank lines. Like the pack, it writes rows only
 * for lookup tables (a check constraint or a native type holds no rows), and renders for every database, with no
 * statement at all when no type is a lookup table there.
 */
export function renderSeed(view: DatabaseView, types: readonly SeedRows[], root: string): RenderedFile {
  const quote = (v: string) => `'${v.replaceAll("'", "''")}'`;
  const lines = ["-- Generated by Maquettiste (sql-ddl/seed). Do not edit; changes are overwritten.", `-- Database ${view.name}.`, ""];
  for (const t of types) {
    if (t.strategy !== "lookup-table" || !t.rows.length) continue;
    const table = applyCase(t.pluralName ?? `${t.name}s`, "snake");
    lines.push(
      `INSERT INTO ${table} (code, label) VALUES`,
      t.rows.map((r) => `  (${quote(r.code)}, ${quote(r.label)})`).join(",\n"),
      "ON CONFLICT (code) DO UPDATE SET label = EXCLUDED.label;",
      "",
    );
  }
  return { path: `${root}/${applyCase(view.name, "kebab")}/seed.sql`, text: lines.join("\n") + "\n", role: "main" };
}

const CS_TYPES: Record<string, string> = {
  string: "string",
  text: "string",
  bool: "bool",
  int16: "short",
  int32: "int",
  int64: "long",
  decimal: "decimal",
  float: "float",
  double: "double",
  date: "DateOnly",
  time: "TimeOnly",
  datetime: "DateTime",
  datetimeoffset: "DateTimeOffset",
  duration: "TimeSpan",
  uuid: "Guid",
  ulid: "Ulid",
  binary: "byte[]",
  json: "JsonDocument",
};

function csType(attr: Json, docs: Map<string, Json>): string {
  const type = attr.type as string | { ref: string };
  const base = typeof type === "string" ? (CS_TYPES[type] ?? "object") : String(docs.get(type.ref)?.name ?? "object");
  const nullable = attr.required === true ? "" : "?";
  return attr.collection === true ? `IReadOnlyList<${base}>` : base + nullable;
}

function packageFolder(doc: Json, docs: Map<string, Json>): string {
  const pkg = typeof doc.package === "string" ? docs.get(doc.package) : undefined;
  return pkg ? `${applyCase(String(pkg.name), "pascal")}/` : "";
}

export function renderCSharp(doc: Json, docs: Map<string, Json>, root: string, namespace: string): RenderedFile[] {
  const name = applyCase(String(doc.name), "pascal");
  const folder = packageFolder(doc, docs);
  const ns = folder ? `${namespace}.${folder.slice(0, -1)}` : namespace;
  const header = [
    "// <auto-generated>",
    `//   Generated by Maquettiste (csharp-dapper/${doc.kind}). Do not edit; changes are overwritten.`,
    "// </auto-generated>",
    "",
    `namespace ${ns};`,
    "",
  ];
  if (doc.kind === "enum") {
    const members = arr(doc.members).map((m) => `    ${String(m.name)}${m.value !== undefined ? ` = ${String(m.value)}` : ""},`);
    return [{ path: `${root}/${folder}${name}.g.cs`, text: [...header, `public enum ${name}`, "{", ...members, "}", ""].join("\n"), role: "main" }];
  }
  const props = arr(doc.attributes).map((a) => `    public ${csType(a, docs)} ${applyCase(String(a.name), "pascal")} { get; set; }`);
  if (doc.kind === "value-object") {
    return [
      {
        path: `${root}/${folder}${name}.g.cs`,
        text: [...header, `public sealed partial record ${name}`, "{", ...props, "}", ""].join("\n"),
        role: "main",
      },
    ];
  }
  const stereotypeProps: string[] = [];
  for (const key of (doc.stereotypes as string[] | undefined) ?? []) {
    const s = [...docs.values()].find((d) => d.kind === "stereotype" && d.key === key);
    for (const a of arr(s?.attributes)) stereotypeProps.push(`    public ${csType(a, docs)} ${applyCase(String(a.name), "pascal")} { get; set; }`);
  }
  const main: RenderedFile = {
    path: `${root}/${folder}${name}.g.cs`,
    text: [...header, `public partial class ${name}`, "{", ...props, ...stereotypeProps, "}", ""].join("\n"),
    role: "main",
  };
  const companion: RenderedFile = {
    path: `${root}/${folder}${name}.cs`,
    text: [
      `namespace ${ns};`,
      "",
      `// Hand-written part of ${name}. Generated once; Maquettiste never overwrites it.`,
      `public partial class ${name}`,
      "{",
      "}",
      "",
    ].join("\n"),
    role: "companion",
  };
  return [main, companion];
}

const qualifiedObject = (o: { schema: string | null; name: string }) => (o.schema ? `${o.schema}.${o.name}` : o.name);

/**
 * A view's CREATE VIEW, its body as resolved for the database's dialect, with what its file says beyond the resolved view: a
 * materialized view (PostgreSQL, Oracle), the column list (the declared columns' names) and WITH CHECK OPTION (not on SQLite, not
 * on a materialized view).
 */
export function viewSql(v: ViewView, dialect = "postgresql", docs?: ReadonlyMap<string, Json>): string {
  const file = docs?.get(v.id);
  const materialized = file?.materialized === true && (dialect === "postgresql" || dialect === "oracle");
  const columnList = file?.columnList === true && v.columns.length ? ` (${v.columns.map((c) => c.name).join(", ")})` : "";
  const check = file?.withCheckOption === true && dialect !== "sqlite" && !materialized ? "\nWITH CHECK OPTION" : "";
  return `CREATE ${materialized ? "MATERIALIZED " : ""}VIEW ${qualifiedObject(v)}${columnList} AS\n${v.body.trim()}${check};`;
}

/** A sequence's CREATE SEQUENCE. */
export function sequenceSql(s: SequenceView): string {
  const parts = [`CREATE SEQUENCE ${qualifiedObject(s)} AS ${s.nativeType}`, `START WITH ${s.start}`, `INCREMENT BY ${s.increment}`];
  if (s.min !== null) parts.push(`MINVALUE ${s.min}`);
  if (s.max !== null) parts.push(`MAXVALUE ${s.max}`);
  if (s.cache !== null) parts.push(`CACHE ${s.cache}`);
  parts.push(s.cycle ? "CYCLE" : "NO CYCLE");
  return `${parts.join(" ")};`;
}

/** The sql-ddl pack's per-view script (its `view` unit, written when the objectScripts parameter is on). */
export function renderView(view: DatabaseView, v: ViewView, root: string, docs?: ReadonlyMap<string, Json>): RenderedFile {
  const text = [
    "-- Generated by Maquettiste (sql-ddl/view). Do not edit; changes are overwritten.",
    `-- View ${qualifiedObject(v)} of database ${view.name} (${DIALECT_LABEL[view.dialect] ?? view.dialect}).`,
    "",
    viewSql(v, view.dialect, docs),
  ].join("\n");
  return { path: `${root}/${applyCase(view.name, "kebab")}/${v.schema ? `${v.schema}/` : ""}views/${v.name}.sql`, text: text + "\n", role: "main" };
}

/** The sql-ddl pack's per-sequence script (its `sequence` unit, written when the objectScripts parameter is on). */
export function renderSequence(view: DatabaseView, s: SequenceView, root: string): RenderedFile {
  const text = [
    "-- Generated by Maquettiste (sql-ddl/sequence). Do not edit; changes are overwritten.",
    `-- Sequence ${qualifiedObject(s)} of database ${view.name} (${DIALECT_LABEL[view.dialect] ?? view.dialect}).`,
    "",
    sequenceSql(s),
  ].join("\n");
  return { path: `${root}/${applyCase(view.name, "kebab")}/${s.schema ? `${s.schema}/` : ""}sequences/${s.name}.sql`, text: text + "\n", role: "main" };
}

/** A routine's CREATE FUNCTION or CREATE PROCEDURE, much simplified from the pack's: parameters, result, language, body. */
export function routineSql(r: RoutineView, dialect: string): string {
  const what = r.routineKind === "procedure" ? "PROCEDURE" : "FUNCTION";
  if (!r.hasBody) return `-- ${what} ${qualifiedObject(r)} has no body for ${dialect}.`;
  const sqlserver = dialect === "sqlserver";
  const parameters = r.parameters.map((p) => {
    const mode = p.mode === "in" ? "" : sqlserver ? "" : `${p.mode.toUpperCase()} `;
    const out = sqlserver && p.mode !== "in" ? " OUTPUT" : "";
    return `${mode}${sqlserver ? "@" : ""}${p.name} ${p.nativeType}${p.default !== null ? ` ${sqlserver ? "=" : "DEFAULT"} ${p.default}` : ""}${out}`;
  });
  const returns = !r.returns
    ? r.routineKind === "function" && !sqlserver
      ? " RETURNS void"
      : ""
    : r.returns.table
      ? ` RETURNS TABLE (${r.returns.table.map((c) => `${c.name} ${c.nativeType}`).join(", ")})`
      : ` RETURNS ${r.returns.nativeType}`;
  if (sqlserver) return `CREATE ${what} ${qualifiedObject(r)}(${parameters.join(", ")})${returns}\nAS\n${r.body.trim()};`;
  const marks = [`LANGUAGE ${r.language}`, ...(r.deterministic ? ["IMMUTABLE"] : []), ...(r.security === "definer" ? ["SECURITY DEFINER"] : [])];
  return `CREATE ${what} ${qualifiedObject(r)}(${parameters.join(", ")})${returns}\n${marks.join(" ")}\nAS $$\n${r.body.trim()}\n$$;`;
}

/** A database type's CREATE DOMAIN or CREATE TYPE (its definition for the dialect, else built from the structured form). */
export function typeSql(t: DatabaseTypeView, dialect: string): string {
  if (!t.isCreated && t.definition === null)
    return `-- Database type ${qualifiedObject(t)} (${t.typeKind}) is not created on ${dialect}; columns use what the type resolves to.`;
  const domain = t.typeKind === "domain" && dialect === "postgresql";
  if (t.definition !== null) return `CREATE ${domain ? "DOMAIN" : "TYPE"} ${qualifiedObject(t)} ${t.definition.trim()};`;
  switch (t.typeKind) {
    case "domain":
      return dialect === "sqlserver"
        ? `CREATE TYPE ${qualifiedObject(t)} FROM ${t.baseNativeType ?? "?"};${t.check ? ` -- CHECK (${t.check}): an alias type has no check.` : ""}`
        : `CREATE DOMAIN ${qualifiedObject(t)} AS ${t.baseNativeType ?? "?"}${t.check ? ` CHECK (${t.check})` : ""};`;
    case "enum":
      return `CREATE TYPE ${qualifiedObject(t)} AS ENUM (${t.members.map((m) => `'${m.replace(/'/g, "''")}'`).join(", ")});`;
    case "composite":
      return `CREATE TYPE ${qualifiedObject(t)} AS (${t.fields.map((f) => `${f.name} ${f.nativeType}`).join(", ")});`;
    case "range":
      return `CREATE TYPE ${qualifiedObject(t)} AS RANGE (SUBTYPE = ${t.subtypeNativeType ?? "?"});`;
  }
}

/** A SQL object's statements as written, or a comment when it has none for the dialect. */
export function objectSql(o: SqlObjectView): string {
  return o.hasBody ? o.body.trim() : `-- SQL object ${o.name} (${o.objectKind}) has no statements for this dialect.`;
}

/** One of the sql-ddl pack's per-object scripts (its `routine`, `database-type` and `sql-object` units, written when the
 * objectScripts parameter is on). */
function objectScript(
  view: DatabaseView,
  unit: string,
  header: string,
  o: { schema: string | null; name: string },
  folder: string,
  sql: string,
  root: string,
): RenderedFile {
  const text = [`-- Generated by Maquettiste (sql-ddl/${unit}). Do not edit; changes are overwritten.`, header, "", sql].join("\n");
  return { path: `${root}/${applyCase(view.name, "kebab")}/${o.schema ? `${o.schema}/` : ""}${folder}/${o.name}.sql`, text: text + "\n", role: "main" };
}

export function renderRoutine(view: DatabaseView, r: RoutineView, root: string): RenderedFile {
  const header = `-- ${r.routineKind === "procedure" ? "Procedure" : "Function"} ${qualifiedObject(r)} of database ${view.name} (${DIALECT_LABEL[view.dialect] ?? view.dialect}).`;
  return objectScript(view, "routine", header, r, "routines", routineSql(r, view.dialect), root);
}

export function renderDatabaseType(view: DatabaseView, t: DatabaseTypeView, root: string): RenderedFile {
  const header = `-- Database type ${qualifiedObject(t)} (${t.typeKind}) of database ${view.name} (${DIALECT_LABEL[view.dialect] ?? view.dialect}).`;
  return objectScript(view, "database-type", header, t, "types", typeSql(t, view.dialect), root);
}

export function renderSqlObject(view: DatabaseView, o: SqlObjectView, root: string): RenderedFile {
  const kind = o.objectKind ? `${o.objectKind[0].toUpperCase()}${o.objectKind.slice(1)}` : "Object";
  const header = `-- ${kind} ${o.name} of database ${view.name} (${DIALECT_LABEL[view.dialect] ?? view.dialect}), run ${o.phase} the tables.`;
  return objectScript(view, "sql-object", header, o, "objects", objectSql(o), root);
}
