-- Migration 0002 of database postgres (PostgreSQL): schema revision 1 to 2.
-- Written once by Maquettiste (sql-ddl/migration) from the schema diff. It is yours now: review it, adjust it and commit it.
-- Lines marked TODO need a decision the diff cannot make (data conversions, sequence restarts).

BEGIN;

DROP MATERIALIZED VIEW sales.order_counts;

DROP VIEW sales.active_customers;

DROP VIEW sales.customer_order_totals;

DROP VIEW sales.customer_orders;

-- Views dropped and created again lose the privileges granted on them: grant them again (this migration does not), or keep the grants in SQL objects that depend on the views, which a migration runs again.

CREATE SCHEMA IF NOT EXISTS sales;

ALTER TABLE sales.order_lines RENAME TO order_items;

COMMENT ON TABLE sales.customers IS 'Customers who place orders, with their balance.';

ALTER TABLE sales.orders DROP CONSTRAINT fk_orders_customer;

ALTER TABLE sales.customers DROP CONSTRAINT ck_customers_balance;

ALTER TABLE sales.customers DROP CONSTRAINT uq_customers_email;

ALTER INDEX sales.ix_customers_code RENAME TO ix_customers_code_lookup;

DROP INDEX sales.ix_orders_placed_on;

ALTER TABLE sales.orders RENAME CONSTRAINT pk_orders TO pk_orders_id;

ALTER TABLE sales.order_items ALTER COLUMN line_no ADD GENERATED BY DEFAULT AS IDENTITY;

DO $$ BEGIN PERFORM setval(pg_get_serial_sequence('sales.order_items', 'line_no'), GREATEST(COALESCE(MAX(line_no), 0) + 1, 1), false) FROM sales.order_items; END $$;

ALTER TABLE sales.order_items RENAME COLUMN product_code TO sku;

ALTER TABLE sales.order_items ALTER COLUMN quantity TYPE bigint USING quantity::bigint;

-- TODO: convert existing values of order_items.quantity (type: int32 -> int64); the cast keeps each value as it is.

ALTER TABLE sales.customers ADD COLUMN phone varchar(30) NULL;

COMMENT ON COLUMN sales.customers.phone IS 'Contact phone.';

ALTER TABLE sales.customers ADD COLUMN loyalty integer NULL;

ALTER TABLE sales.customers ADD COLUMN vip boolean NOT NULL DEFAULT false;

ALTER TABLE sales.customers ALTER COLUMN id TYPE bigint USING id::bigint;

ALTER TABLE sales.customers ALTER COLUMN id SET GENERATED ALWAYS SET INCREMENT BY 2;

-- TODO: convert existing values of customers.id (type: int32 -> int64); the cast keeps each value as it is.

ALTER TABLE sales.customers ALTER COLUMN name TYPE varchar(150) COLLATE "C";

ALTER TABLE sales.customers ALTER COLUMN email DROP NOT NULL;

ALTER TABLE sales.customers RENAME COLUMN notes TO remarks;

COMMENT ON COLUMN sales.customers.remarks IS 'Remarks about the customer.';

ALTER TABLE sales.customers ALTER COLUMN balance SET DEFAULT 10;

ALTER TABLE sales.orders ALTER COLUMN customer_id TYPE bigint USING customer_id::bigint;

-- TODO: convert existing values of orders.customer_id (type: int32 -> int64); the cast keeps each value as it is.

CREATE TABLE sales.notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id bigint NULL,
    body text NOT NULL DEFAULT '-',
    CONSTRAINT pk_notes PRIMARY KEY (id),
    CONSTRAINT fk_notes_customer FOREIGN KEY (customer_id) REFERENCES sales.customers (id) ON DELETE SET NULL
);
CREATE INDEX ix_notes_customer ON sales.notes (customer_id);

ALTER TABLE sales.customers ADD CONSTRAINT uq_customers_mail UNIQUE NULLS NOT DISTINCT (email);

ALTER TABLE sales.customers ADD CONSTRAINT ck_customers_balance CHECK (balance >= -100);

ALTER TABLE sales.orders ADD CONSTRAINT ck_orders_total CHECK (total >= 0);

CREATE INDEX ix_orders_placed_on ON sales.orders (placed_on DESC, number);

ALTER TABLE sales.orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES sales.customers (id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

CREATE VIEW sales.customer_order_list AS
SELECT c.id, c.name, o.number FROM sales.customers c JOIN sales.orders o ON o.customer_id = c.id;
COMMENT ON VIEW sales.customer_order_list IS 'Every customer with each order.';

CREATE VIEW sales.customer_order_totals (customer_id, order_count) AS
SELECT id, count(*) FROM sales.customer_order_list GROUP BY id;

CREATE VIEW sales.active_customers AS
SELECT id, code, status FROM sales.customers WHERE status = 'A'
WITH CHECK OPTION;

CREATE MATERIALIZED VIEW sales.order_counts AS
SELECT customer_id, count(*) AS order_count FROM sales.orders GROUP BY customer_id;
COMMENT ON MATERIALIZED VIEW sales.order_counts IS 'Orders per customer, stored.';

ALTER SEQUENCE sales.order_numbers RENAME TO order_number_seq;

ALTER SEQUENCE sales.order_number_seq INCREMENT BY 5 MAXVALUE 999999999 CYCLE;

COMMIT;
