// The reference-data close-out (reference-types-seeds-localization.md §5 steps 4, 7, 8): the standard strategies hint,
// the seed column drop on field removal, the hover card codes, the per-seed CSV choice, the Storage preview filter
// and header editing in a content locale.
import { describe, expect, it } from "vitest";
import type { TranslationEntry } from "@/api/types";
import { csvSeedFor, dropSeedColumns, firstCodes, removedFieldIds } from "@/workspaces/reference-data/rowsModel";
import { needsStandardStrategies, snakeNames, STANDARD_STRATEGIES, typeStatements, withStandardStrategies } from "@/workspaces/reference-data/storageChoices";
import { headerEdit, headerEntry } from "@/l10n/header";

describe("standard storage strategies", () => {
  it("are offered while the project declares none and added without touching declared ones", () => {
    expect(needsStandardStrategies({})).toBe(true);
    expect(needsStandardStrategies({ referenceData: { strategies: {} } })).toBe(true);
    expect(needsStandardStrategies({ referenceData: { strategies: { table: {} } } })).toBe(false);
    expect(needsStandardStrategies(undefined)).toBe(false);
    const next = withStandardStrategies({ name: "p", referenceData: { strategies: { check: { description: "mine" } } as Record<string, unknown> } });
    const strategies = next.referenceData?.strategies ?? {};
    expect(Object.keys(strategies).sort()).toEqual(["check", "lookup-table", "native"]);
    expect(strategies.check).toEqual({ description: "mine" });
    expect(strategies["lookup-table"]).toEqual(STANDARD_STRATEGIES["lookup-table"]);
    expect((strategies.native as { collections: unknown }).collections).toEqual({ "*": false, postgresql: true });
  });
});

describe("seed columns and codes", () => {
  it("drops a removed field's column and its cells from every row", () => {
    const seed = { columns: ["code", "label", "F1", "F2"], rows: [{ values: ["kg", "Kilogram", 1, "x"] }, { values: ["g", "Gram"] }] };
    const removed = removedFieldIds({ attributes: [{ id: "F1" }, { id: "F2" }] }, { attributes: [{ id: "F2" }] });
    expect([...removed]).toEqual(["F1"]);
    expect(dropSeedColumns(seed, removed)).toBe(true);
    expect(seed.columns).toEqual(["code", "label", "F2"]);
    expect(seed.rows.map((r) => r.values)).toEqual([
      ["kg", "Kilogram", "x"],
      ["g", "Gram"],
    ]);
    expect(dropSeedColumns(seed, new Set(["F9"]))).toBe(false);
  });

  it("lists the first codes across seeds and counts the rest", () => {
    const seeds = [
      { columns: ["code", "label"], rows: [{ values: ["a"] }, { values: ["b"] }, { values: ["c"] }] },
      { columns: ["label", "code"], rows: [{ values: ["D", "d"] }, { values: ["E", "e"] }, { values: ["F", "f"] }] },
    ];
    expect(firstCodes(seeds)).toEqual({ codes: ["a", "b", "c", "d", "e"], more: 1 });
    expect(firstCodes([])).toEqual({ codes: [], more: 0 });
  });

  it("imports and exports the picked seed, else the first", () => {
    const seeds = [{ id: "A" }, { id: "B" }];
    expect(csvSeedFor(seeds, null)?.id).toBe("A");
    expect(csvSeedFor(seeds, "B")?.id).toBe("B");
    expect(csvSeedFor(seeds, "gone")?.id).toBe("A");
    expect(csvSeedFor([], "B")).toBeNull();
  });
});

describe("storage preview", () => {
  it("keeps the statements that name the type's objects or quote its codes", () => {
    const script = [
      "-- Generated by Maquettiste (sql-ddl/seed).",
      "CREATE TABLE IF NOT EXISTS units_of_measure (code varchar(8) PRIMARY KEY);",
      "ALTER TABLE product ADD CONSTRAINT ck_product_unit_ref CHECK (unit IN ('kg', 'g'));",
      "CREATE TYPE country_t AS ENUM ('FR');",
      "-- maquettiste:keep id=seed-data",
    ].join("\n\n");
    const names = snakeNames("UnitOfMeasure", "UnitsOfMeasure");
    expect(names).toEqual(["unit_of_measure", "units_of_measure"]);
    expect(typeStatements(script, names, ["kg", "g"])).toEqual([
      "CREATE TABLE IF NOT EXISTS units_of_measure (code varchar(8) PRIMARY KEY);",
      "ALTER TABLE product ADD CONSTRAINT ck_product_unit_ref CHECK (unit IN ('kg', 'g'));",
    ]);
    expect(typeStatements(script, snakeNames("Country"), [])).toEqual(["CREATE TYPE country_t AS ENUM ('FR');"]);
  });
});

describe("header editing in a content locale", () => {
  const entry = { id: "E", field: "displayName", translation: "Client", shard: "s", shardHash: "h" } as unknown as TranslationEntry;
  it("edits the locale's entry only while a non-default locale is in effect", () => {
    expect(headerEntry(null, [entry], "E", "displayName")).toBeNull();
    expect(headerEntry("fr", [entry], "E", "displayName")).toBe(entry);
    expect(headerEntry("fr", [entry], "E", "pluralName")).toBeNull();
  });
  it("writes a changed text, clears on empty and skips an unchanged one", () => {
    expect(headerEdit(entry, "Cliente")).toEqual({ id: "E", field: "displayName", value: "Cliente" });
    expect(headerEdit(entry, "  ")).toEqual({ id: "E", field: "displayName", value: null });
    expect(headerEdit(entry, "Client")).toBeNull();
  });
});
