-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table billing.invoices of database main (PostgreSQL 16).
-- Maps entity Invoice.

CREATE TABLE billing.invoices (
    id uuid NOT NULL,
    number varchar(32) NOT NULL,
    issued_on date NOT NULL,
    total_amount numeric(18,2) NULL,
    total_currency varchar(3) NULL,
    status varchar(1) NOT NULL DEFAULT 'D',
    notes text NULL,
    created_at timestamptz(6) NOT NULL,
    updated_at timestamptz(6) NULL,
    deleted_at timestamptz(6) NULL,
    reason varchar(200) NULL,
    discriminator varchar(64) NOT NULL,
    customer_id uuid NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id),
    CONSTRAINT uq_invoices_number UNIQUE (number),
    CONSTRAINT fk_invoices_customer_id FOREIGN KEY (customer_id) REFERENCES billing.customers (id) ON DELETE RESTRICT,
    CONSTRAINT ck_invoice_status CHECK (status in ('D', 'I', 'P', 'V'))
);
CREATE INDEX ix_invoices_issued_on ON billing.invoices (issued_on DESC);
COMMENT ON COLUMN billing.invoices.number IS 'Assigned on issue.';
