// Generated by Maquettiste (csharp-dapper/registrations). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;

namespace App.Model.Queries;

/// <summary>The Dapper query classes of the model.</summary>
/// <example><code>QueryRegistrations.Register((service, implementation) => services.AddScoped(service, implementation));</code></example>
public static partial class QueryRegistrations
{
    /// <summary>Every query class: the interface to register and the class that implements it.</summary>
    public static IReadOnlyList<(Type Service, Type Implementation)> All { get; } =
    [
        (typeof(IFindCustomersWithIssuedInvoicesQuery), typeof(FindCustomersWithIssuedInvoicesQuery)),
        (typeof(IInvoicesByCustomerQuery), typeof(InvoicesByCustomerQuery)),
        (typeof(IRevenueByMonthQuery), typeof(RevenueByMonthQuery)),
    ];

    /// <summary>Calls <paramref name="register"/> once per query class.</summary>
    public static void Register(Action<Type, Type> register)
    {
        ArgumentNullException.ThrowIfNull(register);
        foreach (var (service, implementation) in All)
            register(service, implementation);
    }
}
