-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table dbo.ingredients of database reporting (SQL Server).

CREATE TABLE dbo.ingredients (
    sku nvarchar(32) NOT NULL,
    name nvarchar(120) NOT NULL,
    default_unit nvarchar(8) NOT NULL CONSTRAINT df_ingredients_default_unit DEFAULT N'g',
    preferred_unit nvarchar(8) NULL,
    substitute_sku nvarchar(32) NULL,
    CONSTRAINT pk_ingredients PRIMARY KEY (sku),
    CONSTRAINT fk_ingredients_substitute_sku FOREIGN KEY (substitute_sku) REFERENCES dbo.ingredients (sku)
);
