-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table dbo.recipes of database reporting (SQL Server).

CREATE TABLE dbo.recipes (
    code nvarchar(32) NOT NULL,
    name nvarchar(120) NOT NULL,
    CONSTRAINT pk_recipes PRIMARY KEY (code)
);
