-- Generated by Maquettiste (sql-ddl/seed). Edit only inside the protected region below; the rest is regenerated.
-- Seed data of database main (PostgreSQL 16). Run it after the schema script or the migrations; the lookup rows can run again.

-- Lookup rows of product_statuses.
INSERT INTO northwind.product_statuses (id, code, name) VALUES
    (0, 'DRAFT', 'Draft'),
    (1, 'ACTIVE', 'Active'),
    (2, 'PHASEOUT', 'PhasingOut'),
    (3, 'DISC', 'Discontinued'),
    (4, 'BLOCK', 'Blocked')
ON CONFLICT (id) DO UPDATE SET code = excluded.code, name = excluded.name;

-- Lookup rows of shipment_statuses.
INSERT INTO northwind.shipment_statuses (id, code, name) VALUES
    (0, 'PLAN', 'Planned'),
    (1, 'PICK', 'Picking'),
    (2, 'PACK', 'Packed'),
    (3, 'SHIP', 'Shipped'),
    (4, 'TRANSIT', 'InTransit'),
    (5, 'DLVD', 'Delivered'),
    (6, 'EXCEPT', 'DeliveryException'),
    (7, 'CANCEL', 'Cancelled')
ON CONFLICT (id) DO UPDATE SET code = excluded.code, name = excluded.name;

-- maquettiste:keep id=seed-data
-- Hand-written seed data (kept across regeneration): the currencies and countries Northwind trades in.
INSERT INTO northwind.currencies (code, numeric_code, name, symbol, minor_units) VALUES
    ('USD', '840', 'US Dollar', '$', 2),
    ('CAD', '124', 'Canadian Dollar', 'CA$', 2),
    ('MXN', '484', 'Mexican Peso', 'MX$', 2),
    ('EUR', '978', 'Euro', '€', 2),
    ('GBP', '826', 'Pound Sterling', '£', 2),
    ('JPY', '392', 'Yen', '¥', 0)
ON CONFLICT (code) DO UPDATE SET numeric_code = excluded.numeric_code, name = excluded.name, symbol = excluded.symbol, minor_units = excluded.minor_units;

INSERT INTO northwind.countries (code, alpha3_code, numeric_code, name, calling_code, is_eu_member, currency_code) VALUES
    ('US', 'USA', '840', 'United States of America', '+1', false, 'USD'),
    ('CA', 'CAN', '124', 'Canada', '+1', false, 'CAD'),
    ('MX', 'MEX', '484', 'Mexico', '+52', false, 'MXN'),
    ('DE', 'DEU', '276', 'Germany', '+49', true, 'EUR'),
    ('FR', 'FRA', '250', 'France', '+33', true, 'EUR'),
    ('GB', 'GBR', '826', 'United Kingdom of Great Britain and Northern Ireland', '+44', false, 'GBP'),
    ('JP', 'JPN', '392', 'Japan', '+81', false, 'JPY')
ON CONFLICT (code) DO UPDATE SET alpha3_code = excluded.alpha3_code, numeric_code = excluded.numeric_code, name = excluded.name,
    calling_code = excluded.calling_code, is_eu_member = excluded.is_eu_member, currency_code = excluded.currency_code;
-- maquettiste:end-keep
