-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table orders of database oracle (Oracle).

CREATE TABLE orders (
    id number(19) DEFAULT order_numbers.NEXTVAL NOT NULL,
    "number" varchar2(20 char) NOT NULL,
    customer_id number(10) NOT NULL,
    total number(12,2) DEFAULT 0 NOT NULL,
    placed_on date NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_customer_number UNIQUE (customer_id, "number"),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX ix_orders_placed_on ON orders (placed_on DESC);
