-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table orders of database mysql (MySQL).

CREATE TABLE orders (
    id bigint NOT NULL AUTO_INCREMENT,
    number varchar(16) NOT NULL,
    customer_id bigint NOT NULL,
    total decimal(12,2) NOT NULL DEFAULT 0,
    placed_on date NULL,
    CONSTRAINT pk_orders_id PRIMARY KEY (id),
    CONSTRAINT uq_orders_customer_number UNIQUE (customer_id, number),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT ck_orders_total CHECK (total >= 0)
);
