-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table order_lines of database mysql (MySQL).

CREATE TABLE IF NOT EXISTS order_lines (
    order_id bigint NOT NULL,
    line_no int NOT NULL,
    product_code char(20) NOT NULL,
    quantity int NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0),
    INDEX ix_order_lines_product (product_code)
);
