-- Migration 0001 of database pg (PostgreSQL): schema revision 0 to 1.
-- Written once by Maquettiste (sql-ddl/migration) from the schema diff. It is yours now: review it, adjust it and commit it.
-- Lines marked TODO need a decision the diff cannot make (data conversions, sequence restarts).

BEGIN;

CREATE SCHEMA IF NOT EXISTS app;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE app.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    title varchar(200) NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    embedding vector(3) NULL,
    CONSTRAINT pk_documents PRIMARY KEY (id)
) WITH (autovacuum_enabled = true, autovacuum_vacuum_scale_factor = 0.03, fillfactor = 90);
CREATE INDEX ix_documents_title_trgm ON app.documents USING gin (title gin_trgm_ops);
CREATE INDEX ix_documents_created ON app.documents USING brin (created_at) WITH (pages_per_range = 32);
CREATE INDEX ix_documents_embedding ON app.documents USING hnsw (embedding vector_cosine_ops) WITH (ef_construction = 64, m = 16);

CREATE TABLE app.room_rates (
    room_id bigint NOT NULL,
    valid tstzrange NOT NULL,
    rate numeric(10,2) NOT NULL,
    CONSTRAINT pk_room_rates PRIMARY KEY (room_id, valid WITHOUT OVERLAPS)
);

CREATE TABLE app.bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id bigint NOT NULL,
    guest_id bigint NOT NULL,
    stay tstzrange NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_bookings_rate FOREIGN KEY (room_id, PERIOD stay) REFERENCES app.room_rates (room_id, PERIOD valid)
);

CREATE TABLE app.reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id bigint NOT NULL,
    during tstzrange NOT NULL,
    cancelled boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_reservations PRIMARY KEY (id),
    CONSTRAINT ex_reservations_overlap EXCLUDE USING gist (room_id WITH =, during WITH &&) WHERE (NOT cancelled)
);

CREATE TABLE app.audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    occurred_at timestamptz(6) NOT NULL,
    payload text NULL,
    CONSTRAINT pk_audit_events PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE TABLE app.audit_events_2026_01 PARTITION OF app.audit_events FOR VALUES FROM ('2026-01-01') TO ('2026-02-01') WITH (autovacuum_enabled = true, autovacuum_vacuum_scale_factor = 0.03, fillfactor = 70);
CREATE TABLE app.audit_events_2026_02 PARTITION OF app.audit_events FOR VALUES FROM ('2026-02-01') TO ('2026-02-15') WITH (autovacuum_enabled = true, autovacuum_vacuum_scale_factor = 0.03, fillfactor = 70);
CREATE TABLE app.audit_events_default PARTITION OF app.audit_events DEFAULT WITH (autovacuum_enabled = true, autovacuum_vacuum_scale_factor = 0.03, fillfactor = 70);

CREATE FUNCTION app.current_tenant()
RETURNS bigint
LANGUAGE sql
STABLE
AS $$
SELECT coalesce(current_setting('app.tenant', true), '0')::bigint
$$;

CREATE FUNCTION app.tenant_count()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = app, pg_temp
AS $$
SELECT count(*) FROM pg_catalog.pg_namespace
$$;

CREATE VIEW app.my_documents WITH (security_barrier = true, security_invoker = true) AS
SELECT id, title FROM app.documents WHERE tenant_id = app.current_tenant();

GRANT SELECT ON app.my_documents TO PUBLIC;

COMMIT;
