-- Migration 0001 of database oracle (Oracle): schema revision 0 to 1.
-- Written once by Maquettiste (sql-ddl/migration) from the schema diff. It is yours now: review it, adjust it and commit it.
-- Lines marked TODO need a decision the diff cannot make (data conversions, sequence restarts).

-- Oracle commits each DDL statement: run the script once, top to bottom.

CREATE SEQUENCE order_numbers START WITH 1000 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE audit_numbers START WITH 1 INCREMENT BY 1;

CREATE TABLE customers (
    id number(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 100) NOT NULL,
    code char(10 char) NOT NULL,
    name nvarchar2(100) NOT NULL,
    email varchar2(200 char) NOT NULL,
    notes clob NULL,
    balance number(12,2) DEFAULT 0 NOT NULL,
    status varchar2(1 char) DEFAULT 'A' NOT NULL,
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    balance_twice number(14,2) GENERATED ALWAYS AS (balance * 2) VIRTUAL,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_status CHECK (status IN ('A', 'I')),
    CONSTRAINT ck_customers_balance CHECK (balance >= 0)
);
CREATE INDEX ix_customers_name ON customers (name, created_at DESC);
CREATE UNIQUE INDEX ix_customers_code ON customers (code);
CREATE INDEX ix_customers_email_lower ON customers ((lower(email)));
COMMENT ON TABLE customers IS 'Customers who place orders.';
COMMENT ON COLUMN customers.notes IS 'Free-form notes.';

CREATE TABLE orders (
    id number(19) DEFAULT order_numbers.NEXTVAL NOT NULL,
    "number" varchar2(20 char) NOT NULL,
    customer_id number(10) NOT NULL,
    total number(12,2) DEFAULT 0 NOT NULL,
    placed_on date NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_customer_number UNIQUE (customer_id, "number"),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX ix_orders_placed_on ON orders (placed_on DESC);

CREATE TABLE order_lines (
    order_id number(19) NOT NULL,
    line_no number(10) NOT NULL,
    product_code char(20 char) NOT NULL,
    quantity number(10) NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0)
);
CREATE INDEX ix_order_lines_product ON order_lines (product_code);

CREATE VIEW customer_orders AS
SELECT c.id, c.name, o.number FROM customers c JOIN orders o ON o.customer_id = c.id;
COMMENT ON TABLE customer_orders IS 'Customers with their orders.';

CREATE VIEW customer_order_totals (customer_id, order_count) AS
SELECT id, count(*) FROM customer_orders GROUP BY id;

CREATE VIEW active_customers AS
SELECT id, code, status FROM customers WHERE status = 'A'
WITH CHECK OPTION;

CREATE MATERIALIZED VIEW order_counts AS
SELECT customer_id, count(*) AS order_count FROM orders GROUP BY customer_id;
COMMENT ON MATERIALIZED VIEW order_counts IS 'Orders per customer, stored.';
