-- Migration 0002 of database oracle (Oracle): schema revision 1 to 2.
-- Written once by Maquettiste (sql-ddl/migration) from the schema diff. It is yours now: review it, adjust it and commit it.
-- Lines marked TODO need a decision the diff cannot make (data conversions, sequence restarts).

-- Oracle commits each DDL statement: run the script once, top to bottom.

DROP VIEW customer_order_totals;

ALTER TABLE order_lines RENAME TO order_items;

COMMENT ON TABLE customers IS 'Customers who place orders, with their balance.';

ALTER TABLE orders DROP CONSTRAINT fk_orders_customer;

ALTER TABLE customers DROP CONSTRAINT ck_customers_balance;

ALTER TABLE customers RENAME CONSTRAINT uq_customers_email TO uq_customers_mail;

ALTER INDEX ix_customers_code RENAME TO ix_customers_code_lookup;

DROP INDEX ix_orders_placed_on;

ALTER TABLE orders RENAME CONSTRAINT pk_orders TO pk_orders_id;

ALTER TABLE order_items MODIFY (line_no GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));

ALTER TABLE order_items RENAME COLUMN product_code TO sku;

ALTER TABLE order_items MODIFY (quantity number(19));

-- TODO: convert existing values of order_items.quantity (type: int32 -> int64); the cast keeps each value as it is.

ALTER TABLE customers ADD (phone varchar2(30 char) NULL);

COMMENT ON COLUMN customers.phone IS 'Contact phone.';

ALTER TABLE customers ADD (loyalty number(10) NULL);

ALTER TABLE customers ADD (vip number(1) DEFAULT 0 NOT NULL);

ALTER TABLE customers MODIFY (id number(19));

ALTER TABLE customers MODIFY (id GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE INCREMENT BY 2));

-- TODO: convert existing values of customers.id (type: int32 -> int64); the cast keeps each value as it is.

ALTER TABLE customers MODIFY (name nvarchar2(150));

ALTER TABLE customers MODIFY (email NULL);

ALTER TABLE customers RENAME COLUMN notes TO remarks;

COMMENT ON COLUMN customers.remarks IS 'Remarks about the customer.';

ALTER TABLE customers MODIFY (balance DEFAULT 10);

ALTER TABLE orders MODIFY (customer_id number(19));

-- TODO: convert existing values of orders.customer_id (type: int32 -> int64); the cast keeps each value as it is.

CREATE TABLE notes (
    id number(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id number(19) NULL,
    body clob DEFAULT '-' NOT NULL,
    CONSTRAINT pk_notes PRIMARY KEY (id),
    CONSTRAINT fk_notes_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL
);
CREATE INDEX ix_notes_customer ON notes (customer_id);

ALTER TABLE customers ADD CONSTRAINT ck_customers_balance CHECK (balance >= -100);

ALTER TABLE orders ADD CONSTRAINT ck_orders_total CHECK (total >= 0);

CREATE INDEX ix_orders_placed_on ON orders (placed_on DESC, "number");

ALTER TABLE orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

RENAME customer_orders TO customer_order_list;

COMMENT ON TABLE customer_order_list IS 'Every customer with each order.';

CREATE VIEW customer_order_totals (customer_id, order_count) AS
SELECT id, count(*) FROM customer_order_list GROUP BY id;

RENAME order_numbers TO order_number_seq;

ALTER SEQUENCE order_number_seq INCREMENT BY 5 MAXVALUE 999999999 CYCLE;
