// Generated by Maquettiste (csharp-dapper/repository). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Dapper;

namespace App.Model.Billing;

/// <summary>Reads and writes <see cref="InvoiceLine"/> rows in invoice_lines (database local, sqlite).</summary>
public partial interface IInvoiceLineRepository
{
    /// <summary>Returns the entity with the given key, or null.</summary>
    Task<InvoiceLine?> GetAsync(string id, CancellationToken cancellationToken = default);

    /// <summary>Returns a page of entities in key order.</summary>
    Task<IReadOnlyList<InvoiceLine>> ListAsync(int skip = 0, int take = 100, CancellationToken cancellationToken = default);

    /// <summary>Inserts the entity.</summary>
    Task InsertAsync(InvoiceLine entity, CancellationToken cancellationToken = default);

    /// <summary>Updates the entity; returns false when no row has its key.</summary>
    Task<bool> UpdateAsync(InvoiceLine entity, CancellationToken cancellationToken = default);

    /// <summary>Deletes the entity with the given key; returns false when there was none.</summary>
    Task<bool> DeleteAsync(string id, CancellationToken cancellationToken = default);
}

/// <summary>The Dapper implementation of <see cref="IInvoiceLineRepository"/> over an open or closed <see cref="IDbConnection"/>.</summary>
public partial class InvoiceLineRepository(IDbConnection connection, IDbTransaction? transaction = null) : IInvoiceLineRepository
{
    private const string Columns = """
        id AS Id,
        quantity AS Quantity,
        unit_price_amount AS UnitPriceAmount,
        unit_price_currency AS UnitPriceCurrency,
        description AS Description,
        invoice_id AS InvoiceId,
        product_id AS ProductId
        """;

    private const string SelectSql = "SELECT " + Columns + " FROM invoice_lines WHERE id = @Id";

    private const string ListSql = "SELECT " + Columns + " FROM invoice_lines ORDER BY id LIMIT @Take OFFSET @Skip";

    private const string InsertSql = """
        INSERT INTO invoice_lines (id, quantity, unit_price_amount, unit_price_currency, description, invoice_id, product_id)
        VALUES (@Id, @Quantity, @UnitPriceAmount, @UnitPriceCurrency, @Description, @InvoiceId, @ProductId)
        """;

    private const string UpdateSql = """
        UPDATE invoice_lines SET quantity = @Quantity, unit_price_amount = @UnitPriceAmount, unit_price_currency = @UnitPriceCurrency, description = @Description, invoice_id = @InvoiceId, product_id = @ProductId
        WHERE id = @Id
        """;

    private const string DeleteSql = "DELETE FROM invoice_lines WHERE id = @Id";

    /// <inheritdoc/>
    public async Task<InvoiceLine?> GetAsync(string id, CancellationToken cancellationToken = default)
    {
        var row = await connection.QuerySingleOrDefaultAsync<Row>(new CommandDefinition(SelectSql, new { Id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return row is null ? null : Row.ToEntity(row);
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyList<InvoiceLine>> ListAsync(int skip = 0, int take = 100, CancellationToken cancellationToken = default)
    {
        var rows = await connection.QueryAsync<Row>(new CommandDefinition(ListSql, new { Skip = skip, Take = take }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows.Select(Row.ToEntity).ToList();
    }

    /// <inheritdoc/>
    public async Task InsertAsync(InvoiceLine entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        if (string.IsNullOrEmpty(entity.Id))
            entity.Id = UlidGenerator.NewUlid();
        await connection.ExecuteAsync(new CommandDefinition(InsertSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    /// <inheritdoc/>
    public async Task<bool> UpdateAsync(InvoiceLine entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return await connection.ExecuteAsync(new CommandDefinition(UpdateSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <inheritdoc/>
    public async Task<bool> DeleteAsync(string id, CancellationToken cancellationToken = default)
    {
        return await connection.ExecuteAsync(new CommandDefinition(DeleteSql, new { Id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <summary>One row of invoice_lines, column by column, as Dapper reads and writes it.</summary>
    private sealed class Row
    {
        public string Id { get; set; } = default!;
        public int Quantity { get; set; }
        public decimal UnitPriceAmount { get; set; }
        public string UnitPriceCurrency { get; set; } = default!;
        public string? Description { get; set; }
        public Guid InvoiceId { get; set; }
        public Guid ProductId { get; set; }

        public static InvoiceLine ToEntity(Row row) => new()
        {
            Id = row.Id,
            Quantity = row.Quantity,
            UnitPrice = new Money { Amount = row.UnitPriceAmount, Currency = row.UnitPriceCurrency },
            Description = row.Description,
            InvoiceId = row.InvoiceId,
            ProductId = row.ProductId,
        };

        public static Row From(InvoiceLine entity) => new()
        {
            Id = entity.Id,
            Quantity = entity.Quantity,
            UnitPriceAmount = entity.UnitPrice.Amount,
            UnitPriceCurrency = entity.UnitPrice.Currency,
            Description = entity.Description,
            InvoiceId = entity.InvoiceId,
            ProductId = entity.ProductId,
        };
    }
}
