// Generated by Maquettiste (csharp-dapper/repository). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Dapper;

namespace App.Model.Billing;

/// <summary>Reads and writes <see cref="InvoiceNote"/> rows in invoice_notes (database local, sqlite).</summary>
public partial interface IInvoiceNoteRepository
{
    /// <summary>Returns the entity with the given key, or null.</summary>
    Task<InvoiceNote?> GetAsync(Guid id, CancellationToken cancellationToken = default);

    /// <summary>Returns a page of entities in key order.</summary>
    Task<IReadOnlyList<InvoiceNote>> ListAsync(int skip = 0, int take = 100, CancellationToken cancellationToken = default);

    /// <summary>Inserts the entity.</summary>
    Task InsertAsync(InvoiceNote entity, CancellationToken cancellationToken = default);

    /// <summary>Updates the entity; returns false when no row has its key.</summary>
    Task<bool> UpdateAsync(InvoiceNote entity, CancellationToken cancellationToken = default);

    /// <summary>Deletes the entity with the given key; returns false when there was none.</summary>
    Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default);
}

/// <summary>The Dapper implementation of <see cref="IInvoiceNoteRepository"/> over an open or closed <see cref="IDbConnection"/>.</summary>
public partial class InvoiceNoteRepository(IDbConnection connection, IDbTransaction? transaction = null) : IInvoiceNoteRepository
{
    private const string Columns = """
        id AS Id,
        invoice_id AS InvoiceId,
        body AS Body,
        created_at AS CreatedAt
        """;

    private const string SelectSql = "SELECT " + Columns + " FROM invoice_notes WHERE id = @Id";

    private const string ListSql = "SELECT " + Columns + " FROM invoice_notes ORDER BY id LIMIT @Take OFFSET @Skip";

    private const string InsertSql = """
        INSERT INTO invoice_notes (id, invoice_id, body, created_at)
        VALUES (@Id, @InvoiceId, @Body, @CreatedAt)
        """;

    private const string UpdateSql = """
        UPDATE invoice_notes SET invoice_id = @InvoiceId, body = @Body, created_at = @CreatedAt
        WHERE id = @Id
        """;

    private const string DeleteSql = "DELETE FROM invoice_notes WHERE id = @Id";

    /// <inheritdoc/>
    public async Task<InvoiceNote?> GetAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var row = await connection.QuerySingleOrDefaultAsync<Row>(new CommandDefinition(SelectSql, new { Id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return row is null ? null : Row.ToEntity(row);
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyList<InvoiceNote>> ListAsync(int skip = 0, int take = 100, CancellationToken cancellationToken = default)
    {
        var rows = await connection.QueryAsync<Row>(new CommandDefinition(ListSql, new { Skip = skip, Take = take }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows.Select(Row.ToEntity).ToList();
    }

    /// <inheritdoc/>
    public async Task InsertAsync(InvoiceNote entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        if (entity.Id == Guid.Empty)
            entity.Id = Guid.CreateVersion7();
        await connection.ExecuteAsync(new CommandDefinition(InsertSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    /// <inheritdoc/>
    public async Task<bool> UpdateAsync(InvoiceNote entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return await connection.ExecuteAsync(new CommandDefinition(UpdateSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <inheritdoc/>
    public async Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default)
    {
        return await connection.ExecuteAsync(new CommandDefinition(DeleteSql, new { Id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <summary>One row of invoice_notes, column by column, as Dapper reads and writes it.</summary>
    private sealed class Row
    {
        public Guid Id { get; set; }
        public Guid InvoiceId { get; set; }
        public string Body { get; set; } = default!;
        public DateTimeOffset? CreatedAt { get; set; }

        public static InvoiceNote ToEntity(Row row) => new()
        {
            Id = row.Id,
            InvoiceId = row.InvoiceId,
            Body = row.Body,
            CreatedAt = row.CreatedAt,
        };

        public static Row From(InvoiceNote entity) => new()
        {
            Id = entity.Id,
            InvoiceId = entity.InvoiceId,
            Body = entity.Body,
            CreatedAt = entity.CreatedAt,
        };
    }
}
