// Generated by Maquettiste (csharp-dapper/repository). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Dapper;

namespace App.Model.Billing;

/// <summary>Reads and writes <see cref="RevenueMonth"/> rows in revenue_months (database local, sqlite).</summary>
public partial interface IRevenueMonthRepository
{
    /// <summary>Returns the entity with the given key, or null.</summary>
    Task<RevenueMonth?> GetAsync(DateOnly month, CancellationToken cancellationToken = default);

    /// <summary>Returns a page of entities in key order.</summary>
    Task<IReadOnlyList<RevenueMonth>> ListAsync(int skip = 0, int take = 100, CancellationToken cancellationToken = default);

    /// <summary>Inserts the entity.</summary>
    Task InsertAsync(RevenueMonth entity, CancellationToken cancellationToken = default);

    /// <summary>Updates the entity; returns false when no row has its key.</summary>
    Task<bool> UpdateAsync(RevenueMonth entity, CancellationToken cancellationToken = default);

    /// <summary>Deletes the entity with the given key; returns false when there was none.</summary>
    Task<bool> DeleteAsync(DateOnly month, CancellationToken cancellationToken = default);
}

/// <summary>The Dapper implementation of <see cref="IRevenueMonthRepository"/> over an open or closed <see cref="IDbConnection"/>.</summary>
public partial class RevenueMonthRepository(IDbConnection connection, IDbTransaction? transaction = null) : IRevenueMonthRepository
{
    private const string Columns = """
        month AS Month,
        invoice_count AS InvoiceCount,
        revenue AS Revenue
        """;

    private const string SelectSql = "SELECT " + Columns + " FROM revenue_months WHERE month = @Month";

    private const string ListSql = "SELECT " + Columns + " FROM revenue_months ORDER BY month LIMIT @Take OFFSET @Skip";

    private const string InsertSql = """
        INSERT INTO revenue_months (month, invoice_count, revenue)
        VALUES (@Month, @InvoiceCount, @Revenue)
        """;

    private const string UpdateSql = """
        UPDATE revenue_months SET invoice_count = @InvoiceCount, revenue = @Revenue
        WHERE month = @Month
        """;

    private const string DeleteSql = "DELETE FROM revenue_months WHERE month = @Month";

    /// <inheritdoc/>
    public async Task<RevenueMonth?> GetAsync(DateOnly month, CancellationToken cancellationToken = default)
    {
        var row = await connection.QuerySingleOrDefaultAsync<Row>(new CommandDefinition(SelectSql, new { Month = month }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return row is null ? null : Row.ToEntity(row);
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyList<RevenueMonth>> ListAsync(int skip = 0, int take = 100, CancellationToken cancellationToken = default)
    {
        var rows = await connection.QueryAsync<Row>(new CommandDefinition(ListSql, new { Skip = skip, Take = take }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows.Select(Row.ToEntity).ToList();
    }

    /// <inheritdoc/>
    public async Task InsertAsync(RevenueMonth entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        await connection.ExecuteAsync(new CommandDefinition(InsertSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    /// <inheritdoc/>
    public async Task<bool> UpdateAsync(RevenueMonth entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return await connection.ExecuteAsync(new CommandDefinition(UpdateSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <inheritdoc/>
    public async Task<bool> DeleteAsync(DateOnly month, CancellationToken cancellationToken = default)
    {
        return await connection.ExecuteAsync(new CommandDefinition(DeleteSql, new { Month = month }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <summary>One row of revenue_months, column by column, as Dapper reads and writes it.</summary>
    private sealed class Row
    {
        public DateOnly Month { get; set; }
        public long InvoiceCount { get; set; }
        public decimal Revenue { get; set; }

        public static RevenueMonth ToEntity(Row row) => new()
        {
            Month = row.Month,
            InvoiceCount = row.InvoiceCount,
            Revenue = row.Revenue,
        };

        public static Row From(RevenueMonth entity) => new()
        {
            Month = entity.Month,
            InvoiceCount = entity.InvoiceCount,
            Revenue = entity.Revenue,
        };
    }
}
