-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table ingredients of database local (SQLite).
-- Maps entity Ingredient.

CREATE TABLE ingredients (
    sku text NOT NULL,
    name text NOT NULL,
    default_unit text NOT NULL DEFAULT 'g',
    preferred_unit text NULL,
    substitute_sku text NULL,
    CONSTRAINT pk_ingredients PRIMARY KEY (sku),
    CONSTRAINT fk_ingredients_substitute_sku FOREIGN KEY (substitute_sku) REFERENCES ingredients (sku)
);
