-- Generated by Maquettiste (sql-ddl/schema). Do not edit; changes are overwritten.
-- Schema of database sqlserver (SQL Server): tables 3, views 0, sequences 1.
-- Tables are in foreign-key dependency order: every table follows the tables it references.

SET QUOTED_IDENTIFIER ON;
GO

IF SCHEMA_ID(N'shop') IS NULL EXEC(N'CREATE SCHEMA shop');
GO

IF OBJECT_ID(N'shop.order_number_seq', N'SO') IS NULL CREATE SEQUENCE shop.order_number_seq AS bigint START WITH 1000 INCREMENT BY 5 MAXVALUE 999999999 CYCLE CACHE 20;
GO

-- shop.customers
IF OBJECT_ID(N'shop.customers', N'U') IS NULL
CREATE TABLE shop.customers (
    id bigint IDENTITY(100,1) NOT NULL,
    code char(10) NOT NULL,
    name varchar(150) COLLATE Latin1_General_100_CI_AS NOT NULL,
    email nvarchar(200) NULL,
    remarks nvarchar(max) NULL,
    balance decimal(10,2) NOT NULL CONSTRAINT customers_balance_dflt DEFAULT 10,
    status nvarchar(1) NOT NULL CONSTRAINT df_customers_status DEFAULT N'A',
    created_at datetime2(6) NOT NULL CONSTRAINT df_customers_created_at DEFAULT SYSUTCDATETIME(),
    balance_twice AS (balance * 2) PERSISTED,
    vip bit NOT NULL CONSTRAINT df_customers_vip DEFAULT 0,
    CONSTRAINT pk_customers PRIMARY KEY NONCLUSTERED (id),
    CONSTRAINT ck_customers_balance CHECK (balance >= -100)
);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_customers_name' AND object_id = OBJECT_ID(N'shop.customers')) CREATE INDEX ix_customers_name ON shop.customers (name, created_at DESC) INCLUDE (email);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_customers_code_lookup' AND object_id = OBJECT_ID(N'shop.customers')) CREATE UNIQUE INDEX ix_customers_code_lookup ON shop.customers (code);
IF EXISTS (SELECT 1 FROM sys.extended_properties WHERE class = 1 AND name = N'MS_Description' AND major_id = OBJECT_ID(N'shop.customers') AND minor_id = 0) BEGIN DECLARE @mq_rc3 int; EXEC @mq_rc3 = sys.sp_updateextendedproperty @name = N'MS_Description', @level0type = N'SCHEMA', @level0name = N'shop', @level1type = N'TABLE', @level1name = N'customers', @value = N'Customers who place orders, with their balance.'; IF @mq_rc3 <> 0 THROW 50000, N'sys.sp_updateextendedproperty failed: the migration stops here.', 1; END ELSE BEGIN DECLARE @mq_rc4 int; EXEC @mq_rc4 = sys.sp_addextendedproperty @name = N'MS_Description', @level0type = N'SCHEMA', @level0name = N'shop', @level1type = N'TABLE', @level1name = N'customers', @value = N'Customers who place orders, with their balance.'; IF @mq_rc4 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
IF EXISTS (SELECT 1 FROM sys.extended_properties WHERE class = 1 AND name = N'MS_Description' AND major_id = OBJECT_ID(N'shop.customers') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'shop.customers'), N'remarks', 'ColumnId')) BEGIN DECLARE @mq_rc1 int; EXEC @mq_rc1 = sys.sp_updateextendedproperty @name = N'MS_Description', @level0type = N'SCHEMA', @level0name = N'shop', @level1type = N'TABLE', @level1name = N'customers', @level2type = N'COLUMN', @level2name = N'remarks', @value = N'Remarks about the customer.'; IF @mq_rc1 <> 0 THROW 50000, N'sys.sp_updateextendedproperty failed: the migration stops here.', 1; END ELSE BEGIN DECLARE @mq_rc2 int; EXEC @mq_rc2 = sys.sp_addextendedproperty @name = N'MS_Description', @level0type = N'SCHEMA', @level0name = N'shop', @level1type = N'TABLE', @level1name = N'customers', @level2type = N'COLUMN', @level2name = N'remarks', @value = N'Remarks about the customer.'; IF @mq_rc2 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
GO

-- shop.orders
IF OBJECT_ID(N'shop.orders', N'U') IS NULL
CREATE TABLE shop.orders (
    id bigint NOT NULL CONSTRAINT df_orders_id DEFAULT (NEXT VALUE FOR shop.order_number_seq),
    number nvarchar(16) NOT NULL,
    customer_id bigint NOT NULL,
    total decimal(12,2) NOT NULL CONSTRAINT df_orders_total DEFAULT 0,
    placed_on date NULL,
    CONSTRAINT pk_orders_id PRIMARY KEY (id),
    CONSTRAINT uq_orders_customer_number UNIQUE (customer_id, number),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES shop.customers (id),
    CONSTRAINT ck_orders_total CHECK (total >= 0)
);
GO

-- shop.order_items
IF OBJECT_ID(N'shop.order_items', N'U') IS NULL
CREATE TABLE shop.order_items (
    order_id bigint NOT NULL,
    line_no int NOT NULL,
    sku nchar(20) NOT NULL,
    quantity bigint NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES shop.orders (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0)
);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_order_lines_product' AND object_id = OBJECT_ID(N'shop.order_items')) CREATE INDEX ix_order_lines_product ON shop.order_items (sku);
GO
