-- Migration 0002 of database postgres (PostgreSQL): schema revision 1 to 2.
-- Written once by Maquettiste (sql-ddl/migration) from the schema diff. It is yours now: review it, adjust it and commit it.
-- Lines marked TODO need a decision the diff cannot make (data conversions, sequence restarts).

BEGIN;

DROP MATERIALIZED VIEW IF EXISTS sales.order_counts;

DROP VIEW IF EXISTS sales.active_customers;

DROP VIEW IF EXISTS sales.customer_order_totals;

DROP VIEW IF EXISTS sales.customer_order_list;

DROP VIEW IF EXISTS sales.customer_orders;

-- Views dropped and created again lose the privileges granted on them: grant them again (this migration does not).

CREATE SCHEMA IF NOT EXISTS sales;

ALTER TABLE IF EXISTS sales.order_lines RENAME TO order_items;

COMMENT ON TABLE sales.customers IS 'Customers who place orders, with their balance.';

ALTER TABLE sales.orders DROP CONSTRAINT IF EXISTS fk_orders_customer;

ALTER TABLE sales.customers DROP CONSTRAINT IF EXISTS ck_customers_balance;

ALTER TABLE sales.customers DROP CONSTRAINT IF EXISTS uq_customers_email;

ALTER INDEX IF EXISTS sales.ix_customers_code RENAME TO ix_customers_code_lookup;

DROP INDEX IF EXISTS sales.ix_orders_placed_on;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pk_orders' AND conrelid = 'sales.orders'::regclass) THEN ALTER TABLE sales.orders RENAME CONSTRAINT pk_orders TO pk_orders_id; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'sales' AND table_name = 'order_items' AND column_name = 'line_no' AND is_identity = 'YES') THEN ALTER TABLE sales.order_items ALTER COLUMN line_no ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $$;

DO $$ BEGIN PERFORM setval(pg_get_serial_sequence('sales.order_items', 'line_no'), GREATEST(COALESCE(MAX(line_no), 0) + 1, 1), false) FROM sales.order_items; END $$;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'sales' AND table_name = 'order_items' AND column_name = 'product_code') THEN ALTER TABLE sales.order_items RENAME COLUMN product_code TO sku; END IF; END $$;

ALTER TABLE sales.order_items ALTER COLUMN quantity TYPE bigint USING quantity::bigint;

-- TODO: convert existing values of order_items.quantity (type: int32 -> int64); the cast keeps each value as it is.

ALTER TABLE sales.customers ADD COLUMN IF NOT EXISTS phone varchar(30) NULL;

COMMENT ON COLUMN sales.customers.phone IS 'Contact phone.';

ALTER TABLE sales.customers ADD COLUMN IF NOT EXISTS loyalty integer NULL;

ALTER TABLE sales.customers ADD COLUMN IF NOT EXISTS vip boolean NOT NULL DEFAULT false;

ALTER TABLE sales.customers ALTER COLUMN id TYPE bigint USING id::bigint;

ALTER TABLE sales.customers ALTER COLUMN id SET GENERATED ALWAYS SET INCREMENT BY 2;

-- TODO: convert existing values of customers.id (type: int32 -> int64); the cast keeps each value as it is.

ALTER TABLE sales.customers ALTER COLUMN name TYPE varchar(150) COLLATE "C";

ALTER TABLE sales.customers ALTER COLUMN email DROP NOT NULL;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'sales' AND table_name = 'customers' AND column_name = 'notes') THEN ALTER TABLE sales.customers RENAME COLUMN notes TO remarks; END IF; END $$;

COMMENT ON COLUMN sales.customers.remarks IS 'Remarks about the customer.';

ALTER TABLE sales.customers ALTER COLUMN balance SET DEFAULT 10;

ALTER TABLE sales.orders ALTER COLUMN customer_id TYPE bigint USING customer_id::bigint;

-- TODO: convert existing values of orders.customer_id (type: int32 -> int64); the cast keeps each value as it is.

CREATE TABLE IF NOT EXISTS sales.notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id bigint NULL,
    body text NOT NULL DEFAULT '-',
    CONSTRAINT pk_notes PRIMARY KEY (id),
    CONSTRAINT fk_notes_customer FOREIGN KEY (customer_id) REFERENCES sales.customers (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_notes_customer ON sales.notes (customer_id);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_customers_mail' AND conrelid = 'sales.customers'::regclass) THEN ALTER TABLE sales.customers ADD CONSTRAINT uq_customers_mail UNIQUE NULLS NOT DISTINCT (email); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_customers_balance' AND conrelid = 'sales.customers'::regclass) THEN ALTER TABLE sales.customers ADD CONSTRAINT ck_customers_balance CHECK (balance >= -100); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_orders_total' AND conrelid = 'sales.orders'::regclass) THEN ALTER TABLE sales.orders ADD CONSTRAINT ck_orders_total CHECK (total >= 0); END IF; END $$;

CREATE INDEX IF NOT EXISTS ix_orders_placed_on ON sales.orders (placed_on DESC, number);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_orders_customer' AND conrelid = 'sales.orders'::regclass) THEN ALTER TABLE sales.orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES sales.customers (id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE; END IF; END $$;

CREATE OR REPLACE VIEW sales.customer_order_list AS
SELECT c.id, c.name, o.number FROM sales.customers c JOIN sales.orders o ON o.customer_id = c.id;
COMMENT ON VIEW sales.customer_order_list IS 'Every customer with each order.';

CREATE OR REPLACE VIEW sales.customer_order_totals (customer_id, order_count) AS
SELECT id, count(*) FROM sales.customer_order_list GROUP BY id;

CREATE OR REPLACE VIEW sales.active_customers AS
SELECT id, code, status FROM sales.customers WHERE status = 'A'
WITH CHECK OPTION;

CREATE MATERIALIZED VIEW IF NOT EXISTS sales.order_counts AS
SELECT customer_id, count(*) AS order_count FROM sales.orders GROUP BY customer_id;
COMMENT ON MATERIALIZED VIEW sales.order_counts IS 'Orders per customer, stored.';

ALTER SEQUENCE IF EXISTS sales.order_numbers RENAME TO order_number_seq;

ALTER SEQUENCE sales.order_number_seq INCREMENT BY 5 MAXVALUE 999999999 CYCLE;

COMMIT;
