-- Generated by Maquettiste (sql-ddl/seed). Edit only inside the protected region below; the rest is regenerated.
-- Seed data of database main (PostgreSQL 16). Run it after the schema script or the migrations; it can run again.

-- Reference data, reconciled on every run: these tables, constraints and types are not in the schema snapshot.

-- payments.method (PaymentMethod, check).
ALTER TABLE billing.payments DROP CONSTRAINT IF EXISTS ck_payments_method_ref;
ALTER TABLE billing.payments DROP CONSTRAINT IF EXISTS fk_payments_method_ref;
ALTER TABLE billing.payments ADD CONSTRAINT ck_payments_method_ref CHECK (method IN ('card', 'transfer', 'cash'));

-- maquettiste:keep id=seed-data
-- Hand-written seed data for main goes here, for example:
-- INSERT INTO ... VALUES (...);
-- maquettiste:end-keep
