-- Generated by Maquettiste (sql-ddl/schema). Do not edit; changes are overwritten.
-- Schema of database mysql (MySQL): tables 3, views 0, sequences 0.
-- Tables are in foreign-key dependency order: every table follows the tables it references.

-- customers
CREATE TABLE IF NOT EXISTS customers (
    id bigint NOT NULL AUTO_INCREMENT,
    code char(10) NOT NULL,
    name varchar(150) COLLATE utf8mb4_bin NOT NULL,
    email varchar(200) NULL,
    remarks longtext NULL COMMENT 'Remarks about the customer.',
    balance decimal(10,2) NOT NULL DEFAULT 10,
    status varchar(1) NOT NULL DEFAULT 'A',
    created_at datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    balance_twice decimal(14,2) GENERATED ALWAYS AS (balance * 2) STORED,
    vip tinyint(1) NOT NULL DEFAULT 0,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT ck_customers_balance CHECK (balance >= -100),
    INDEX ix_customers_name (name, created_at DESC),
    UNIQUE INDEX ix_customers_code_lookup (code) USING BTREE
) AUTO_INCREMENT = 100 COMMENT = 'Customers who place orders, with their balance.';

-- orders
CREATE TABLE IF NOT EXISTS orders (
    id bigint NOT NULL AUTO_INCREMENT,
    number varchar(16) NOT NULL,
    customer_id bigint NOT NULL,
    total decimal(12,2) NOT NULL DEFAULT 0,
    placed_on date NULL,
    CONSTRAINT pk_orders_id PRIMARY KEY (id),
    CONSTRAINT uq_orders_customer_number UNIQUE (customer_id, number),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT ck_orders_total CHECK (total >= 0)
);

-- order_items
CREATE TABLE IF NOT EXISTS order_items (
    order_id bigint NOT NULL,
    line_no int NOT NULL,
    sku char(20) NOT NULL,
    quantity bigint NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0),
    INDEX ix_order_lines_product (sku)
);
