-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table billing.payment_invoice of database main (PostgreSQL 16).
-- Junction table of relation "settles".

CREATE TABLE billing.payment_invoice (
    payments_id bigint NOT NULL,
    invoices_id uuid NOT NULL,
    allocated_amount numeric(18,2) NOT NULL,
    allocated_currency varchar(3) NOT NULL,
    CONSTRAINT pk_payment_invoice PRIMARY KEY (payments_id, invoices_id),
    CONSTRAINT fk_payment_invoice_payments_id FOREIGN KEY (payments_id) REFERENCES billing.payments (id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_invoice_invoices_id FOREIGN KEY (invoices_id) REFERENCES billing.invoices (id) ON DELETE CASCADE
);
