-- Generated by Maquettiste (sql-ddl/schema). Do not edit; changes are overwritten.
-- Schema of database reporting (SQL Server): tables 9, views 0, sequences 0, routines 1, database types 1, SQL objects 1.
-- Tables are in foreign-key dependency order: every table follows the tables it references.

-- SQL Server alias types have no CHECK; email_address does not enforce: VALUE LIKE '%_@_%'
CREATE TYPE dbo.email_address FROM nvarchar(254);
GO

-- dbo.customer_notes
CREATE TABLE dbo.customer_notes (
    id uniqueidentifier NOT NULL,
    customer_id uniqueidentifier NOT NULL,
    body nvarchar(max) NOT NULL,
    created_at datetimeoffset(6) NULL,
    CONSTRAINT pk_customer_notes PRIMARY KEY (id)
);
BEGIN DECLARE @mq_rc1 int; EXEC @mq_rc1 = sys.sp_addextendedproperty @name = N'MS_Description', @value = N'A note on a customer. Stored in the shared notes table with entity_type ''customer''.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'customer_notes'; IF @mq_rc1 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
GO

-- dbo.customers
CREATE TABLE dbo.customers (
    id uniqueidentifier NOT NULL,
    name nvarchar(120) NOT NULL,
    email dbo.email_address NOT NULL,
    customer_since date NULL,
    created_at datetimeoffset(6) NOT NULL,
    updated_at datetimeoffset(6) NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uq_customers_email UNIQUE (email)
);
BEGIN DECLARE @mq_rc2 int; EXEC @mq_rc2 = sys.sp_addextendedproperty @name = N'MS_Description', @value = N'Someone we bill.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'customers'; IF @mq_rc2 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
GO

-- dbo.invoices
CREATE TABLE dbo.invoices (
    id uniqueidentifier NOT NULL,
    number nvarchar(32) NOT NULL,
    issued_on date NOT NULL,
    total_amount decimal(18,2) NULL,
    total_currency nvarchar(3) NULL,
    status int NOT NULL CONSTRAINT df_invoices_status DEFAULT 0,
    notes nvarchar(max) NULL,
    created_at datetimeoffset(6) NOT NULL,
    updated_at datetimeoffset(6) NULL,
    deleted_at datetimeoffset(6) NULL,
    reason nvarchar(200) NULL,
    discriminator nvarchar(64) NOT NULL,
    customer_id uniqueidentifier NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id),
    CONSTRAINT uq_invoices_number UNIQUE (number),
    CONSTRAINT fk_invoices_customer_id FOREIGN KEY (customer_id) REFERENCES dbo.customers (id)
);
CREATE INDEX ix_invoices_issued_on ON dbo.invoices (issued_on);
BEGIN DECLARE @mq_rc3 int; EXEC @mq_rc3 = sys.sp_addextendedproperty @name = N'MS_Description', @value = N'# Invoice

A bill issued to a customer. Its number is assigned when it is issued and never reused.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'invoices'; IF @mq_rc3 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
GO

-- dbo.products
CREATE TABLE dbo.products (
    id uniqueidentifier NOT NULL,
    sku nvarchar(40) NOT NULL,
    name nvarchar(200) NOT NULL,
    list_price_amount decimal(18,2) NULL,
    list_price_currency nvarchar(3) NULL,
    deleted_at datetimeoffset(6) NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_sku UNIQUE (sku)
);
GO

-- dbo.invoice_lines
CREATE TABLE dbo.invoice_lines (
    id char(26) NOT NULL,
    quantity int NOT NULL,
    unit_price_amount decimal(18,2) NOT NULL,
    unit_price_currency nvarchar(3) NOT NULL,
    description nvarchar(500) NULL,
    invoice_id uniqueidentifier NOT NULL,
    product_id uniqueidentifier NOT NULL,
    CONSTRAINT pk_invoice_lines PRIMARY KEY (id),
    CONSTRAINT fk_invoice_lines_invoice_id FOREIGN KEY (invoice_id) REFERENCES dbo.invoices (id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_lines_product_id FOREIGN KEY (product_id) REFERENCES dbo.products (id)
);
GO

-- dbo.invoice_notes
CREATE TABLE dbo.invoice_notes (
    id uniqueidentifier NOT NULL,
    invoice_id uniqueidentifier NOT NULL,
    body nvarchar(max) NOT NULL,
    created_at datetimeoffset(6) NULL,
    CONSTRAINT pk_invoice_notes PRIMARY KEY (id)
);
BEGIN DECLARE @mq_rc4 int; EXEC @mq_rc4 = sys.sp_addextendedproperty @name = N'MS_Description', @value = N'A note on an invoice. Stored in the shared notes table with entity_type ''invoice''.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'invoice_notes'; IF @mq_rc4 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
GO

-- dbo.payments
CREATE TABLE dbo.payments (
    id bigint IDENTITY(1,1) NOT NULL,
    amount_amount decimal(18,2) NOT NULL,
    amount_currency nvarchar(3) NOT NULL,
    received_at datetimeoffset(6) NOT NULL,
    reference nvarchar(64) NULL,
    method nvarchar(16) NULL,
    ledger_position binary(8) NULL,
    created_at datetimeoffset(6) NOT NULL,
    updated_at datetimeoffset(6) NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);
GO

-- dbo.payment_invoice
CREATE TABLE dbo.payment_invoice (
    payments_id bigint NOT NULL,
    invoices_id uniqueidentifier NOT NULL,
    allocated_amount decimal(18,2) NOT NULL,
    allocated_currency nvarchar(3) NOT NULL,
    CONSTRAINT pk_payment_invoice PRIMARY KEY (payments_id, invoices_id),
    CONSTRAINT fk_payment_invoice_payments_id FOREIGN KEY (payments_id) REFERENCES dbo.payments (id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_invoice_invoices_id FOREIGN KEY (invoices_id) REFERENCES dbo.invoices (id) ON DELETE CASCADE
);
GO

-- dbo.revenue_months
CREATE TABLE dbo.revenue_months (
    month date NOT NULL,
    invoice_count bigint NOT NULL,
    revenue decimal(18,2) NOT NULL,
    CONSTRAINT pk_revenue_months PRIMARY KEY (month)
);
BEGIN DECLARE @mq_rc5 int; EXEC @mq_rc5 = sys.sp_addextendedproperty @name = N'MS_Description', @value = N'Invoiced revenue per month, read through the RevenueByMonth query; read-only.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'revenue_months'; IF @mq_rc5 <> 0 THROW 50000, N'sys.sp_addextendedproperty failed: the migration stops here.', 1; END;
GO

CREATE FUNCTION dbo.invoice_total(@invoice_id uniqueidentifier)
RETURNS decimal(18,2)
AS
BEGIN
    RETURN (SELECT COALESCE(SUM(quantity * unit_price_amount), 0) FROM dbo.invoice_lines WHERE invoice_id = @invoice_id);
END
GO

CREATE TRIGGER dbo.invoices_keep_number ON dbo.invoices AFTER UPDATE AS
BEGIN
    IF EXISTS (SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id WHERE i.number <> d.number)
        THROW 50001, 'An invoice keeps its number.', 1;
END
GO
