-- Generated by Maquettiste (sql-ddl/seed). Edit only inside the protected region below; the rest is regenerated.
-- Seed data of database reporting (SQL Server). Run it after the schema script or the migrations; it can run again.

-- Reference data, reconciled on every run: these tables, constraints and types are not in the schema snapshot.

-- payments.method (PaymentMethod, check).
IF OBJECT_ID(N'dbo.ck_payments_method_ref', N'C') IS NOT NULL ALTER TABLE dbo.payments DROP CONSTRAINT ck_payments_method_ref;
IF OBJECT_ID(N'dbo.fk_payments_method_ref', N'F') IS NOT NULL ALTER TABLE dbo.payments DROP CONSTRAINT fk_payments_method_ref;
ALTER TABLE dbo.payments ADD CONSTRAINT ck_payments_method_ref CHECK (method IN (N'card', N'transfer', N'cash'));
GO

-- maquettiste:keep id=seed-data
-- Hand-written seed data for reporting goes here, for example:
-- INSERT INTO ... VALUES (...);
-- maquettiste:end-keep
