// Generated by Maquettiste (csharp-dapper/process-endpoints). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Processes.Data.Dispatch;
using Processes.Data.Runtime;

namespace Processes.Data.Sales;

/// <summary>The HTTP endpoints of process SalesOrderLifecycle: one POST per event under /processes/sales-order-lifecycle/{instance}/.</summary>
public static partial class SalesOrderLifecycleEndpoints
{
    /// <summary>Maps the endpoints of SalesOrderLifecycle.</summary>
    /// <param name="routes">The route builder.</param>
    /// <returns>The route builder.</returns>
    public static IEndpointRouteBuilder MapSalesOrderLifecycleEndpoints(this IEndpointRouteBuilder routes)
    {
        ArgumentNullException.ThrowIfNull(routes);
        routes.MapPost("/processes/sales-order-lifecycle/{instance}/submit", SubmitAsync);
        routes.MapPost("/processes/sales-order-lifecycle/{instance}/approve-credit", ApproveCreditAsync);
        routes.MapPost("/processes/sales-order-lifecycle/{instance}/reject-credit", RejectCreditAsync);
        routes.MapPost("/processes/sales-order-lifecycle/{instance}/payment-received", PaymentReceivedAsync);
        routes.MapPost("/processes/sales-order-lifecycle/{instance}/pick", PickAsync);
        routes.MapPost("/processes/sales-order-lifecycle/{instance}/ship", ShipAsync);
        routes.MapPost("/processes/sales-order-lifecycle/{instance}/hold", HoldAsync);
        routes.MapPost("/processes/sales-order-lifecycle/{instance}/release", ReleaseAsync);
        routes.MapPost("/processes/sales-order-lifecycle/{instance}/cancel", CancelAsync);
        return routes;
    }

    /// <summary>POST /processes/sales-order-lifecycle/{instance}/submit: raises submit.</summary>
    /// <param name="instance">The instance identity.</param>
    /// <param name="request">The envelope.</param>
    /// <param name="dispatcher">The dispatcher.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    /// <returns>200 with the result when accepted, 409 when refused.</returns>
    public static async Task<IResult> SubmitAsync(string instance, EventRequest request, [FromServices] Dispatcher dispatcher, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(dispatcher);
        var command = new SalesOrderLifecycleSubmitCommand(new ProcessEnvelope(instance, request.Actor, request.Signer, request.Meaning, request.Reason));
        Func<CommandResult, IResult> respond = Respond;
        // maquettiste:keep id=01JQPRX0000000000000000001
        // maquettiste:end-keep
        return respond(await dispatcher.SendAsync(command, cancellationToken).ConfigureAwait(false));
    }

    /// <summary>POST /processes/sales-order-lifecycle/{instance}/approve-credit: raises approveCredit.</summary>
    /// <param name="instance">The instance identity.</param>
    /// <param name="request">The envelope.</param>
    /// <param name="dispatcher">The dispatcher.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    /// <returns>200 with the result when accepted, 409 when refused.</returns>
    public static async Task<IResult> ApproveCreditAsync(string instance, EventRequest request, [FromServices] Dispatcher dispatcher, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(dispatcher);
        var command = new SalesOrderLifecycleApproveCreditCommand(new ProcessEnvelope(instance, request.Actor, request.Signer, request.Meaning, request.Reason));
        Func<CommandResult, IResult> respond = Respond;
        // maquettiste:keep id=01JQPRX0000000000000000002
        // maquettiste:end-keep
        return respond(await dispatcher.SendAsync(command, cancellationToken).ConfigureAwait(false));
    }

    /// <summary>POST /processes/sales-order-lifecycle/{instance}/reject-credit: raises rejectCredit.</summary>
    /// <param name="instance">The instance identity.</param>
    /// <param name="request">The envelope.</param>
    /// <param name="dispatcher">The dispatcher.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    /// <returns>200 with the result when accepted, 409 when refused.</returns>
    public static async Task<IResult> RejectCreditAsync(string instance, EventRequest request, [FromServices] Dispatcher dispatcher, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(dispatcher);
        var command = new SalesOrderLifecycleRejectCreditCommand(new ProcessEnvelope(instance, request.Actor, request.Signer, request.Meaning, request.Reason));
        Func<CommandResult, IResult> respond = Respond;
        // maquettiste:keep id=01JQPRX0000000000000000003
        // maquettiste:end-keep
        return respond(await dispatcher.SendAsync(command, cancellationToken).ConfigureAwait(false));
    }

    /// <summary>POST /processes/sales-order-lifecycle/{instance}/payment-received: raises paymentReceived.</summary>
    /// <param name="instance">The instance identity.</param>
    /// <param name="request">The envelope.</param>
    /// <param name="dispatcher">The dispatcher.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    /// <returns>200 with the result when accepted, 409 when refused.</returns>
    public static async Task<IResult> PaymentReceivedAsync(string instance, EventRequest request, [FromServices] Dispatcher dispatcher, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(dispatcher);
        var command = new SalesOrderLifecyclePaymentReceivedCommand(new ProcessEnvelope(instance, request.Actor, request.Signer, request.Meaning, request.Reason));
        Func<CommandResult, IResult> respond = Respond;
        // maquettiste:keep id=01JQPRX0000000000000000004
        // maquettiste:end-keep
        return respond(await dispatcher.SendAsync(command, cancellationToken).ConfigureAwait(false));
    }

    /// <summary>POST /processes/sales-order-lifecycle/{instance}/pick: raises pick.</summary>
    /// <param name="instance">The instance identity.</param>
    /// <param name="request">The envelope.</param>
    /// <param name="dispatcher">The dispatcher.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    /// <returns>200 with the result when accepted, 409 when refused.</returns>
    public static async Task<IResult> PickAsync(string instance, EventRequest request, [FromServices] Dispatcher dispatcher, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(dispatcher);
        var command = new SalesOrderLifecyclePickCommand(new ProcessEnvelope(instance, request.Actor, request.Signer, request.Meaning, request.Reason));
        Func<CommandResult, IResult> respond = Respond;
        // maquettiste:keep id=01JQPRX0000000000000000005
        // maquettiste:end-keep
        return respond(await dispatcher.SendAsync(command, cancellationToken).ConfigureAwait(false));
    }

    /// <summary>POST /processes/sales-order-lifecycle/{instance}/ship: raises ship.</summary>
    /// <param name="instance">The instance identity.</param>
    /// <param name="request">The envelope.</param>
    /// <param name="dispatcher">The dispatcher.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    /// <returns>200 with the result when accepted, 409 when refused.</returns>
    public static async Task<IResult> ShipAsync(string instance, EventRequest request, [FromServices] Dispatcher dispatcher, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(dispatcher);
        var command = new SalesOrderLifecycleShipCommand(new ProcessEnvelope(instance, request.Actor, request.Signer, request.Meaning, request.Reason));
        Func<CommandResult, IResult> respond = Respond;
        // maquettiste:keep id=01JQPRX0000000000000000006
        // maquettiste:end-keep
        return respond(await dispatcher.SendAsync(command, cancellationToken).ConfigureAwait(false));
    }

    /// <summary>POST /processes/sales-order-lifecycle/{instance}/hold: raises hold.</summary>
    /// <param name="instance">The instance identity.</param>
    /// <param name="request">The envelope.</param>
    /// <param name="dispatcher">The dispatcher.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    /// <returns>200 with the result when accepted, 409 when refused.</returns>
    public static async Task<IResult> HoldAsync(string instance, EventRequest request, [FromServices] Dispatcher dispatcher, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(dispatcher);
        var command = new SalesOrderLifecycleHoldCommand(new ProcessEnvelope(instance, request.Actor, request.Signer, request.Meaning, request.Reason));
        Func<CommandResult, IResult> respond = Respond;
        // maquettiste:keep id=01JQPRX0000000000000000007
        // maquettiste:end-keep
        return respond(await dispatcher.SendAsync(command, cancellationToken).ConfigureAwait(false));
    }

    /// <summary>POST /processes/sales-order-lifecycle/{instance}/release: raises release.</summary>
    /// <param name="instance">The instance identity.</param>
    /// <param name="request">The envelope.</param>
    /// <param name="dispatcher">The dispatcher.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    /// <returns>200 with the result when accepted, 409 when refused.</returns>
    public static async Task<IResult> ReleaseAsync(string instance, EventRequest request, [FromServices] Dispatcher dispatcher, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(dispatcher);
        var command = new SalesOrderLifecycleReleaseCommand(new ProcessEnvelope(instance, request.Actor, request.Signer, request.Meaning, request.Reason));
        Func<CommandResult, IResult> respond = Respond;
        // maquettiste:keep id=01JQPRX0000000000000000008
        // maquettiste:end-keep
        return respond(await dispatcher.SendAsync(command, cancellationToken).ConfigureAwait(false));
    }

    /// <summary>POST /processes/sales-order-lifecycle/{instance}/cancel: raises cancel.</summary>
    /// <param name="instance">The instance identity.</param>
    /// <param name="request">The envelope.</param>
    /// <param name="dispatcher">The dispatcher.</param>
    /// <param name="cancellationToken">Cancellation.</param>
    /// <returns>200 with the result when accepted, 409 when refused.</returns>
    public static async Task<IResult> CancelAsync(string instance, EventRequest request, [FromServices] Dispatcher dispatcher, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(dispatcher);
        var command = new SalesOrderLifecycleCancelCommand(new ProcessEnvelope(instance, request.Actor, request.Signer, request.Meaning, request.Reason));
        Func<CommandResult, IResult> respond = Respond;
        // maquettiste:keep id=01JQPRX0000000000000000009
        // maquettiste:end-keep
        return respond(await dispatcher.SendAsync(command, cancellationToken).ConfigureAwait(false));
    }

    private static IResult Respond(CommandResult result) => result.Accepted ? Results.Ok(result) : Results.Conflict(result);
}
