// Generated by Maquettiste (csharp-dapper/query). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using App.Model.Billing;

namespace App.Model.Queries;

/// <summary>A customer&apos;s invoices in some statuses, newest first, a page at a time, each with its lines.</summary>
public partial interface IInvoicesByCustomerQuery
{
    /// <summary>Runs the query and fills its collections.</summary>
    Task<IReadOnlyList<InvoicesByCustomerResult>> ExecuteAsync(Guid customerId, IEnumerable<string> statuses, int offset = 0, int limit = 50, CancellationToken cancellationToken = default);
}

/// <summary>One row of query InvoicesByCustomer with its collections.</summary>
public sealed partial record InvoicesByCustomerResult(Invoice Item, IReadOnlyList<InvoiceLine> Lines);

/// <summary>The Dapper implementation of <see cref="IInvoicesByCustomerQuery"/> (database main, postgresql).</summary>
public partial class InvoicesByCustomerQuery(IDbConnection connection, IDbTransaction? transaction = null) : IInvoicesByCustomerQuery
{
    private const string Sql = """
        SELECT i.id AS id, i.number AS number, i.issued_on AS issuedOn, i.status AS status, i.notes AS notes, i.created_at AS createdAt
        FROM billing.invoices i
        WHERE i.customer_id = @customerId AND i.status IN @statuses AND i.deleted_at IS NULL
        ORDER BY i.issued_on DESC, i.number ASC
        LIMIT @limit OFFSET @offset
        """;

    private const string LinesSql = """
        SELECT l.id AS id, l.quantity AS quantity, l.description AS description, l.invoice_id AS __key0
        FROM billing.invoice_lines l
        WHERE l.invoice_id IN @__keys0
        ORDER BY l.id ASC
        """;

    /// <inheritdoc/>
    public async Task<IReadOnlyList<InvoicesByCustomerResult>> ExecuteAsync(Guid customerId, IEnumerable<string> statuses, int offset = 0, int limit = 50, CancellationToken cancellationToken = default)
    {
        var rows = (await connection.QueryAsync<Row>(new CommandDefinition(Sql, new { customerId = customerId, statuses = statuses, offset = offset, limit = limit }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false)).ToList();
        var lines = Array.Empty<LinesRow>().ToLookup(r => r.__key0);
        if (rows.Count > 0)
        {
            var found = await connection.QueryAsync<LinesRow>(new CommandDefinition(LinesSql, new
            {
                __keys0 = rows.Select(r => r.id).Distinct().ToArray(),
                customerId = customerId,
                statuses = statuses,
                offset = offset,
                limit = limit,
            }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
            lines = found.ToLookup(r => r.__key0);
        }

        return rows.Select(r => new InvoicesByCustomerResult(r.ToItem(), [.. lines[r.id].Select(x => x.ToItem())])).ToList();
    }

    /// <summary>One row as Dapper reads it, field by field.</summary>
    private sealed class Row
    {
        public Guid id { get; set; }
        public string number { get; set; } = default!;
        public DateOnly issuedOn { get; set; }
        public string status { get; set; } = default!;
        public string? notes { get; set; }
        public DateTimeOffset createdAt { get; set; }

        public Invoice ToItem() => new()
        {
            Id = id,
            Number = number,
            IssuedOn = issuedOn,
            Status = InvoiceStatusCodes.Parse(status),
            Notes = notes,
            CreatedAt = createdAt,
        };
    }

    /// <summary>One element of collection lines with its parent's key, as Dapper reads it.</summary>
    private sealed class LinesRow
    {
        public string id { get; set; } = default!;
        public int quantity { get; set; }
        public string? description { get; set; }
        public Guid __key0 { get; set; }

        public InvoiceLine ToItem() => new()
        {
            Id = id,
            Quantity = quantity,
            Description = description,
        };
    }
}
