// Generated by Maquettiste (csharp-dapper/repository). Do not edit; changes are overwritten.
// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Dapper;

namespace App.Model.Billing;

/// <summary>Reads and writes <see cref="Customer"/> rows in billing.customers (database main, postgresql).</summary>
public partial interface ICustomerRepository
{
    /// <summary>Returns the entity with the given key, or null.</summary>
    Task<Customer?> GetAsync(Guid id, CancellationToken cancellationToken = default);

    /// <summary>Returns a page of entities in key order.</summary>
    Task<IReadOnlyList<Customer>> ListAsync(int skip = 0, int take = 100, CancellationToken cancellationToken = default);

    /// <summary>Inserts the entity.</summary>
    Task InsertAsync(Customer entity, CancellationToken cancellationToken = default);

    /// <summary>Updates the entity; returns false when no row has its key.</summary>
    Task<bool> UpdateAsync(Customer entity, CancellationToken cancellationToken = default);

    /// <summary>Deletes the entity with the given key; returns false when there was none.</summary>
    Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default);
}

/// <summary>The Dapper implementation of <see cref="ICustomerRepository"/> over an open or closed <see cref="IDbConnection"/>.</summary>
public partial class CustomerRepository(IDbConnection connection, IDbTransaction? transaction = null) : ICustomerRepository
{
    private const string Columns = """
        id AS Id,
        name AS Name,
        email AS Email,
        customer_since AS CustomerSince,
        created_at AS CreatedAt,
        updated_at AS UpdatedAt
        """;

    private const string SelectSql = "SELECT " + Columns + " FROM billing.customers WHERE id = @Id";

    private const string ListSql = "SELECT " + Columns + " FROM billing.customers ORDER BY id LIMIT @Take OFFSET @Skip";

    private const string InsertSql = """
        INSERT INTO billing.customers (id, name, email, customer_since, created_at, updated_at)
        VALUES (@Id, @Name, @Email, @CustomerSince, @CreatedAt, @UpdatedAt)
        """;

    private const string UpdateSql = """
        UPDATE billing.customers SET name = @Name, email = @Email, customer_since = @CustomerSince, created_at = @CreatedAt, updated_at = @UpdatedAt
        WHERE id = @Id
        """;

    private const string DeleteSql = "DELETE FROM billing.customers WHERE id = @Id";

    /// <inheritdoc/>
    public async Task<Customer?> GetAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var row = await connection.QuerySingleOrDefaultAsync<Row>(new CommandDefinition(SelectSql, new { Id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return row is null ? null : Row.ToEntity(row);
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyList<Customer>> ListAsync(int skip = 0, int take = 100, CancellationToken cancellationToken = default)
    {
        var rows = await connection.QueryAsync<Row>(new CommandDefinition(ListSql, new { Skip = skip, Take = take }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows.Select(Row.ToEntity).ToList();
    }

    /// <inheritdoc/>
    public async Task InsertAsync(Customer entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        if (entity.Id == Guid.Empty)
            entity.Id = Guid.CreateVersion7();
        await connection.ExecuteAsync(new CommandDefinition(InsertSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    /// <inheritdoc/>
    public async Task<bool> UpdateAsync(Customer entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return await connection.ExecuteAsync(new CommandDefinition(UpdateSql, Row.From(entity), transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <inheritdoc/>
    public async Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default)
    {
        return await connection.ExecuteAsync(new CommandDefinition(DeleteSql, new { Id = id }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false) > 0;
    }

    /// <summary>One row of customers, column by column, as Dapper reads and writes it.</summary>
    private sealed class Row
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = default!;
        public string Email { get; set; } = default!;
        public DateOnly? CustomerSince { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset? UpdatedAt { get; set; }

        public static Customer ToEntity(Row row) => new()
        {
            Id = row.Id,
            Name = row.Name,
            Email = row.Email,
            CustomerSince = row.CustomerSince,
            CreatedAt = row.CreatedAt,
            UpdatedAt = row.UpdatedAt,
        };

        public static Row From(Customer entity) => new()
        {
            Id = entity.Id,
            Name = entity.Name,
            Email = entity.Email,
            CustomerSince = entity.CustomerSince,
            CreatedAt = entity.CreatedAt,
            UpdatedAt = entity.UpdatedAt,
        };
    }
}
