-- Migration 0001 of database postgres (PostgreSQL): schema revision 0 to 1.
-- Written once by Maquettiste (sql-ddl/migration) from the schema diff. It is yours now: review it, adjust it and commit it.
-- Lines marked TODO need a decision the diff cannot make (data conversions, sequence restarts).

BEGIN;

CREATE SCHEMA IF NOT EXISTS sales;

CREATE SEQUENCE IF NOT EXISTS sales.order_numbers AS bigint START WITH 1000 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE IF NOT EXISTS sales.audit_numbers AS integer START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS sales.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) NOT NULL,
    code char(10) NOT NULL,
    name varchar(100) COLLATE "C" NOT NULL,
    email varchar(200) NOT NULL,
    notes text NULL,
    balance numeric(12,2) NOT NULL DEFAULT 0,
    status varchar(1) NOT NULL DEFAULT 'A',
    created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    balance_twice numeric(14,2) GENERATED ALWAYS AS (balance * 2) STORED,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_status CHECK (status IN ('A', 'I')),
    CONSTRAINT ck_customers_balance CHECK (balance >= 0)
);
CREATE INDEX IF NOT EXISTS ix_customers_name ON sales.customers (name, created_at DESC) INCLUDE (email);
CREATE INDEX IF NOT EXISTS ix_customers_active ON sales.customers (status) WHERE status = 'A';
CREATE UNIQUE INDEX IF NOT EXISTS ix_customers_code ON sales.customers USING btree (code);
CREATE INDEX IF NOT EXISTS ix_customers_email_lower ON sales.customers ((lower(email)));
COMMENT ON TABLE sales.customers IS 'Customers who place orders.';
COMMENT ON COLUMN sales.customers.notes IS 'Free-form notes.';

CREATE TABLE IF NOT EXISTS sales.orders (
    id bigint NOT NULL DEFAULT nextval('sales.order_numbers'),
    number varchar(20) NOT NULL,
    customer_id integer NOT NULL,
    total numeric(12,2) NOT NULL DEFAULT 0,
    placed_on date NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_customer_number UNIQUE (customer_id, number),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES sales.customers (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS ix_orders_placed_on ON sales.orders (placed_on DESC);

CREATE TABLE IF NOT EXISTS sales.order_lines (
    order_id bigint NOT NULL,
    line_no integer NOT NULL,
    product_code char(20) NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES sales.orders (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0)
);
CREATE INDEX IF NOT EXISTS ix_order_lines_product ON sales.order_lines (product_code);

CREATE OR REPLACE VIEW sales.customer_orders AS
SELECT c.id, c.name, o.number FROM sales.customers c JOIN sales.orders o ON o.customer_id = c.id;
COMMENT ON VIEW sales.customer_orders IS 'Customers with their orders.';

CREATE OR REPLACE VIEW sales.customer_order_totals (customer_id, order_count) AS
SELECT id, count(*) FROM sales.customer_orders GROUP BY id;

CREATE OR REPLACE VIEW sales.active_customers AS
SELECT id, code, status FROM sales.customers WHERE status = 'A'
WITH CHECK OPTION;

CREATE MATERIALIZED VIEW IF NOT EXISTS sales.order_counts AS
SELECT customer_id, count(*) AS order_count FROM sales.orders GROUP BY customer_id;
COMMENT ON MATERIALIZED VIEW sales.order_counts IS 'Orders per customer, stored.';

COMMIT;
