-- Generated by Maquettiste (sql-ddl/seed). Edit only inside the protected region below; the rest is regenerated.
-- Seed data of database main (PostgreSQL). Run it after the schema script or the migrations; it can run again.

-- Reference data, reconciled on every run: these tables, constraints and types are not in the schema snapshot.

-- Allergen: lookup table allergens, rows upserted by code.
CREATE TABLE IF NOT EXISTS public.allergens (
    code varchar(16) NOT NULL,
    label varchar(64) NOT NULL,
    parent varchar(16) NULL,
    CONSTRAINT pk_allergens PRIMARY KEY (code),
    CONSTRAINT fk_allergens_parent_ref FOREIGN KEY (parent) REFERENCES public.allergens (code)
);
INSERT INTO public.allergens (code, label, parent) VALUES
    ('gluten', 'Gluten', NULL),
    ('nut', 'Nuts', NULL),
    ('tree_nut', 'Tree nuts', 'nut')
ON CONFLICT (code) DO UPDATE SET label = excluded.label, parent = excluded.parent;

-- ingredients.default_unit (UnitOfMeasure, check).
ALTER TABLE public.ingredients DROP CONSTRAINT IF EXISTS ck_ingredients_default_unit_ref;
ALTER TABLE public.ingredients DROP CONSTRAINT IF EXISTS fk_ingredients_default_unit_ref;
ALTER TABLE public.ingredients ADD CONSTRAINT ck_ingredients_default_unit_ref CHECK (default_unit IN ('kg', 'g', 'pinch'));

-- ingredients.preferred_unit (UnitOfMeasure, check).
ALTER TABLE public.ingredients DROP CONSTRAINT IF EXISTS ck_ingredients_preferred_unit_ref;
ALTER TABLE public.ingredients DROP CONSTRAINT IF EXISTS fk_ingredients_preferred_unit_ref;
ALTER TABLE public.ingredients ADD CONSTRAINT ck_ingredients_preferred_unit_ref CHECK (preferred_unit IN ('kg', 'g', 'pinch'));

-- recipe_ingredient.unit_of_measure (UnitOfMeasure, check).
ALTER TABLE public.recipe_ingredient DROP CONSTRAINT IF EXISTS ck_recipe_ingredient_unit_of_measure_ref;
ALTER TABLE public.recipe_ingredient DROP CONSTRAINT IF EXISTS fk_recipe_ingredient_unit_of_measure_ref;
ALTER TABLE public.recipe_ingredient ADD CONSTRAINT ck_recipe_ingredient_unit_of_measure_ref CHECK (unit_of_measure IN ('kg', 'g', 'pinch'));

-- Ingredient.allergens (collection of Allergen, lookup-table).
CREATE TABLE IF NOT EXISTS public.ingredients_allergens (
    ingredient_sku varchar(32) NOT NULL,
    allergen_code varchar(16) NOT NULL,
    CONSTRAINT pk_ingredients_allergens PRIMARY KEY (ingredient_sku, allergen_code),
    CONSTRAINT fk_ingredients_allergens_owner FOREIGN KEY (ingredient_sku) REFERENCES public.ingredients (sku) ON DELETE CASCADE
);
ALTER TABLE public.ingredients_allergens DROP CONSTRAINT IF EXISTS ck_ingredients_allergens_allergen_code_ref;
ALTER TABLE public.ingredients_allergens DROP CONSTRAINT IF EXISTS fk_ingredients_allergens_allergen_code_ref;
ALTER TABLE public.ingredients_allergens ADD CONSTRAINT fk_ingredients_allergens_allergen_code_ref FOREIGN KEY (allergen_code) REFERENCES public.allergens (code);

-- Codes no longer in the seeds of Allergen.
DELETE FROM public.allergens WHERE code NOT IN ('gluten', 'nut', 'tree_nut');

-- Seed rows, targets of referenced rows first; rows whose key is already there are skipped.

-- Seed Recipe (2 rows) into recipes.
INSERT INTO public.recipes (code, name) VALUES
    ('bread', 'Bread'),
    ('soup', 'Soup')
ON CONFLICT DO NOTHING;

-- Seed Ingredient (4 rows) into ingredients.
INSERT INTO public.ingredients (sku, name, default_unit, preferred_unit, substitute_sku) VALUES
    ('flour', 'Flour', 'g', 'kg', NULL),
    ('salt', 'Salt', 'g', NULL, NULL),
    ('spelt', 'Spelt flour', 'g', 'g', 'flour'),
    ('almond', 'Almond', 'g', NULL, NULL)
ON CONFLICT DO NOTHING;
INSERT INTO public.ingredients_allergens (ingredient_sku, allergen_code) VALUES
    ('flour', 'gluten'),
    ('spelt', 'gluten'),
    ('almond', 'tree_nut')
ON CONFLICT DO NOTHING;

-- Seed contains (2 rows) into recipe_ingredient.
INSERT INTO public.recipe_ingredient (recipe_code, ingredient_sku, quantity, unit_of_measure) VALUES
    ('bread', 'flour', 500, 'g'),
    ('bread', 'salt', 0.01, 'kg')
ON CONFLICT DO NOTHING;

-- maquettiste:keep id=seed-data
-- Hand-written seed data for main goes here, for example:
-- INSERT INTO ... VALUES (...);
-- maquettiste:end-keep
