-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table shop.orders of database sqlserver (SQL Server).

IF OBJECT_ID(N'shop.orders', N'U') IS NULL
CREATE TABLE shop.orders (
    id bigint NOT NULL CONSTRAINT df_orders_id DEFAULT (NEXT VALUE FOR shop.order_number_seq),
    number nvarchar(16) NOT NULL,
    customer_id bigint NOT NULL,
    total decimal(12,2) NOT NULL CONSTRAINT df_orders_total DEFAULT 0,
    placed_on date NULL,
    CONSTRAINT pk_orders_id PRIMARY KEY (id),
    CONSTRAINT uq_orders_customer_number UNIQUE (customer_id, number),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES shop.customers (id),
    CONSTRAINT ck_orders_total CHECK (total >= 0)
);
