-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table shop.order_items of database sqlserver (SQL Server).

IF OBJECT_ID(N'shop.order_items', N'U') IS NULL
CREATE TABLE shop.order_items (
    order_id bigint NOT NULL,
    line_no int NOT NULL,
    sku nchar(20) NOT NULL,
    quantity bigint NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES shop.orders (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0)
);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_order_lines_product' AND object_id = OBJECT_ID(N'shop.order_items')) CREATE INDEX ix_order_lines_product ON shop.order_items (sku);
