-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table app.reservations of database pg (PostgreSQL).

CREATE TABLE app.reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id bigint NOT NULL,
    during tstzrange NOT NULL,
    cancelled boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_reservations PRIMARY KEY (id),
    CONSTRAINT ex_reservations_room_overlap EXCLUDE USING gist (room_id WITH =, during WITH &&) WHERE (NOT cancelled) DEFERRABLE INITIALLY DEFERRED
);
