-- Generated by Maquettiste (sql-ddl/table). Do not edit; changes are overwritten.
-- Table app.audit_events of database pg (PostgreSQL).

CREATE TABLE IF NOT EXISTS app.audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    occurred_at timestamptz(6) NOT NULL,
    payload text NULL,
    CONSTRAINT pk_audit_events PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE TABLE IF NOT EXISTS app.audit_events_2026_01 PARTITION OF app.audit_events FOR VALUES FROM ('2026-01-01') TO ('2026-02-01') WITH (autovacuum_vacuum_scale_factor = 0.03, fillfactor = 70);
CREATE TABLE IF NOT EXISTS app.audit_events_2026_02_full PARTITION OF app.audit_events FOR VALUES FROM ('2026-02-01') TO ('2026-03-01') WITH (autovacuum_vacuum_scale_factor = 0.03, fillfactor = 70);
CREATE TABLE IF NOT EXISTS app.audit_events_rest PARTITION OF app.audit_events DEFAULT WITH (autovacuum_vacuum_scale_factor = 0.03, fillfactor = 70);
