-- Migration 0001 of database main (PostgreSQL 16): schema revision 0 to 1.
-- Written once by Maquettiste (sql-ddl/migration) from the schema diff. It is yours now: review it, adjust it and commit it.
-- Lines marked TODO need a decision the diff cannot make (data conversions, sequence restarts).

BEGIN;

CREATE TABLE public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku varchar(40) NOT NULL,
    name varchar(200) NOT NULL,
    price numeric(12,2) NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_sku UNIQUE (sku)
);

CREATE TABLE public.customers (
    id uuid NOT NULL,
    name varchar(120) NOT NULL,
    email varchar(254) NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE public.notes (
    id uuid NOT NULL,
    entity_type varchar(32) NOT NULL,
    entity_id varchar(40) NOT NULL,
    body text NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notes PRIMARY KEY (id)
);
CREATE INDEX ix_notes_entity_type_entity_id ON public.notes (entity_type, entity_id);

COMMIT;
